// @generated by ores-stack rpc; do not edit

use ores_api_docs::{RpcV1Call, RpcV1HttpContext, RpcV1Receipt};

use crate::{
    model::{FindUserOperation, UpdateUserOperation},
    rpc_support::invoke_json_rpc,
    state::AppState,
};

use super::handlers;

pub async fn dispatch_find(
    state: AppState,
    http_context: RpcV1HttpContext,
    call: RpcV1Call,
) -> RpcV1Receipt {
    invoke_json_rpc::<FindUserOperation, _, _>(
        state,
        http_context,
        call,
        "ores-trace-proof-rpc-find-C5mR8xK2vQz",
        handlers::__ores_invoke_find_user_by_id,
    )
    .await
}

pub async fn dispatch_update(
    state: AppState,
    http_context: RpcV1HttpContext,
    call: RpcV1Call,
) -> RpcV1Receipt {
    invoke_json_rpc::<UpdateUserOperation, _, _>(
        state,
        http_context,
        call,
        "ores-trace-proof-rpc-update-P4nV7sJ3bWt",
        handlers::__ores_invoke_update_user,
    )
    .await
}
