//! Canonical five-language RPC client projection.
//!
//! v2 consumes both the audience-filtered route map and the handlers-authoritative
//! normalized operation IR. The route map retains transport/projection metadata;
//! the normalized IR supplies operation identity and semantic request/response
//! schemas. Public SDK methods are generated from `source.operation` and always
//! target canonical POST `/v1/rpc`.

use serde::Serialize;

use crate::{
    contract_sha256, rpc_client_bundle, typed_rpc_sdk_codegen::typed_sdk_sources, RouteMap,
    RpcOperationContract,
};

const GENERATOR: &str = "ores-api-docs rpc_client_bundle_v2";
const RPC_HTTP_PATH: &str = "/v1/rpc";

#[derive(Clone, Debug, Serialize)]
pub struct RpcClientBundleV2Manifest {
    pub schema_version: u32,
    pub generated_by: &'static str,
    pub service: String,
    pub audience: String,
    pub contract_sha256: String,
    pub operations: Vec<String>,
    pub languages: [&'static str; 5],
    pub http_endpoint: &'static str,
}

#[derive(Clone, Debug)]
pub struct RpcClientBundleV2 {
    pub manifest: RpcClientBundleV2Manifest,
    pub rust: String,
    pub go: String,
    pub dart: String,
    pub typescript: String,
    pub gleam: String,
}

/// Generate the canonical five-language v1-over-HTTP client bundle.
///
/// `map` must already be filtered for the target audience. `operations` must be
/// the matching handlers-authoritative normalized IR. A real semantic section
/// without a concrete supported schema is rejected rather than emitted as an
/// `any`/`unknown`/`serde_json::Value` public SDK type.
pub fn rpc_client_bundle_v2(
    map: &RouteMap,
    operations: &[RpcOperationContract],
    dto_module: &str,
    audience: &str,
) -> Result<RpcClientBundleV2, String> {
    if audience.trim().is_empty() {
        return Err("client audience must not be empty".to_owned());
    }
    let compatibility = rpc_client_bundle(map, dto_module, audience)?;
    let digest = contract_sha256(map);
    let typed = typed_sdk_sources(map, operations, audience, &digest)?;
    let operation_keys = operations
        .iter()
        .map(|operation| operation.operation_key.clone())
        .collect::<Vec<_>>();
    let manifest = RpcClientBundleV2Manifest {
        schema_version: 2,
        generated_by: GENERATOR,
        service: map.service.clone(),
        audience: audience.to_owned(),
        contract_sha256: digest.clone(),
        operations: operation_keys,
        languages: ["rust", "go", "dart", "typescript", "gleam"],
        http_endpoint: RPC_HTTP_PATH,
    };
    Ok(RpcClientBundleV2 {
        manifest,
        rust: compatibility.rust + &typed.rust,
        go: go_client(map, audience, &digest) + &typed.go,
        dart: compatibility.dart + &typed.dart,
        typescript: compatibility.typescript + &typed.typescript,
        gleam: gleam_client(map, audience, &digest) + &typed.gleam,
    })
}

fn go_client(map: &RouteMap, audience: &str, digest: &str) -> String {
    let allowed = map
        .map
        .values()
        .filter_map(|entry| entry.rpc_key.as_deref())
        .map(|key| format!("\t{key:?}: {{}},"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"// Code generated by {generator}; DO NOT EDIT.
package rpc

import (
    "bytes"
    "context"
    "encoding/json"
    "fmt"
    "io"
    "net/http"
    "net/url"
    "strings"
    "sync/atomic"
)

const ContractSHA256 = {digest:?}
const ClientAudience = {audience:?}
const Service = {service:?}
const HTTPPath = {rpc_path:?}

var operations = map[string]struct{{}}{{
{allowed}
}}

type CallArgs struct {{
    Path map[string]any `json:"path,omitempty"`
    Query map[string]any `json:"query,omitempty"`
    Headers map[string]any `json:"headers,omitempty"`
    Body any `json:"body,omitempty"`
    TraceID string `json:"traceId,omitempty"`
    SpanID string `json:"spanId,omitempty"`
}}

type Receipt struct {{
    V int `json:"v"`
    Op string `json:"op"`
    ID string `json:"id"`
    Key string `json:"key"`
    Transport string `json:"transport,omitempty"`
    OK bool `json:"ok"`
    Status int `json:"status,omitempty"`
    Headers map[string]any `json:"headers,omitempty"`
    Trailers map[string]any `json:"trailers,omitempty"`
    Body json.RawMessage `json:"body,omitempty"`
    Error json.RawMessage `json:"error,omitempty"`
    TraceID string `json:"traceId,omitempty"`
    SpanID string `json:"spanId,omitempty"`
}}

type RpcContext struct {{
    OK bool `json:"ok"`
    Status int `json:"status"`
    ID string `json:"id"`
    Key string `json:"key"`
    Transport string `json:"transport"`
    Headers map[string]any `json:"headers"`
    Trailers map[string]any `json:"trailers"`
    Errors []json.RawMessage `json:"errors"`
    TraceID string `json:"traceId,omitempty"`
    TraceIDs []string `json:"traceIds"`
    SpanID string `json:"spanId,omitempty"`
}}

type RpcRemoteError struct {{ Context RpcContext }}
func (e *RpcRemoteError) Error() string {{
    return fmt.Sprintf("RPC %s failed with status %d", e.Context.Key, e.Context.Status)
}}

type Client struct {{
    BaseURL *url.URL
    HTTP *http.Client
    sequence atomic.Uint64
}}

type CallBuilder struct {{
    client *Client
    key string
    args CallArgs
    buildErr error
}}

func (b *CallBuilder) AddHeader(name string, value any) *CallBuilder {{
    if b.args.Headers == nil {{ b.args.Headers = map[string]any{{}} }}
    b.args.Headers[name] = value
    return b
}}
func (b *CallBuilder) AddHeaders(values map[string]any) *CallBuilder {{
    if b.args.Headers == nil {{ b.args.Headers = map[string]any{{}} }}
    for key, value := range values {{ b.args.Headers[key] = value }}
    return b
}}
func (b *CallBuilder) AddPathField(name string, value any) *CallBuilder {{
    if b.args.Path == nil {{ b.args.Path = map[string]any{{}} }}
    b.args.Path[name] = value
    return b
}}
func (b *CallBuilder) AddQueryField(name string, value any) *CallBuilder {{
    if b.args.Query == nil {{ b.args.Query = map[string]any{{}} }}
    b.args.Query[name] = value
    return b
}}
func (b *CallBuilder) AddBodyField(name string, value any) *CallBuilder {{
    if b.buildErr != nil {{ return b }}
    body, ok := b.args.Body.(map[string]any)
    if b.args.Body == nil {{
        body = map[string]any{{}}
        ok = true
    }} else if !ok {{
        raw, err := json.Marshal(b.args.Body)
        if err != nil {{ b.buildErr = err; return b }}
        if err := json.Unmarshal(raw, &body); err != nil {{ b.buildErr = fmt.Errorf("AddBodyField requires an object RPC body: %w", err); return b }}
        ok = true
    }}
    if !ok {{ b.buildErr = fmt.Errorf("AddBodyField requires an object RPC body"); return b }}
    body[name] = value
    b.args.Body = body
    return b
}}
func (b *CallBuilder) WithBody(value any) *CallBuilder {{ b.args.Body = value; return b }}
func (b *CallBuilder) WithTraceID(value string) *CallBuilder {{ b.args.TraceID = value; return b }}
func (b *CallBuilder) WithSpanID(value string) *CallBuilder {{ b.args.SpanID = value; return b }}
func (b *CallBuilder) MakeCallRaw(ctx context.Context) (json.RawMessage, RpcContext, error) {{
    if b.buildErr != nil {{ return nil, RpcContext{{}}, b.buildErr }}
    return b.client.SendRaw(ctx, b.key, b.args)
}}

type TypedCall[T any] struct {{ builder *CallBuilder }}
func NewTypedCall[T any](builder *CallBuilder) *TypedCall[T] {{ return &TypedCall[T]{{builder: builder}} }}
func (b *TypedCall[T]) AddHeader(name string, value any) *TypedCall[T] {{ b.builder.AddHeader(name, value); return b }}
func (b *TypedCall[T]) AddHeaders(values map[string]any) *TypedCall[T] {{ b.builder.AddHeaders(values); return b }}
func (b *TypedCall[T]) AddPathField(name string, value any) *TypedCall[T] {{ b.builder.AddPathField(name, value); return b }}
func (b *TypedCall[T]) AddQueryField(name string, value any) *TypedCall[T] {{ b.builder.AddQueryField(name, value); return b }}
func (b *TypedCall[T]) AddBodyField(name string, value any) *TypedCall[T] {{ b.builder.AddBodyField(name, value); return b }}
func (b *TypedCall[T]) WithBody(value any) *TypedCall[T] {{ b.builder.WithBody(value); return b }}
func (b *TypedCall[T]) MakeCall(ctx context.Context) (*T, RpcContext, error) {{
    raw, rpcCtx, err := b.builder.MakeCallRaw(ctx)
    if err != nil {{ return nil, rpcCtx, err }}
    if len(raw) == 0 {{ return nil, rpcCtx, nil }}
    var out T
    if err := json.Unmarshal(raw, &out); err != nil {{ return nil, rpcCtx, err }}
    return &out, rpcCtx, nil
}}
func (b *TypedCall[T]) MakeCallOrError(ctx context.Context) (*T, error) {{
    out, rpcCtx, err := b.MakeCall(ctx)
    if err != nil {{ return nil, err }}
    if !rpcCtx.OK {{ return nil, &RpcRemoteError{{Context: rpcCtx}} }}
    if out == nil {{ return nil, fmt.Errorf("RPC %s succeeded without a body", rpcCtx.Key) }}
    return out, nil
}}

func NewClient(baseURL string, client *http.Client) (*Client, error) {{
    parsed, err := url.Parse(baseURL)
    if err != nil {{ return nil, err }}
    if client == nil {{ client = http.DefaultClient }}
    return &Client{{BaseURL: parsed, HTTP: client}}, nil
}}

func (c *Client) Prepare(key string, args CallArgs) *CallBuilder {{
    return &CallBuilder{{client: c, key: key, args: args}}
}}

func (c *Client) SendRaw(ctx context.Context, key string, args CallArgs) (json.RawMessage, RpcContext, error) {{
    var rpcCtx RpcContext
    if _, ok := operations[key]; !ok {{
        return nil, rpcCtx, fmt.Errorf("RPC operation not generated for this audience: %s", key)
    }}
    id := fmt.Sprintf("go-%d", c.sequence.Add(1))
    envelope := map[string]any{{
        "v": 1, "op": "call", "id": id, "key": key, "transport": "http",
    }}
    if args.Path != nil {{ envelope["path"] = args.Path }}
    if args.Query != nil {{ envelope["query"] = args.Query }}
    if args.Headers != nil {{ envelope["headers"] = args.Headers }}
    if args.Body != nil {{ envelope["body"] = args.Body }}
    if args.TraceID != "" {{ envelope["traceId"] = args.TraceID }}
    if args.SpanID != "" {{ envelope["spanId"] = args.SpanID }}
    encoded, err := json.Marshal(envelope)
    if err != nil {{ return nil, rpcCtx, err }}
    endpoint := *c.BaseURL
    endpoint.Path = strings.TrimRight(endpoint.Path, "/") + HTTPPath
    request, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint.String(), bytes.NewReader(encoded))
    if err != nil {{ return nil, rpcCtx, err }}
    request.Header.Set("content-type", "application/json")
    response, err := c.HTTP.Do(request)
    if err != nil {{ return nil, rpcCtx, err }}
    defer response.Body.Close()
    raw, err := io.ReadAll(response.Body)
    if err != nil {{ return nil, rpcCtx, err }}
    var receipt Receipt
    if err := json.Unmarshal(raw, &receipt); err != nil {{ return nil, rpcCtx, err }}
    if receipt.ID != id || receipt.Key != key {{ return nil, rpcCtx, fmt.Errorf("RPC receipt correlation mismatch") }}
    errors := []json.RawMessage{{}}
    if len(receipt.Error) != 0 {{ errors = []json.RawMessage{{receipt.Error}} }}
    traceIDs := []string{{}}
    if receipt.TraceID != "" {{ traceIDs = []string{{receipt.TraceID}} }}
    status := receipt.Status
    if status == 0 {{ status = response.StatusCode }}
    transport := receipt.Transport
    if transport == "" {{ transport = "http" }}
    rpcCtx = RpcContext{{
        OK: receipt.OK && status < 400,
        Status: status,
        ID: receipt.ID,
        Key: receipt.Key,
        Transport: transport,
        Headers: receipt.Headers,
        Trailers: receipt.Trailers,
        Errors: errors,
        TraceID: receipt.TraceID,
        TraceIDs: traceIDs,
        SpanID: receipt.SpanID,
    }}
    return receipt.Body, rpcCtx, nil
}}

func (c *Client) Call(ctx context.Context, key string, args CallArgs, out any) error {{
    raw, rpcCtx, err := c.SendRaw(ctx, key, args)
    if err != nil {{ return err }}
    if !rpcCtx.OK {{ return &RpcRemoteError{{Context: rpcCtx}} }}
    if out != nil && len(raw) != 0 {{ return json.Unmarshal(raw, out) }}
    return nil
}}
"#,
        generator = GENERATOR,
        digest = digest,
        audience = audience,
        service = map.service,
        rpc_path = RPC_HTTP_PATH,
        allowed = allowed,
    )
}

fn gleam_client(map: &RouteMap, audience: &str, digest: &str) -> String {
    let allowed = map
        .map
        .values()
        .filter_map(|entry| entry.rpc_key.as_deref())
        .map(|key| format!("    {key:?} -> True"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"// @generated by {generator}; do not edit.
import gleam/dynamic
import gleam/dynamic/decode
import gleam/json
import gleam/list
import gleam/option
import gleam/string

pub const rpc_contract_sha256 = {digest:?}
pub const rpc_client_audience = {audience:?}
pub const rpc_service = {service:?}
pub const rpc_http_path = {rpc_path:?}

pub type CallArgs {{
  CallArgs(
    path: List(#(String, json.Json)),
    query: List(#(String, json.Json)),
    headers: List(#(String, json.Json)),
    body: option.Option(json.Json),
    body_fields: List(#(String, json.Json)),
    trace_id: option.Option(String),
    span_id: option.Option(String),
  )
}}

pub type RpcContext {{
  RpcContext(
    ok: Bool,
    status: Int,
    headers: option.Option(dynamic.Dynamic),
    trailers: option.Option(dynamic.Dynamic),
    errors: List(dynamic.Dynamic),
    trace_id: option.Option(String),
    trace_ids: List(String),
    span_id: option.Option(String),
  )
}}

pub type Outcome(a) {{
  Outcome(value: option.Option(a), context: RpcContext)
}}

pub type Receipt {{
  Receipt(
    id: String,
    key: String,
    ok: Bool,
    status: option.Option(Int),
    headers: option.Option(dynamic.Dynamic),
    trailers: option.Option(dynamic.Dynamic),
    body: option.Option(dynamic.Dynamic),
    error: option.Option(dynamic.Dynamic),
    trace_id: option.Option(String),
    span_id: option.Option(String),
  )
}}

pub fn receipt_decoder() -> decode.Decoder(Receipt) {{
  use id <- decode.field("id", decode.string)
  use key <- decode.field("key", decode.string)
  use ok <- decode.field("ok", decode.bool)
  use status <- decode.optional_field("status", option.None, decode.optional(decode.int))
  use headers <- decode.optional_field("headers", option.None, decode.optional(decode.dynamic))
  use trailers <- decode.optional_field("trailers", option.None, decode.optional(decode.dynamic))
  use body <- decode.optional_field("body", option.None, decode.optional(decode.dynamic))
  use error <- decode.optional_field("error", option.None, decode.optional(decode.dynamic))
  use trace_id <- decode.optional_field("traceId", option.None, decode.optional(decode.string))
  use span_id <- decode.optional_field("spanId", option.None, decode.optional(decode.string))
  decode.success(Receipt(id, key, ok, status, headers, trailers, body, error, trace_id, span_id))
}}

pub fn operation_allowed(key: String) -> Bool {{
  case key {{
{allowed}
    _ -> False
  }}
}}

pub type Transport {{
  Transport(fn(String, String) -> Result(String, String))
}}

pub type CallBuilder {{
  CallBuilder(
    transport: Transport,
    base_url: String,
    id: String,
    key: String,
    args: CallArgs,
  )
}}

pub type TypedCall(a) {{
  TypedCall(builder: CallBuilder, decoder: decode.Decoder(a))
}}

pub fn prepare(
  transport: Transport,
  base_url: String,
  id: String,
  key: String,
  args: CallArgs,
) -> CallBuilder {{
  CallBuilder(transport, base_url, id, key, args)
}}

pub fn typed(builder: CallBuilder, decoder: decode.Decoder(a)) -> TypedCall(a) {{
  TypedCall(builder, decoder)
}}

fn replace_field(
  fields: List(#(String, json.Json)),
  name: String,
  value: json.Json,
) -> List(#(String, json.Json)) {{
  [#(name, value), ..list.filter(fields, fn(item) {{ item.0 != name }})]
}}

pub fn add_header(call: TypedCall(a), name: String, value: json.Json) -> TypedCall(a) {{
  let TypedCall(CallBuilder(transport, base_url, id, key, args), decoder) = call
  let CallArgs(path, query, headers, body, body_fields, trace_id, span_id) = args
  TypedCall(
    CallBuilder(transport, base_url, id, key, CallArgs(path, query, replace_field(headers, name, value), body, body_fields, trace_id, span_id)),
    decoder,
  )
}}

pub fn add_headers(call: TypedCall(a), values: List(#(String, json.Json))) -> TypedCall(a) {{
  list.fold(values, call, fn(current, item) {{ add_header(current, item.0, item.1) }})
}}

pub fn add_body_field(call: TypedCall(a), name: String, value: json.Json) -> TypedCall(a) {{
  let TypedCall(CallBuilder(transport, base_url, id, key, args), decoder) = call
  let CallArgs(path, query, headers, body, body_fields, trace_id, span_id) = args
  TypedCall(
    CallBuilder(transport, base_url, id, key, CallArgs(path, query, headers, body, replace_field(body_fields, name, value), trace_id, span_id)),
    decoder,
  )
}}

fn send_raw(builder: CallBuilder) -> Result(Outcome(dynamic.Dynamic), String) {{
  let CallBuilder(transport, base_url, id, key, args) = builder
  case operation_allowed(key) {{
    False -> Error("RPC operation not generated for this audience")
    True -> {{
      let CallArgs(path, query, headers, body, body_fields, trace_id, span_id) = args
      let members = [
        #("v", json.int(1)),
        #("op", json.string("call")),
        #("id", json.string(id)),
        #("key", json.string(key)),
        #("transport", json.string("http")),
      ]
      let members = case path {{ [] -> members; value -> [#("path", json.object(value)), ..members] }}
      let members = case query {{ [] -> members; value -> [#("query", json.object(value)), ..members] }}
      let members = case headers {{ [] -> members; value -> [#("headers", json.object(value)), ..members] }}
      let body = case body_fields {{ [] -> body; fields -> option.Some(json.object(fields)) }}
      let members = case body {{ option.None -> members; option.Some(value) -> [#("body", value), ..members] }}
      let members = case trace_id {{ option.None -> members; option.Some(value) -> [#("traceId", json.string(value)), ..members] }}
      let members = case span_id {{ option.None -> members; option.Some(value) -> [#("spanId", json.string(value)), ..members] }}
      let Transport(send_transport) = transport
      use response <- result.try(send_transport(base_url <> rpc_http_path, json.to_string(json.object(members))))
      use receipt <- result.try(json.parse(response, receipt_decoder()) |> result.map_error(string.inspect))
      let Receipt(receipt_id, receipt_key, ok, status, response_headers, trailers, response_body, error, primary_trace_id, response_span_id) = receipt
      case receipt_id == id && receipt_key == key {{
        False -> Error("RPC receipt correlation mismatch")
        True -> {{
          let errors = case error {{ option.Some(value) -> [value]; option.None -> [] }}
          let trace_ids = case primary_trace_id {{ option.Some(value) -> [value]; option.None -> [] }}
          let status = option.unwrap(status, if ok {{ 200 }} else {{ 500 }})
          Ok(Outcome(
            response_body,
            RpcContext(ok && status < 400, status, response_headers, trailers, errors, primary_trace_id, trace_ids, response_span_id),
          ))
        }}
      }}
    }}
  }}
}}

pub fn make_call(call: TypedCall(a)) -> Result(Outcome(a), String) {{
  let TypedCall(builder, decoder) = call
  use raw <- result.try(send_raw(builder))
  let Outcome(value, context) = raw
  case value {{
    option.None -> Ok(Outcome(option.None, context))
    option.Some(body) ->
      case decode.run(body, decoder) {{
        Ok(decoded) -> Ok(Outcome(option.Some(decoded), context))
        Error(errors) -> Error(string.inspect(errors))
      }}
  }}
}}
"#,
        generator = GENERATOR,
        digest = digest,
        audience = audience,
        service = map.service,
        rpc_path = RPC_HTTP_PATH,
        allowed = allowed,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        RpcClientAudience, RpcCodecSet, RpcHttpProjection, RpcOperationScope, RpcOperationSource,
        RpcPayloadCodec, RpcRequestShape, RpcResponseShape, RpcStreamMode,
    };
    use serde_json::json;

    fn sample_map() -> RouteMap {
        RouteMap::from_json_str(
            r#"{
              "schema_version":"1.0.0",
              "service":"demo-api",
              "map":{
                "demo.health.get_version":{
                  "path":"/v1/version",
                  "methods":["GET"],
                  "rpc_key":"demo.health.get_version",
                  "transports":["http"]
                }
              }
            }"#,
        )
        .unwrap_or_else(|error| panic!("sample route map failed: {error}"))
    }

    fn sample_operation() -> RpcOperationContract {
        RpcOperationContract {
            schema_version: crate::RPC_OPERATION_CONTRACT_SCHEMA_VERSION,
            operation_key: "demo.health.get_version".to_owned(),
            namespace: vec!["demo".to_owned(), "health".to_owned()],
            source: RpcOperationSource {
                route_file: Some("src/routes/version/route.rs".to_owned()),
                handlers_file: None,
                http_handler: Some("get".to_owned()),
                operation: Some("get_version".to_owned()),
                invoker: Some("__ores_invoke_get_version".to_owned()),
                execution_model: "shared_operation".to_owned(),
                repository: None,
                commit_sha: None,
            },
            rpc_transport_path: "/v1/rpc",
            http: Some(RpcHttpProjection {
                method: "GET".to_owned(),
                path: "/v1/version".to_owned(),
            }),
            scope: RpcOperationScope::Regular,
            stream: RpcStreamMode::Unary,
            audiences: vec![RpcClientAudience::Browser, RpcClientAudience::Server],
            codecs: RpcCodecSet {
                allowed: vec![RpcPayloadCodec::Json],
                default: RpcPayloadCodec::Json,
            },
            request: RpcRequestShape::default(),
            response: RpcResponseShape {
                header_schema: None,
                trailer_schema: None,
                body_schema: Some(json!({
                    "type":"object",
                    "additionalProperties":false,
                    "properties":{
                        "result":{
                            "type":"object",
                            "additionalProperties":false,
                            "properties":{"service":{"type":"string"},"version":{"type":"string"}},
                            "required":["service","version"]
                        },
                        "traceIds":{"type":"array","items":{"type":"string"}}
                    },
                    "required":["result","traceIds"]
                })),
                error_schema: Some(json!({
                    "type":"object",
                    "additionalProperties":false,
                    "properties":{"code":{"type":"string"},"message":{"type":"string"}},
                    "required":["code","message"]
                })),
            },
            contract_sha256: "0".repeat(64),
        }
    }

    #[test]
    fn emits_named_typed_five_language_bundle() {
        let operation = sample_operation();
        let bundle = rpc_client_bundle_v2(&sample_map(), &[operation], "crate::dto", "public")
            .unwrap_or_else(|error| panic!("bundle generation failed: {error}"));
        assert_eq!(bundle.manifest.http_endpoint, "/v1/rpc");
        assert_eq!(bundle.manifest.operations, vec!["demo.health.get_version"]);
        assert!(bundle.rust.contains("pub fn get_version"));
        assert!(bundle.rust.contains("GetVersionResponseResult"));
        assert!(bundle.rust.contains("TYPED_RPC_HTTP_PATH"));
        assert!(bundle.go.contains("func (c *Client) GetVersion"));
        assert!(bundle
            .dart
            .contains("RpcCallBuilder<GetVersionResponse> getVersion"));
        assert!(bundle
            .typescript
            .contains("getVersion(input: GetVersionInput): RpcCallBuilder"));
        assert!(bundle
            .typescript
            .contains("RpcCallBuilder<GetVersionResponse"));
        assert!(bundle.gleam.contains("pub fn get_version"));
        assert!(bundle
            .typescript
            .contains("@oresoftware/api-docs/fluent-rpc"));
        assert!(bundle
            .typescript
            .contains("getVersion(input: GetVersionInput): RpcCallBuilder"));
        assert!(bundle.dart.contains("Future<RpcOutcome<T>> makeCall()"));
        assert!(bundle
            .go
            .contains("func (b *TypedCall[T]) MakeCall(ctx context.Context)"));
        assert!(bundle.rust.contains("pub async fn make_call(self)"));
        assert!(bundle
            .gleam
            .contains("pub fn make_call(call: TypedCall(a))"));
        assert!(!bundle.typescript.contains("send(): Promise<RpcOutcome"));
        assert!(!bundle
            .typescript
            .contains("getVersion(input: GetVersionInput): Promise<unknown>"));
    }

    #[test]
    fn streaming_operation_is_never_emitted_as_v1_unary_client() {
        let mut operation = sample_operation();
        operation.operation_key = "demo.health.watch_version_stream".to_owned();
        operation.source.operation = Some("watch_version_stream".to_owned());
        operation.source.invoker = Some("__ores_invoke_watch_version_stream".to_owned());
        operation.stream = RpcStreamMode::ServerStream;
        let map = RouteMap::from_json_str(
            r#"{
              "schema_version":"1.0.0",
              "service":"demo-api",
              "map":{
                "demo.health.watch_version_stream":{
                  "path":"/v1/version/stream",
                  "methods":["GET"],
                  "rpc_key":"demo.health.watch_version_stream",
                  "transports":["websocket","tcp"]
                }
              }
            }"#,
        )
        .expect("stream map");
        let error = rpc_client_bundle_v2(&map, &[operation], "crate::dto", "public")
            .expect_err("v1 unary generator must reject streaming operations");
        assert!(error.contains("unary-only"));
        assert!(error.contains("framed streaming SDK"));
    }

    #[test]
    fn rejects_untyped_open_object_in_semantic_schema() {
        let mut operation = sample_operation();
        operation.response.body_schema = Some(json!({"type":"object"}));
        let error = rpc_client_bundle_v2(&sample_map(), &[operation], "crate::dto", "public")
            .expect_err("open object must fail closed");
        assert!(error.contains("open/untyped object schemas are forbidden"));
    }
}
