//! Shared client-SDK projection from one normalized API route map.
//!
//! Product build tools such as `ores-stack` own repository discovery, audience
//! filtering, and filesystem materialization. This module owns the generated
//! client source so Rust, TypeScript, Dart, and browser WASM cannot drift into
//! four independent RPC dialects.

use std::collections::BTreeMap;

use serde::Serialize;
use serde_json::Value;

use crate::{contract_sha256, rpc_pool_bindings, RouteMap};

const GENERATOR: &str = "ores-api-docs rpc_client_bundle";
const RPC_HTTP_PATH: &str = "/v1/rpc";

#[derive(Clone, Debug, Serialize)]
pub struct RpcClientBundleManifest {
    pub schema_version: u32,
    pub generated_by: &'static str,
    pub service: String,
    pub audience: String,
    pub contract_sha256: String,
    pub operations: Vec<String>,
    pub languages: [&'static str; 4],
    pub http_endpoint: &'static str,
}

#[derive(Clone, Debug)]
pub struct RpcClientBundle {
    pub manifest: RpcClientBundleManifest,
    pub rust: String,
    pub typescript: String,
    pub dart: String,
    pub wasm_cargo_toml: String,
    pub wasm_rust: String,
}

/// Generate all client-language surfaces for an already audience-filtered map.
///
/// The route map remains authoritative. `audience` is carried into generated
/// metadata so internal and public packages cannot be mistaken for each other.
/// Rust body/response bindings may reference authored DTOs under `dto_module`;
/// route-local transport DTOs are generated inline by `rpc_pool_bindings`.
pub fn rpc_client_bundle(
    map: &RouteMap,
    dto_module: &str,
    audience: &str,
) -> Result<RpcClientBundle, String> {
    if audience.trim().is_empty() {
        return Err("client audience must not be empty".to_owned());
    }
    let digest = contract_sha256(map);
    let operations = map.map.keys().cloned().collect::<Vec<_>>();
    let manifest = RpcClientBundleManifest {
        schema_version: 1,
        generated_by: GENERATOR,
        service: map.service.clone(),
        audience: audience.to_owned(),
        contract_sha256: digest.clone(),
        operations,
        languages: ["rust", "typescript", "dart", "wasm"],
        http_endpoint: RPC_HTTP_PATH,
    };
    Ok(RpcClientBundle {
        rust: rust_client(map, dto_module, audience, &digest)?,
        typescript: typescript_client(map, audience, &digest),
        dart: dart_client(map, audience, &digest),
        wasm_cargo_toml: wasm_cargo_toml(map),
        wasm_rust: wasm_client(map, audience, &digest),
        manifest,
    })
}

fn rust_client(
    map: &RouteMap,
    dto_module: &str,
    audience: &str,
    digest: &str,
) -> Result<String, String> {
    let bindings = rpc_pool_bindings(map, dto_module)?;
    Ok(format!(
        "// @generated by {GENERATOR}; do not edit.\n\
         pub const RPC_CONTRACT_SHA256: &str = {digest:?};\n\
         pub const RPC_CLIENT_AUDIENCE: &str = {audience:?};\n\
         pub const RPC_SERVICE: &str = {service:?};\n\
         pub const RPC_HTTP_PATH: &str = {rpc_path:?};\n\n\
         {bindings}",
        service = map.service,
        rpc_path = RPC_HTTP_PATH,
    ))
}

fn typescript_client(map: &RouteMap, audience: &str, digest: &str) -> String {
    let metadata = operation_metadata(map);
    let routes = serde_json::to_string(&metadata).unwrap_or_else(|_| "{}".to_owned());
    format!(
        r#"/** @generated by {generator}; do not edit. */
export const RPC_CONTRACT_SHA256 = {digest:?} as const;
export const RPC_CLIENT_AUDIENCE = {audience:?} as const;
export const RPC_SERVICE = {service:?} as const;
export const RPC_HTTP_PATH = {rpc_path:?} as const;
export const RPC_OPERATIONS = {routes} as const;
export type RpcOperation = keyof typeof RPC_OPERATIONS;
export type RpcJsonObject = Record<string, unknown>;

export interface RpcCallArgs {{
  path?: RpcJsonObject;
  query?: RpcJsonObject;
  headers?: RpcJsonObject;
  body?: unknown;
  traceId?: string;
  spanId?: string;
}}

export interface RpcReceipt {{
  v: 1;
  op: "receipt";
  id: string;
  key: string;
  transport?: "http" | "tcp" | "websocket" | "nats";
  ok: boolean;
  status?: number;
  headers?: RpcJsonObject;
  trailers?: RpcJsonObject;
  body?: unknown;
  error?: RpcJsonObject;
  errors?: RpcJsonObject[];
  traceId?: string;
  traceIds?: string[];
  spanId?: string;
}}

export interface RpcContext<E = RpcJsonObject> {{
  ok: boolean;
  status: number;
  id: string;
  key: string;
  transport: "http" | "tcp" | "websocket" | "nats";
  headers: RpcJsonObject;
  trailers: RpcJsonObject;
  errors: E[];
  traceId?: string;
  traceIds: string[];
  spanId?: string;
}}

export type RpcOutcome<T, E = RpcJsonObject> = readonly [T | undefined, RpcContext<E>];

export class RpcRemoteError<E = RpcJsonObject> extends Error {{
  public readonly ctx: RpcContext<E>;

  constructor(ctx: RpcContext<E>) {{
    super(`RPC ${{ctx.key}} failed with status ${{ctx.status}}`);
    this.ctx = ctx;
  }}
}}

export class RpcCallBuilder<T = unknown, E = RpcJsonObject> {{
  private readonly args: RpcCallArgs;

  constructor(
    private readonly client: RpcClient,
    private readonly key: RpcOperation,
    args: RpcCallArgs = {{}},
  ) {{
    this.args = {{
      ...args,
      path: args.path === undefined ? undefined : {{ ...args.path }},
      query: args.query === undefined ? undefined : {{ ...args.query }},
      headers: args.headers === undefined ? undefined : {{ ...args.headers }},
      body:
        args.body !== null && typeof args.body === "object" && !Array.isArray(args.body)
          ? {{ ...(args.body as RpcJsonObject) }}
          : args.body,
    }};
  }}

  addHeader(name: string, value: unknown): this {{
    this.args.headers ??= {{}};
    this.args.headers[name] = value;
    return this;
  }}

  addHeaders(values: RpcJsonObject): this {{
    this.args.headers = {{ ...(this.args.headers ?? {{}}), ...values }};
    return this;
  }}

  addPathField(name: string, value: unknown): this {{
    this.args.path ??= {{}};
    this.args.path[name] = value;
    return this;
  }}

  addQueryField(name: string, value: unknown): this {{
    this.args.query ??= {{}};
    this.args.query[name] = value;
    return this;
  }}

  addBodyField(name: string, value: unknown): this {{
    if (this.args.body === undefined) this.args.body = {{}};
    if (this.args.body === null || typeof this.args.body !== "object" || Array.isArray(this.args.body)) {{
      throw new TypeError("addBodyField requires an object RPC body");
    }}
    (this.args.body as RpcJsonObject)[name] = value;
    return this;
  }}

  withBody(body: unknown): this {{
    this.args.body = body;
    return this;
  }}

  withTraceId(traceId: string): this {{
    this.args.traceId = traceId;
    return this;
  }}

  withSpanId(spanId: string): this {{
    this.args.spanId = spanId;
    return this;
  }}

  send(): Promise<RpcOutcome<T, E>> {{
    return this.client.send<T, E>(this.key, this.args);
  }}

  async sendOrThrow(): Promise<T> {{
    const [value, ctx] = await this.send();
    if (!ctx.ok) throw new RpcRemoteError(ctx);
    if (value === undefined) throw new Error(`RPC ${{ctx.key}} succeeded without a body`);
    return value;
  }}
}}

export class RpcClient {{
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;

  constructor(
    baseUrl: string,
    fetchImpl: typeof fetch = globalThis.fetch.bind(globalThis),
  ) {{
    this.baseUrl = baseUrl;
    this.fetchImpl = fetchImpl;
  }}

  prepare<T = unknown, E = RpcJsonObject>(
    key: RpcOperation,
    args: RpcCallArgs = {{}},
  ): RpcCallBuilder<T, E> {{
    if (!(key in RPC_OPERATIONS)) {{
      throw new Error(`RPC operation not generated for this audience: ${{String(key)}}`);
    }}
    return new RpcCallBuilder<T, E>(this, key, args);
  }}

  async send<T = unknown, E = RpcJsonObject>(
    key: RpcOperation,
    args: RpcCallArgs = {{}},
  ): Promise<RpcOutcome<T, E>> {{
    if (!(key in RPC_OPERATIONS)) {{
      throw new Error(`RPC operation not generated for this audience: ${{String(key)}}`);
    }}
    const id = globalThis.crypto?.randomUUID?.() ?? `ores-${{Date.now()}}-${{Math.random()}}`;
    const envelope = {{
      v: 1,
      op: "call",
      id,
      key,
      transport: "http",
      ...(args.path === undefined ? {{}} : {{ path: args.path }}),
      ...(args.query === undefined ? {{}} : {{ query: args.query }}),
      ...(args.headers === undefined ? {{}} : {{ headers: args.headers }}),
      ...(args.body === undefined ? {{}} : {{ body: args.body }}),
      ...(args.traceId === undefined ? {{}} : {{ traceId: args.traceId }}),
      ...(args.spanId === undefined ? {{}} : {{ spanId: args.spanId }}),
    }};
    const response = await this.fetchImpl(new URL(RPC_HTTP_PATH, this.baseUrl), {{
      method: "POST",
      headers: {{ "content-type": "application/json" }},
      body: JSON.stringify(envelope),
    }});
    const receipt = (await response.json()) as RpcReceipt;
    if (receipt.id !== id || receipt.key !== key) {{
      throw new Error("RPC receipt correlation mismatch");
    }}
    const errors = (
      receipt.errors?.length ? receipt.errors : receipt.error === undefined ? [] : [receipt.error]
    ) as E[];
    const traceIds =
      receipt.traceIds?.length ? receipt.traceIds : receipt.traceId === undefined ? [] : [receipt.traceId];
    const ctx: RpcContext<E> = {{
      ok: receipt.ok && response.status < 400,
      status: receipt.status ?? response.status,
      id: receipt.id,
      key: receipt.key,
      transport: receipt.transport ?? "http",
      headers: receipt.headers ?? {{}},
      trailers: receipt.trailers ?? {{}},
      errors,
      traceId: receipt.traceId,
      traceIds,
      spanId: receipt.spanId,
    }};
    return [receipt.body as T | undefined, ctx] as const;
  }}

  async call<K extends RpcOperation>(key: K, args: RpcCallArgs = {{}}): Promise<unknown> {{
    return this.prepare(key, args).sendOrThrow();
  }}
}}
"#,
        generator = GENERATOR,
        digest = digest,
        audience = audience,
        service = map.service,
        rpc_path = RPC_HTTP_PATH,
        routes = routes,
    )
}

fn dart_client(map: &RouteMap, audience: &str, digest: &str) -> String {
    let keys = map
        .map
        .keys()
        .map(|key| format!("  {key:?},"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"// @generated by {generator}; do not edit.
import 'dart:convert';

const rpcContractSha256 = {digest:?};
const rpcClientAudience = {audience:?};
const rpcService = {service:?};
const rpcHttpPath = {rpc_path:?};
const rpcOperations = <String>{{
{keys}
}};

class RpcHttpResponse {{
  const RpcHttpResponse(this.statusCode, this.body);
  final int statusCode;
  final String body;
}}

typedef RpcHttpTransport = Future<RpcHttpResponse> Function(
  Uri uri,
  Map<String, String> headers,
  String body,
);

class RpcRemoteException implements Exception {{
  const RpcRemoteException(this.receipt);
  final Map<String, Object?> receipt;
  @override
  String toString() => 'RPC ${{receipt['key']}} failed with status ${{receipt['status']}}';
}}

class OresRpcClient {{
  OresRpcClient({{required this.baseUri, required this.transport}});
  final Uri baseUri;
  final RpcHttpTransport transport;
  int _sequence = 0;

  Future<Object?> call(
    String key, {{
    Map<String, Object?>? path,
    Map<String, Object?>? query,
    Map<String, Object?>? headers,
    Object? body,
    String? traceId,
    String? spanId,
  }}) async {{
    if (!rpcOperations.contains(key)) {{
      throw ArgumentError.value(key, 'key', 'RPC operation not generated for this audience');
    }}
    final id = 'dart-${{DateTime.now().microsecondsSinceEpoch}}-${{_sequence++}}';
    final envelope = <String, Object?>{{
      'v': 1,
      'op': 'call',
      'id': id,
      'key': key,
      'transport': 'http',
      if (path != null) 'path': path,
      if (query != null) 'query': query,
      if (headers != null) 'headers': headers,
      if (body != null) 'body': body,
      if (traceId != null) 'traceId': traceId,
      if (spanId != null) 'spanId': spanId,
    }};
    final response = await transport(
      baseUri.resolve(rpcHttpPath),
      const {{'content-type': 'application/json'}},
      jsonEncode(envelope),
    );
    final decoded = jsonDecode(response.body);
    if (decoded is! Map<String, dynamic>) {{
      throw const FormatException('RPC receipt must be a JSON object');
    }}
    final receipt = decoded.cast<String, Object?>();
    if (receipt['id'] != id || receipt['key'] != key) {{
      throw const FormatException('RPC receipt correlation mismatch');
    }}
    if (receipt['ok'] != true) throw RpcRemoteException(receipt);
    return receipt['body'];
  }}
}}
"#,
        generator = GENERATOR,
        digest = digest,
        audience = audience,
        service = map.service,
        rpc_path = RPC_HTTP_PATH,
        keys = keys,
    )
}

fn wasm_cargo_toml(map: &RouteMap) -> String {
    let package = sanitize_package(&map.service);
    format!(
        r#"[package]
name = "{package}-rpc-wasm"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
serde = {{ version = "1", features = ["derive"] }}
serde-wasm-bindgen = "0.6"
serde_json = "1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = {{ version = "0.3", features = ["Headers", "Request", "RequestInit", "RequestMode", "Response", "Window"] }}
"#
    )
}

fn wasm_client(map: &RouteMap, audience: &str, digest: &str) -> String {
    let allowed = map
        .map
        .keys()
        .map(|key| format!("        {key:?} => true,"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"// @generated by {generator}; do not edit.
#![forbid(unsafe_code)]

use js_sys::{{Date, Math}};
use serde_json::Value;
use wasm_bindgen::{{prelude::*, JsCast}};
use wasm_bindgen_futures::JsFuture;
use web_sys::{{Request, RequestInit, RequestMode, Response}};

pub const RPC_CONTRACT_SHA256: &str = {digest:?};
pub const RPC_CLIENT_AUDIENCE: &str = {audience:?};
pub const RPC_SERVICE: &str = {service:?};
pub const RPC_HTTP_PATH: &str = {rpc_path:?};

fn allowed_operation(key: &str) -> bool {{
    match key {{
{allowed}
        _ => false,
    }}
}}

#[wasm_bindgen]
pub struct RpcClient {{
    base_url: String,
}}

#[wasm_bindgen]
impl RpcClient {{
    #[wasm_bindgen(constructor)]
    pub fn new(base_url: String) -> Self {{
        Self {{ base_url }}
    }}

    #[wasm_bindgen]
    pub async fn call(&self, key: String, body: JsValue) -> Result<JsValue, JsValue> {{
        if !allowed_operation(&key) {{
            return Err(JsValue::from_str("RPC operation is not generated for this audience"));
        }}
        let id = format!("wasm-{{}}-{{}}", Date::now(), Math::random());
        let body_value: Value = if body.is_undefined() || body.is_null() {{
            Value::Null
        }} else {{
            serde_wasm_bindgen::from_value(body)
                .map_err(|error| JsValue::from_str(&error.to_string()))?
        }};
        let envelope = serde_json::json!({{
            "v": 1,
            "op": "call",
            "id": id,
            "key": key,
            "transport": "http",
            "body": body_value,
        }});
        let serialized = serde_json::to_string(&envelope)
            .map_err(|error| JsValue::from_str(&error.to_string()))?;
        let options = RequestInit::new();
        options.set_method("POST");
        options.set_mode(RequestMode::Cors);
        options.set_body(&JsValue::from_str(&serialized));
        let url = format!("{{}}{{}}", self.base_url.trim_end_matches('/'), RPC_HTTP_PATH);
        let request = Request::new_with_str_and_init(&url, &options)?;
        request.headers().set("content-type", "application/json")?;
        let window = web_sys::window().ok_or_else(|| JsValue::from_str("window is unavailable"))?;
        let response = JsFuture::from(window.fetch_with_request(&request)).await?;
        let response: Response = response.dyn_into()?;
        let json = JsFuture::from(response.json()?).await?;
        let receipt: Value = serde_wasm_bindgen::from_value(json)
            .map_err(|error| JsValue::from_str(&error.to_string()))?;
        if receipt.get("id").and_then(Value::as_str) != envelope.get("id").and_then(Value::as_str)
            || receipt.get("key").and_then(Value::as_str) != envelope.get("key").and_then(Value::as_str)
        {{
            return Err(JsValue::from_str("RPC receipt correlation mismatch"));
        }}
        if receipt.get("ok").and_then(Value::as_bool) != Some(true) {{
            return serde_wasm_bindgen::to_value(&receipt)
                .map(Err)
                .unwrap_or_else(|error| Err(JsValue::from_str(&error.to_string())));
        }}
        serde_wasm_bindgen::to_value(receipt.get("body").unwrap_or(&Value::Null))
            .map_err(|error| JsValue::from_str(&error.to_string()))
    }}
}}
"#,
        generator = GENERATOR,
        digest = digest,
        audience = audience,
        service = map.service,
        rpc_path = RPC_HTTP_PATH,
        allowed = allowed,
    )
}

fn operation_metadata(map: &RouteMap) -> BTreeMap<&str, Value> {
    map.map
        .iter()
        .map(|(key, entry)| {
            (
                key.as_str(),
                serde_json::json!({
                    "rpcKey": entry.rpc_key,
                    "path": entry.path,
                    "methods": entry.methods,
                    "transports": entry.transports,
                }),
            )
        })
        .collect()
}

fn sanitize_package(service: &str) -> String {
    let mut out = service
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '-' {
                character.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>();
    while out.contains("--") {
        out = out.replace("--", "-");
    }
    out.trim_matches('-').to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_map() -> RouteMap {
        RouteMap::from_json_str(
            r#"{
              "schema_version":"1.0.0",
              "service":"demo-api",
              "map":{
                "ping":{
                  "path":"/v1/ping",
                  "methods":["GET"],
                  "authorization":{"mode":"public"},
                  "transports":["http"]
                }
              }
            }"#,
        )
        .unwrap_or_else(|error| panic!("sample route map failed: {error}"))
    }

    #[test]
    fn emits_one_digest_bound_four_language_bundle() {
        let bundle = rpc_client_bundle(&sample_map(), "crate::dto", "public")
            .unwrap_or_else(|error| panic!("bundle generation failed: {error}"));
        assert_eq!(bundle.manifest.operations, vec!["ping"]);
        assert_eq!(bundle.manifest.http_endpoint, "/v1/rpc");
        assert!(bundle.rust.contains("RPC_CONTRACT_SHA256"));
        assert!(bundle.rust.contains("RPC_HTTP_PATH"));
        assert!(bundle.typescript.contains("new URL(RPC_HTTP_PATH"));
        assert!(bundle.dart.contains("baseUri.resolve(rpcHttpPath)"));
        assert!(bundle.wasm_rust.contains("RPC_HTTP_PATH"));
    }

    #[test]
    fn typescript_projection_avoids_parameter_properties() {
        let bundle = rpc_client_bundle(&sample_map(), "crate::dto", "public")
            .unwrap_or_else(|error| panic!("bundle generation failed: {error}"));
        assert!(bundle
            .typescript
            .contains("private readonly baseUrl: string;"));
        assert!(bundle
            .typescript
            .contains("public readonly receipt: RpcReceipt;"));
        assert!(!bundle.typescript.contains("constructor(public readonly"));
        assert!(!bundle
            .typescript
            .contains("private readonly baseUrl: string,"));
        assert!(!bundle
            .typescript
            .contains("private readonly fetchImpl: typeof fetch ="));
    }
}
