//! Canonical five-language RPC client projection.
//!
//! v2 consumes both the audience-filtered route map and the handlers-authoritative
//! normalized operation IR. The route map retains transport/projection metadata;
//! the normalized IR supplies operation identity and semantic request/response
//! schemas. Public SDK methods are generated from `source.operation` and always
//! target canonical POST `/v1/rpc`.

use serde::Serialize;

use crate::{
    contract_sha256, rpc_client_bundle, typed_rpc_sdk_codegen::typed_sdk_sources, RouteMap,
    RpcOperationContract,
};

const GENERATOR: &str = "ores-api-docs rpc_client_bundle_v2";
const RPC_HTTP_PATH: &str = "/v1/rpc";

#[derive(Clone, Debug, Serialize)]
pub struct RpcClientBundleV2Manifest {
    pub schema_version: u32,
    pub generated_by: &'static str,
    pub service: String,
    pub audience: String,
    pub contract_sha256: String,
    pub operations: Vec<String>,
    pub languages: [&'static str; 5],
    pub http_endpoint: &'static str,
}

#[derive(Clone, Debug)]
pub struct RpcClientBundleV2 {
    pub manifest: RpcClientBundleV2Manifest,
    pub rust: String,
    pub go: String,
    pub dart: String,
    pub typescript: String,
    pub gleam: String,
}

/// Generate the canonical five-language v1-over-HTTP client bundle.
///
/// `map` must already be filtered for the target audience. `operations` must be
/// the matching handlers-authoritative normalized IR. A real semantic section
/// without a concrete supported schema is rejected rather than emitted as an
/// `any`/`unknown`/`serde_json::Value` public SDK type.
pub fn rpc_client_bundle_v2(
    map: &RouteMap,
    operations: &[RpcOperationContract],
    dto_module: &str,
    audience: &str,
) -> Result<RpcClientBundleV2, String> {
    if audience.trim().is_empty() {
        return Err("client audience must not be empty".to_owned());
    }
    let compatibility = rpc_client_bundle(map, dto_module, audience)?;
    let digest = contract_sha256(map);
    let typed = typed_sdk_sources(map, operations, audience, &digest)?;
    let operation_keys = operations
        .iter()
        .map(|operation| operation.operation_key.clone())
        .collect::<Vec<_>>();
    let manifest = RpcClientBundleV2Manifest {
        schema_version: 2,
        generated_by: GENERATOR,
        service: map.service.clone(),
        audience: audience.to_owned(),
        contract_sha256: digest.clone(),
        operations: operation_keys,
        languages: ["rust", "go", "dart", "typescript", "gleam"],
        http_endpoint: RPC_HTTP_PATH,
    };
    Ok(RpcClientBundleV2 {
        manifest,
        rust: compatibility.rust + &typed.rust,
        go: go_client(map, audience, &digest) + &typed.go,
        dart: compatibility.dart + &typed.dart,
        typescript: compatibility.typescript + &typed.typescript,
        gleam: gleam_client(map, audience, &digest) + &typed.gleam,
    })
}

fn go_client(map: &RouteMap, audience: &str, digest: &str) -> String {
    let allowed = map
        .map
        .values()
        .filter_map(|entry| entry.rpc_key.as_deref())
        .map(|key| format!("\t{key:?}: {{}},"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"// Code generated by {generator}; DO NOT EDIT.
package rpc

import (
    "bytes"
    "context"
    "encoding/json"
    "fmt"
    "io"
    "net/http"
    "net/url"
    "strings"
    "sync/atomic"
)

const ContractSHA256 = {digest:?}
const ClientAudience = {audience:?}
const Service = {service:?}
const HTTPPath = {rpc_path:?}

var operations = map[string]struct{{}}{{
{allowed}
}}

type CallArgs struct {{
    Path map[string]any `json:"path,omitempty"`
    Query map[string]any `json:"query,omitempty"`
    Headers map[string]any `json:"headers,omitempty"`
    Body any `json:"body,omitempty"`
    TraceID string `json:"traceId,omitempty"`
    SpanID string `json:"spanId,omitempty"`
}}

type Receipt struct {{
    V int `json:"v"`
    Op string `json:"op"`
    ID string `json:"id"`
    Key string `json:"key"`
    Transport string `json:"transport,omitempty"`
    OK bool `json:"ok"`
    Status int `json:"status,omitempty"`
    Body json.RawMessage `json:"body,omitempty"`
    Error json.RawMessage `json:"error,omitempty"`
    TraceID string `json:"traceId,omitempty"`
    SpanID string `json:"spanId,omitempty"`
}}

type Client struct {{
    BaseURL *url.URL
    HTTP *http.Client
    sequence atomic.Uint64
}}

func NewClient(baseURL string, client *http.Client) (*Client, error) {{
    parsed, err := url.Parse(baseURL)
    if err != nil {{ return nil, err }}
    if client == nil {{ client = http.DefaultClient }}
    return &Client{{BaseURL: parsed, HTTP: client}}, nil
}}

func (c *Client) Call(ctx context.Context, key string, args CallArgs, out any) error {{
    if _, ok := operations[key]; !ok {{
        return fmt.Errorf("RPC operation not generated for this audience: %s", key)
    }}
    id := fmt.Sprintf("go-%d", c.sequence.Add(1))
    envelope := map[string]any{{
        "v": 1, "op": "call", "id": id, "key": key, "transport": "http",
    }}
    if args.Path != nil {{ envelope["path"] = args.Path }}
    if args.Query != nil {{ envelope["query"] = args.Query }}
    if args.Headers != nil {{ envelope["headers"] = args.Headers }}
    if args.Body != nil {{ envelope["body"] = args.Body }}
    if args.TraceID != "" {{ envelope["traceId"] = args.TraceID }}
    if args.SpanID != "" {{ envelope["spanId"] = args.SpanID }}
    encoded, err := json.Marshal(envelope)
    if err != nil {{ return err }}
    endpoint := *c.BaseURL
    endpoint.Path = strings.TrimRight(endpoint.Path, "/") + HTTPPath
    request, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint.String(), bytes.NewReader(encoded))
    if err != nil {{ return err }}
    request.Header.Set("content-type", "application/json")
    response, err := c.HTTP.Do(request)
    if err != nil {{ return err }}
    defer response.Body.Close()
    raw, err := io.ReadAll(response.Body)
    if err != nil {{ return err }}
    var receipt Receipt
    if err := json.Unmarshal(raw, &receipt); err != nil {{ return err }}
    if receipt.ID != id || receipt.Key != key {{ return fmt.Errorf("RPC receipt correlation mismatch") }}
    if !receipt.OK {{ return fmt.Errorf("RPC %s failed with status %d: %s", key, receipt.Status, string(receipt.Error)) }}
    if out != nil && len(receipt.Body) != 0 {{ return json.Unmarshal(receipt.Body, out) }}
    return nil
}}
"#,
        generator = GENERATOR,
        digest = digest,
        audience = audience,
        service = map.service,
        rpc_path = RPC_HTTP_PATH,
        allowed = allowed,
    )
}

fn gleam_client(map: &RouteMap, audience: &str, digest: &str) -> String {
    let allowed = map
        .map
        .values()
        .filter_map(|entry| entry.rpc_key.as_deref())
        .map(|key| format!("    {key:?} -> True"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"// @generated by {generator}; do not edit.
import gleam/dict
import gleam/dynamic
import gleam/dynamic/decode
import gleam/http
import gleam/http/request
import gleam/json
import gleam/list
import gleam/option
import gleam/string

pub const rpc_contract_sha256 = {digest:?}
pub const rpc_client_audience = {audience:?}
pub const rpc_service = {service:?}
pub const rpc_http_path = {rpc_path:?}

pub type CallArgs {{
  CallArgs(
    path: option.Option(json.Json),
    query: option.Option(json.Json),
    headers: option.Option(json.Json),
    body: option.Option(json.Json),
    trace_id: option.Option(String),
    span_id: option.Option(String),
  )
}}

pub type Receipt {{
  Receipt(
    id: String,
    key: String,
    ok: Bool,
    status: option.Option(Int),
    body: option.Option(dynamic.Dynamic),
  )
}}

pub fn receipt_decoder() -> decode.Decoder(Receipt) {{
  use id <- decode.field("id", decode.string)
  use key <- decode.field("key", decode.string)
  use ok <- decode.field("ok", decode.bool)
  use status <- decode.optional_field("status", option.None, decode.optional(decode.int))
  use body <- decode.optional_field("body", option.None, decode.optional(decode.dynamic))
  decode.success(Receipt(id, key, ok, status, body))
}}

pub fn operation_allowed(key: String) -> Bool {{
  case key {{
{allowed}
    _ -> False
  }}
}}

pub type Transport {{
  Transport(fn(String, String) -> Result(String, String))
}}

pub fn call(
  transport: Transport,
  base_url: String,
  id: String,
  key: String,
  args: CallArgs,
) -> Result(dynamic.Dynamic, String) {{
  case operation_allowed(key) {{
    False -> Error("RPC operation not generated for this audience")
    True -> {{
      let CallArgs(path, query, headers, body, trace_id, span_id) = args
      let members = [
        #("v", json.int(1)),
        #("op", json.string("call")),
        #("id", json.string(id)),
        #("key", json.string(key)),
        #("transport", json.string("http")),
      ]
      let members = case path {{ option.None -> members; option.Some(value) -> [#("path", value), ..members] }}
      let members = case query {{ option.None -> members; option.Some(value) -> [#("query", value), ..members] }}
      let members = case headers {{ option.None -> members; option.Some(value) -> [#("headers", value), ..members] }}
      let members = case body {{ option.None -> members; option.Some(value) -> [#("body", value), ..members] }}
      let members = case trace_id {{ option.None -> members; option.Some(value) -> [#("traceId", json.string(value)), ..members] }}
      let members = case span_id {{ option.None -> members; option.Some(value) -> [#("spanId", json.string(value)), ..members] }}
      let Transport(send) = transport
      use response <- result.try(send(base_url <> rpc_http_path, json.to_string(json.object(members))))
      use receipt <- result.try(json.parse(response, receipt_decoder()) |> result.map_error(string.inspect))
      case receipt {{
        Receipt(receipt_id, receipt_key, True, _, option.Some(body)) if receipt_id == id && receipt_key == key -> Ok(body)
        Receipt(receipt_id, receipt_key, _, _, _) if receipt_id != id || receipt_key != key -> Error("RPC receipt correlation mismatch")
        Receipt(_, _, False, status, _) -> Error("RPC failed with status " <> string.inspect(status))
        _ -> Error("RPC success receipt omitted body")
      }}
    }}
  }}
}}
"#,
        generator = GENERATOR,
        digest = digest,
        audience = audience,
        service = map.service,
        rpc_path = RPC_HTTP_PATH,
        allowed = allowed,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        RpcClientAudience, RpcCodecSet, RpcHttpProjection, RpcOperationScope, RpcOperationSource,
        RpcPayloadCodec, RpcRequestShape, RpcResponseShape,
    };
    use serde_json::json;

    fn sample_map() -> RouteMap {
        RouteMap::from_json_str(
            r#"{
              "schema_version":"1.0.0",
              "service":"demo-api",
              "map":{
                "demo.health.get_version":{
                  "path":"/v1/version",
                  "methods":["GET"],
                  "rpc_key":"demo.health.get_version",
                  "transports":["http"]
                }
              }
            }"#,
        )
        .unwrap_or_else(|error| panic!("sample route map failed: {error}"))
    }

    fn sample_operation() -> RpcOperationContract {
        RpcOperationContract {
            schema_version: 2,
            operation_key: "demo.health.get_version".to_owned(),
            namespace: vec!["demo".to_owned(), "health".to_owned()],
            source: RpcOperationSource {
                route_file: "src/routes/version/route.rs".to_owned(),
                handler: "get".to_owned(),
                operation: Some("get_version".to_owned()),
                invoker: Some("__ores_invoke_get_version".to_owned()),
                execution_model: "shared_operation".to_owned(),
                repository: None,
                commit_sha: None,
            },
            http: RpcHttpProjection {
                method: "GET".to_owned(),
                path: "/v1/version".to_owned(),
                rpc_transport_path: "/v1/rpc",
            },
            scope: RpcOperationScope::Regular,
            audiences: vec![RpcClientAudience::Browser, RpcClientAudience::Server],
            codecs: RpcCodecSet {
                allowed: vec![RpcPayloadCodec::Json],
                default: RpcPayloadCodec::Json,
            },
            request: RpcRequestShape::default(),
            response: RpcResponseShape {
                header_schema: None,
                trailer_schema: None,
                body_schema: Some(json!({
                    "type":"object",
                    "additionalProperties":false,
                    "properties":{
                        "result":{
                            "type":"object",
                            "additionalProperties":false,
                            "properties":{"service":{"type":"string"},"version":{"type":"string"}},
                            "required":["service","version"]
                        },
                        "traceIds":{"type":"array","items":{"type":"string"}}
                    },
                    "required":["result","traceIds"]
                })),
                error_schema: Some(json!({
                    "type":"object",
                    "additionalProperties":false,
                    "properties":{"code":{"type":"string"},"message":{"type":"string"}},
                    "required":["code","message"]
                })),
            },
            contract_sha256: "0".repeat(64),
        }
    }

    #[test]
    fn emits_named_typed_five_language_bundle() {
        let operation = sample_operation();
        let bundle = rpc_client_bundle_v2(&sample_map(), &[operation], "crate::dto", "public")
            .unwrap_or_else(|error| panic!("bundle generation failed: {error}"));
        assert_eq!(bundle.manifest.http_endpoint, "/v1/rpc");
        assert_eq!(bundle.manifest.operations, vec!["demo.health.get_version"]);
        assert!(bundle.rust.contains("pub async fn get_version"));
        assert!(bundle.rust.contains("GetVersionResponseResult"));
        assert!(bundle.rust.contains("TYPED_RPC_HTTP_PATH"));
        assert!(bundle.go.contains("func (c *Client) GetVersion"));
        assert!(bundle
            .dart
            .contains("Future<GetVersionResponse> getVersion"));
        assert!(bundle.typescript.contains("async getVersion"));
        assert!(bundle.typescript.contains("Promise<GetVersionResponse>"));
        assert!(bundle.gleam.contains("pub fn get_version"));
        assert!(!bundle
            .typescript
            .contains("async getVersion(input: GetVersionInput): Promise<unknown>"));
    }

    #[test]
    fn rejects_untyped_open_object_in_semantic_schema() {
        let mut operation = sample_operation();
        operation.response.body_schema = Some(json!({"type":"object"}));
        let error = rpc_client_bundle_v2(&sample_map(), &[operation], "crate::dto", "public")
            .expect_err("open object must fail closed");
        assert!(error.contains("open/untyped object schemas are forbidden"));
    }
}
