use crate::{FsRoute, FsRouteKind, RouteMap};
use std::path::{Path, PathBuf};

const PAGE_GENERATOR_LEAF: &str = "generate.rs";

/// Generate Rust source that imports every discovered `page.rs` and assigns its
/// required exports to exact `ores-api-docs-client` function types.
///
/// Rendering stays in `page.rs`. Static path enumeration is deliberately split
/// into the optional sibling `generate.rs`; dynamic StaticOnly pages are checked
/// separately by the manifest/policy validator to require that sibling.
///
/// Consumers write this text to `OUT_DIR/ores_pages_compile.rs` from build.rs
/// and `include!` it in the crate. Missing exports or signature drift therefore
/// fail normal Rust compilation.
pub fn page_compile_glue(repo_root: &Path, routes: &[FsRoute]) -> Result<String, String> {
    let mut out = String::from("// @generated by ores-route-fs; do not edit\n");
    for route in routes {
        if route.kind != FsRouteKind::Page {
            return Err(format!("{} is not a page route", route.source));
        }

        let module = module_ident("page", &route.source);
        let source = absolute_source(repo_root, &route.source)?;
        let literal = format!("{:?}", source.to_string_lossy());
        out.push_str(&format!(
            "#[path = {literal}]\nmod {module};\n\
             const _: ::ores_api_docs_client::PageFn = {module}::page;\n\
             const _: ::ores_api_docs_client::PageConfigFn = {module}::config;\n\
             const _: ::ores_api_docs_client::PageAssetsFn = {module}::assets;\n"
        ));

        if let Some(generator) = sibling_generator(repo_root, &route.source)? {
            let generator_module = module_ident("generate", generator.strip_prefix(repo_root).unwrap_or(&generator).to_string_lossy().as_ref());
            let generator_literal = format!("{:?}", generator.to_string_lossy());
            out.push_str(&format!(
                "#[path = {generator_literal}]\nmod {generator_module};\n\
                 const _: ::ores_api_docs_client::GenerateStaticParamsFn = {generator_module}::generate_static_params;\n"
            ));
        }
    }
    Ok(out)
}

/// Generate Rust source that imports every optional API `route.rs`, checks its
/// module-level `route()` signature, and tests its declared operation keys
/// against the authoritative api-docs route map for the filesystem-derived path.
pub fn api_compile_glue(
    repo_root: &Path,
    routes: &[FsRoute],
    route_map: &RouteMap,
) -> Result<String, String> {
    let mut out = String::from("// @generated by ores-route-fs; do not edit\n");
    for route in routes {
        if route.kind != FsRouteKind::ApiHandler {
            return Err(format!("{} is not an API route", route.source));
        }
        let canonical = route.canonical_path();
        let expected = route_map
            .map
            .iter()
            .filter(|(_, entry)| entry.path == canonical)
            .map(|(key, _)| key.as_str())
            .collect::<Vec<_>>();
        if expected.is_empty() {
            return Err(format!(
                "{} derives {canonical} but no api-docs operation owns that path",
                route.source
            ));
        }
        let module = module_ident("route", &route.source);
        let test = format!("__ores_contract_{module}");
        let source = absolute_source(repo_root, &route.source)?;
        let literal = format!("{:?}", source.to_string_lossy());
        let expected_literal = expected
            .iter()
            .map(|value| format!("{:?}", value))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "#[path = {literal}]\nmod {module};\n\
             const _: ::ores_api_docs::RouteDefinitionFn = {module}::route;\n\
             #[cfg(test)]\n#[test]\nfn {test}() {{\n\
                 let mut actual = {module}::route().operations.to_vec();\n\
                 actual.sort_unstable();\n\
                 let mut expected = vec![{expected_literal}];\n\
                 expected.sort_unstable();\n\
                 assert_eq!(actual, expected, \"route.rs operations must equal api-docs operations for {canonical}\");\n\
             }}\n"
        ));
    }
    Ok(out)
}

fn sibling_generator(repo_root: &Path, page_source: &str) -> Result<Option<PathBuf>, String> {
    let root = repo_root
        .canonicalize()
        .map_err(|error| format!("canonicalize {}: {error}", repo_root.display()))?;
    let page = root.join(page_source);
    let parent = page
        .parent()
        .ok_or_else(|| format!("page source has no parent directory: {page_source}"))?;
    let generator = parent.join(PAGE_GENERATOR_LEAF);
    Ok(generator.is_file().then_some(generator))
}

fn absolute_source(repo_root: &Path, source: &str) -> Result<PathBuf, String> {
    let root = repo_root
        .canonicalize()
        .map_err(|error| format!("canonicalize {}: {error}", repo_root.display()))?;
    let path = root.join(source);
    if !path.is_file() {
        return Err(format!("route source does not exist: {}", path.display()));
    }
    Ok(path)
}

fn module_ident(prefix: &str, source: &str) -> String {
    let mut out = format!("__ores_{prefix}_");
    for ch in source.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identifiers_are_stable_and_rust_safe() {
        assert_eq!(
            module_ident("page", "src/pages/users/[id]/page.rs"),
            "__ores_page_src_pages_users__id__page_rs"
        );
        assert_eq!(
            module_ident("generate", "src/pages/users/[id]/generate.rs"),
            "__ores_generate_src_pages_users__id__generate_rs"
        );
    }
}
