use crate::{
    analyze_generator_source, analyze_http_route_source, analyze_page_source, FsRoute, FsRouteKind,
    FsRouteSegment, RouteMap,
};
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

const PAGE_GENERATOR_LEAF: &str = "gen.rs";
const RPC_V1_CANONICAL_PATH: &str = "/v1/rpc";
const RPC_V1_LEGACY_PATH: &str = "/rpc/v1";

/// Generate Rust source that imports every discovered `page.rs` and assigns its
/// generated wrapper to the exact `ores-api-docs-client` async function type.
///
/// Before code generation we parse the Rust source without executing it. The
/// analyzer validates the reserved `#[ores_page(...)] pub async fn page`
/// contract and forbids `generate_static_params` from living in `page.rs`. The
/// proc macro emits a typed `__ORES_PAGE_CONFIG` constant and a boxed async
/// wrapper; generated glue verifies both with rustc. Optional sibling `gen.rs`
/// is analyzed independently and type-checked the same way.
pub fn page_compile_glue(repo_root: &Path, routes: &[FsRoute]) -> Result<String, String> {
    let mut out = String::from("// @generated by ores-route-fs; do not edit\n");
    for route in routes {
        if route.kind != FsRouteKind::Page {
            return Err(format!("{} is not a page route", route.source));
        }

        let source = absolute_source(repo_root, &route.source)?;
        let page_source = fs::read_to_string(&source)
            .map_err(|error| format!("read {}: {error}", source.display()))?;
        let analysis =
            analyze_page_source(&route.source, &page_source).map_err(|error| error.to_string())?;
        let has_assets = analysis
            .public_functions
            .iter()
            .any(|name| name == "assets");
        let metadata = analysis
            .page
            .ok_or_else(|| format!("{} did not yield page metadata", route.source))?;

        let generator = sibling_generator(repo_root, &route.source)?;
        let dynamic = route
            .segments
            .iter()
            .any(|segment| !matches!(segment, FsRouteSegment::Static(_)));
        if dynamic && metadata.render == "static_only" && generator.is_none() {
            return Err(format!(
                "{} is a dynamic static_only route and therefore requires sibling gen.rs",
                route.source
            ));
        }

        let module = module_ident("page", &route.source);
        let literal = format!("{:?}", source.to_string_lossy());
        out.push_str(&format!(
            "#[path = {literal}]\nmod {module};\n\
             const _: ::ores_api_docs_client::PageFn = {module}::__ores_page_boxed;\n\
             const _: ::ores_api_docs_client::PageConfig = {module}::__ORES_PAGE_CONFIG;\n"
        ));
        // The page module stays private. A generated sibling `lambda.rs` is a
        // separate bin crate and gets exactly this one entrypoint.
        let entry = crate::page_lambda_entry_ident(&route.source);
        out.push_str(&format!(
            "#[doc(hidden)]\n#[allow(dead_code)]\n\
             pub fn {entry}(ctx: ::ores_api_docs_client::PageContext) -> ::ores_api_docs_client::PageFuture {{\n    \
             {module}::__ores_page_boxed(ctx)\n}}\n"
        ));
        if has_assets {
            out.push_str(&format!(
                "const _: ::ores_api_docs_client::PageAssetsFn = {module}::assets;\n"
            ));
        }

        if let Some(generator) = generator {
            let relative = generator
                .strip_prefix(repo_root)
                .unwrap_or(&generator)
                .to_string_lossy()
                .replace('\\', "/");
            let generator_source = fs::read_to_string(&generator)
                .map_err(|error| format!("read {}: {error}", generator.display()))?;
            analyze_generator_source(&relative, &generator_source)
                .map_err(|error| error.to_string())?;
            let generator_module = module_ident("gen", &relative);
            let generator_literal = format!("{:?}", generator.to_string_lossy());
            out.push_str(&format!(
                "#[path = {generator_literal}]\nmod {generator_module};\n\
                 const _: ::ores_api_docs_client::GenerateStaticParamsFn = {generator_module}::__ores_generate_static_params_boxed;\n"
            ));
        }
    }
    Ok(out)
}

/// Generate metadata-only compile glue for legacy API route modules.
///
/// This compatibility surface keeps the older `route() -> ApiRouteDefinition`
/// contract available while the fleet migrates to handwritten HTTP verb exports.
pub fn api_compile_glue(
    repo_root: &Path,
    routes: &[FsRoute],
    route_map: &RouteMap,
) -> Result<String, String> {
    let mut out = String::from("// @generated by ores-route-fs; do not edit\n");
    for route in routes {
        if route.kind != FsRouteKind::ApiHandler {
            return Err(format!("{} is not an API route", route.source));
        }
        let canonical = route.canonical_path();
        reject_reserved_rpc_path(&route.source, &canonical)?;
        let expected = expected_operations(route_map, &canonical);
        if expected.is_empty() {
            return Err(format!(
                "{} derives {canonical} but no api-docs operation owns that path",
                route.source
            ));
        }
        let module = module_ident("route", &route.source);
        let test = format!("__ores_contract_{module}");
        let source = absolute_source(repo_root, &route.source)?;
        let literal = format!("{:?}", source.to_string_lossy());
        let expected_literal = expected
            .iter()
            .map(|value| format!("{:?}", value))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "#[path = {literal}]\nmod {module};\n\
             const _: ::ores_api_docs::RouteDefinitionFn = {module}::route;\n\
             #[cfg(test)]\n#[test]\nfn {test}() {{\n\
                 let mut actual = {module}::route().operation_keys();\n\
                 actual.sort_unstable();\n\
                 let mut expected = vec![{expected_literal}];\n\
                 expected.sort_unstable();\n\
                 assert_eq!(actual, expected, \"route.rs operations must equal api-docs operations for {canonical}\");\n\
             }}\n"
        ));
    }
    Ok(out)
}

/// Generate the executable API-server surface from handwritten Next-style
/// `route.rs` files and verify every exported HTTP verb against the authoritative
/// REST route map.
///
/// The invariant is **one route.rs == one canonical REST path**, not one RPC
/// operation. A file may export any supported combination of `get`, `post`,
/// `put`, `patch`, `delete`, `head`, and `options`. Each verb maps to its own
/// api-docs operation key.
///
/// RPC is generated only from these API REST handlers. `page.rs` is a separate
/// web-rendering contract and is never used as an RPC authority. RPC dispatch
/// resolves the operation key first, then enters an Axum router containing only
/// that selected operation so normal `Path`, `Query`, `Json`, `State`, and route
/// middleware semantics are preserved without exposing the general API router.
///
/// The three-argument combined-router macro accepts one Axum router layer and
/// applies the same layer to the ordinary REST router and every operation-local
/// RPC adapter. Auth, per-route rate limiting, telemetry, and other middleware
/// therefore see the same logical REST path/method on both entry paths. A
/// two-argument compatibility form remains available without a shared layer.
pub fn api_server_glue(
    repo_root: &Path,
    routes: &[FsRoute],
    route_map: &RouteMap,
) -> Result<String, String> {
    let mut out = String::from("// @generated by ores-route-fs; do not edit\n");
    let mut mounts = Vec::new();
    let mut operation_rows = Vec::new();
    let mut rpc_binding_rows = Vec::new();
    let mut direct_rows = Vec::new();
    let mut layered_rows = Vec::new();

    for route in routes {
        if route.kind != FsRouteKind::ApiHandler {
            return Err(format!("{} is not an API route", route.source));
        }

        let canonical = route.canonical_path();
        reject_reserved_rpc_path(&route.source, &canonical)?;
        let source = absolute_source(repo_root, &route.source)?;
        let route_source = fs::read_to_string(&source)
            .map_err(|error| format!("read {}: {error}", source.display()))?;
        let analysis = analyze_http_route_source(&route.source, &route_source)
            .map_err(|error| error.to_string())?;
        let source_methods = analysis.methods();
        let operations = expected_http_operations_by_method(route_map, &canonical)?;
        let contract_methods = operations
            .keys()
            .map(String::as_str)
            .collect::<BTreeSet<_>>();

        if source_methods != contract_methods {
            return Err(format!(
                "{} derives {canonical}: public route.rs verbs {:?} != api-docs HTTP methods {:?}",
                route.source, source_methods, contract_methods
            ));
        }

        let module = module_ident("route", &route.source);
        let literal = format!("{:?}", source.to_string_lossy());
        out.push_str(&format!("#[path = {literal}]\nmod {module};\n"));

        let method_router = method_router_expression(&module, &analysis.handlers)?;
        for axum_path in route.axum_paths() {
            mounts.push(format!(
                "        .route({:?}, {method_router})\n",
                axum_path
            ));
        }

        for (method, operation) in operations {
            let handler = analysis
                .handlers
                .iter()
                .find(|handler| handler.method == method)
                .ok_or_else(|| {
                    format!(
                        "{}: generated operation {operation:?} has no {method} handler",
                        route.source
                    )
                })?;
            operation_rows.push(format!(
                "    ({:?}, {:?}, {:?}, {:?}),\n",
                operation, method, canonical, route.source
            ));
            rpc_binding_rows.push(format!(
                "    ::ores_api_docs::RpcV1RouteBinding::new({:?}, {:?}, {:?}, {:?}),\n",
                operation, method, canonical, route.source
            ));

            let service_var = module_ident("operation_service", operation);
            let axum_paths = route.axum_paths();
            let mut direct =
                format!("                let mut {service_var} = ::axum::Router::new();\n");
            for axum_path in &axum_paths {
                direct.push_str(&format!(
                    "                {service_var} = {service_var}.route({axum_path:?}, ::axum::routing::{routing}({module}::{handler_name}));\n",
                    routing = handler.rust_name,
                    handler_name = handler.rust_name,
                ));
            }
            direct.push_str(&format!(
                "                let {service_var} = {service_var}.with_state(__ores_state.clone());\n\
                 __ores_rpc_handlers.insert({operation:?},\n\
                     ::ores_api_docs::rpc_axum::operation_router::axum_rpc_operation_handler(\n\
                         {service_var}));\n"
            ));
            direct_rows.push(direct);

            let mut layered =
                format!("                let mut {service_var} = ::axum::Router::new();\n");
            for axum_path in &axum_paths {
                layered.push_str(&format!(
                    "                {service_var} = {service_var}.route({axum_path:?}, ::axum::routing::{routing}({module}::{handler_name}));\n",
                    routing = handler.rust_name,
                    handler_name = handler.rust_name,
                ));
            }
            layered.push_str(&format!(
                "                let {service_var} = {service_var}\n\
                     .with_state(__ores_state.clone())\n\
                     .layer(__ores_layer.clone());\n\
                 __ores_rpc_handlers.insert({operation:?},\n\
                     ::ores_api_docs::rpc_axum::operation_router::axum_rpc_operation_handler(\n\
                         {service_var}));\n"
            ));
            layered_rows.push(layered);
        }
    }

    out.push_str(
        "\n/// Build the filesystem REST surface only. This compatibility macro does not\n\
         /// mount RPC. Type inference happens at the call site so normal Axum\n\
         /// State<T> extractors remain supported without naming product state here.\n\
         #[allow(unused_macros)]\n\
         macro_rules! __ores_filesystem_api_router {\n\
             () => {{\n\
                 ::axum::Router::new()\n",
    );
    for mount in mounts {
        out.push_str(&mount);
    }
    out.push_str("            }};\n        }\n\n");
    out.push_str("pub(crate) use __ores_filesystem_api_router;\n\n");

    out.push_str(
        "/// (operation key, HTTP method, canonical REST path, source route.rs).\n\
         /// Build tooling uses this deterministic inventory for route/function slicing.\n\
         pub static __ORES_HTTP_ROUTE_OPERATIONS: &[(&str, &str, &str, &str)] = &[\n",
    );
    for row in operation_rows {
        out.push_str(&row);
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// Generated operation-key metadata. Operation selection happens before\n\
         /// the isolated Axum adapter is invoked; this is not an internal HTTP\n\
         /// route lookup table for the general API router.\n\
         pub static __ORES_RPC_ROUTE_BINDINGS: &[::ores_api_docs::RpcV1RouteBinding] = &[\n",
    );
    for row in rpc_binding_rows {
        out.push_str(&row);
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// Build ordinary REST routes and canonical `/v1/rpc` from the same\n\
         /// authored `route.rs` functions. RPC cannot fall through to another\n\
         /// route or the RPC endpoint itself.\n\
         #[allow(unused_macros)]\n\
         macro_rules! __ores_filesystem_api_http_and_rpc_router {\n\
             ($state:expr, $route_map:expr) => {{\n\
                 let __ores_state = $state;\n\
                 let __ores_http = __ores_filesystem_api_router!()\n\
                     .with_state(__ores_state.clone());\n\
                 let mut __ores_rpc_handlers = ::std::collections::BTreeMap::new();\n",
    );
    for row in direct_rows {
        out.push_str(&row);
    }
    out.push_str(
        "                ::ores_api_docs::rpc_axum::operation_router::filesystem_operation_rpc_v1_router(\n\
                     $route_map, __ORES_RPC_ROUTE_BINDINGS, __ores_rpc_handlers\n\
                 ).map(|__ores_rpc| __ores_http.merge(__ores_rpc))\n\
             }};\n\
             ($state:expr, $route_map:expr, $layer:expr) => {{\n\
                 let __ores_state = $state;\n\
                 let __ores_layer = $layer;\n\
                 let __ores_http = __ores_filesystem_api_router!()\n\
                     .with_state(__ores_state.clone())\n\
                     .layer(__ores_layer.clone());\n\
                 let mut __ores_rpc_handlers = ::std::collections::BTreeMap::new();\n",
    );
    for row in layered_rows {
        out.push_str(&row);
    }
    out.push_str(
        "                ::ores_api_docs::rpc_axum::operation_router::filesystem_operation_rpc_v1_router(\n\
                     $route_map, __ORES_RPC_ROUTE_BINDINGS, __ores_rpc_handlers\n\
                 ).map(|__ores_rpc| __ores_http.merge(__ores_rpc))\n\
             }};\n\
         }\n\n\
         pub(crate) use __ores_filesystem_api_http_and_rpc_router;\n",
    );
    Ok(out)
}

fn method_router_expression(
    module: &str,
    handlers: &[crate::HttpRouteHandlerSource],
) -> Result<String, String> {
    let mut handlers = handlers.to_vec();
    handlers.sort_by_key(|handler| method_order(&handler.method));
    let Some(first) = handlers.first() else {
        return Err("route module has no handlers".to_owned());
    };
    let mut expression = format!(
        "::axum::routing::{}({module}::{})",
        first.rust_name, first.rust_name
    );
    for handler in handlers.iter().skip(1) {
        expression.push_str(&format!(
            ".{}({module}::{})",
            handler.rust_name, handler.rust_name
        ));
    }
    Ok(expression)
}

fn method_order(method: &str) -> usize {
    match method {
        "GET" => 0,
        "POST" => 1,
        "PUT" => 2,
        "PATCH" => 3,
        "DELETE" => 4,
        "HEAD" => 5,
        "OPTIONS" => 6,
        _ => usize::MAX,
    }
}

fn expected_http_operations_by_method<'a>(
    route_map: &'a RouteMap,
    canonical: &str,
) -> Result<BTreeMap<String, &'a str>, String> {
    let mut operations = BTreeMap::new();
    for (key, entry) in &route_map.map {
        if entry.path != canonical || !entry.transports.iter().any(|value| value == "http") {
            continue;
        }
        if entry.methods.len() != 1 {
            return Err(format!(
                "api-docs operation {key:?} at {canonical} declares methods {:?}; filesystem RPC generation requires one operation key per HTTP verb",
                entry.methods
            ));
        }
        let method = entry.methods[0].to_ascii_uppercase();
        if !matches!(
            method.as_str(),
            "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS"
        ) {
            return Err(format!(
                "api-docs operation {key:?} at {canonical} uses unsupported HTTP method {method:?}"
            ));
        }
        if let Some(other) = operations.insert(method.clone(), key.as_str()) {
            return Err(format!(
                "api-docs operations {other:?} and {key:?} both own {method} {canonical}"
            ));
        }
    }
    if operations.is_empty() {
        return Err(format!(
            "{canonical} has no HTTP operation in the api-docs route map"
        ));
    }
    Ok(operations)
}

fn expected_operations<'a>(route_map: &'a RouteMap, canonical: &str) -> Vec<&'a str> {
    route_map
        .map
        .iter()
        .filter(|(_, entry)| entry.path == canonical)
        .map(|(key, _)| key.as_str())
        .collect()
}

fn reject_reserved_rpc_path(source: &str, canonical: &str) -> Result<(), String> {
    if matches!(canonical, RPC_V1_CANONICAL_PATH | RPC_V1_LEGACY_PATH) {
        return Err(format!(
            "{source} derives reserved RPC transport path {canonical}; /v1/rpc is runtime-owned and cannot be authored as route.rs"
        ));
    }
    Ok(())
}

fn sibling_generator(repo_root: &Path, page_source: &str) -> Result<Option<PathBuf>, String> {
    let root = repo_root
        .canonicalize()
        .map_err(|error| format!("canonicalize {}: {error}", repo_root.display()))?;
    let page = root.join(page_source);
    let parent = page
        .parent()
        .ok_or_else(|| format!("page source has no parent directory: {page_source}"))?;
    let generator = parent.join(PAGE_GENERATOR_LEAF);
    Ok(generator.is_file().then_some(generator))
}

fn absolute_source(repo_root: &Path, source: &str) -> Result<PathBuf, String> {
    let root = repo_root
        .canonicalize()
        .map_err(|error| format!("canonicalize {}: {error}", repo_root.display()))?;
    let path = root.join(source);
    if !path.is_file() {
        return Err(format!("route source does not exist: {}", path.display()));
    }
    Ok(path)
}

fn module_ident(prefix: &str, source: &str) -> String {
    let mut out = format!("__ores_{prefix}_");
    for ch in source.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identifiers_are_stable_and_rust_safe() {
        assert_eq!(
            module_ident("page", "src/pages/users/[id]/page.rs"),
            "__ores_page_src_pages_users__id__page_rs"
        );
        assert_eq!(
            module_ident("gen", "src/pages/users/[id]/gen.rs"),
            "__ores_gen_src_pages_users__id__gen_rs"
        );
    }

    #[test]
    fn method_router_can_chain_multiple_verbs_from_one_file() {
        let handlers = vec![
            crate::HttpRouteHandlerSource {
                rust_name: "post".into(),
                method: "POST".into(),
                parameter_types: vec![],
                return_type: None,
            },
            crate::HttpRouteHandlerSource {
                rust_name: "get".into(),
                method: "GET".into(),
                parameter_types: vec![],
                return_type: None,
            },
        ];
        assert_eq!(
            method_router_expression("route_mod", &handlers).unwrap(),
            "::axum::routing::get(route_mod::get).post(route_mod::post)"
        );
    }

    #[test]
    fn rpc_transport_paths_are_not_application_routes() {
        assert!(reject_reserved_rpc_path("src/routes/v1/rpc/route.rs", "/v1/rpc").is_err());
        assert!(reject_reserved_rpc_path("src/routes/rpc/v1/route.rs", "/rpc/v1").is_err());
        assert!(reject_reserved_rpc_path("src/routes/v1/users/route.rs", "/v1/users").is_ok());
    }
}
