//! Canonical filesystem layout for generated RPC operation modules.
//!
//! The low-level transport/runtime client is intentionally outside the per-language
//! `generated/` directory. Only operation-specific generated modules live under
//! `generated/`, namespaced by the canonical dotted RPC key after dropping the
//! service/root segment.

use std::path::PathBuf;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RpcSdkLanguage {
    Rust,
    Go,
    Dart,
    TypeScript,
    Gleam,
}

impl RpcSdkLanguage {
    pub const ALL: [Self; 5] = [
        Self::Rust,
        Self::Go,
        Self::Dart,
        Self::TypeScript,
        Self::Gleam,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Rust => "rust",
            Self::Go => "go",
            Self::Dart => "dart",
            Self::TypeScript => "typescript",
            Self::Gleam => "gleam",
        }
    }

    pub const fn extension(self) -> &'static str {
        match self {
            Self::Rust => "rs",
            Self::Go => "go",
            Self::Dart => "dart",
            Self::TypeScript => "ts",
            Self::Gleam => "gleam",
        }
    }

    /// Root containing operation-specific generated modules for this language.
    /// There are exactly five such roots, one per supported language.
    pub fn generated_root(self) -> PathBuf {
        match self {
            Self::Rust => PathBuf::from("rust/generated"),
            Self::Go => PathBuf::from("go/generated"),
            Self::Dart => PathBuf::from("dart/lib/generated"),
            Self::TypeScript => PathBuf::from("typescript/generated"),
            Self::Gleam => PathBuf::from("gleam/src/generated"),
        }
    }

    /// Runtime/transport code is intentionally outside `generated/`.
    pub fn runtime_root(self) -> PathBuf {
        match self {
            Self::Rust => PathBuf::from("rust/runtime"),
            Self::Go => PathBuf::from("go/runtime"),
            Self::Dart => PathBuf::from("dart/lib/runtime"),
            Self::TypeScript => PathBuf::from("typescript/runtime"),
            Self::Gleam => PathBuf::from("gleam/src/runtime"),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RpcOperationModulePath {
    pub service_root: String,
    pub namespace: Vec<String>,
    pub operation: String,
}

impl RpcOperationModulePath {
    pub fn from_rpc_key(rpc_key: &str) -> Result<Self, String> {
        let segments = rpc_key.split('.').collect::<Vec<_>>();
        if segments.len() < 2 {
            return Err(format!(
                "RPC operation key {rpc_key:?} must contain a service/root segment and operation"
            ));
        }
        for segment in &segments {
            if !is_snake_identifier(segment) {
                return Err(format!(
                    "RPC operation key {rpc_key:?} contains non-snake_case segment {segment:?}"
                ));
            }
        }
        let service_root = segments[0].to_owned();
        let operation = segments[segments.len() - 1].to_owned();
        let namespace = segments[1..segments.len() - 1]
            .iter()
            .map(|value| (*value).to_owned())
            .collect();
        Ok(Self {
            service_root,
            namespace,
            operation,
        })
    }

    pub fn relative_operation_path(&self, language: RpcSdkLanguage) -> PathBuf {
        let mut path = language.generated_root();
        for segment in &self.namespace {
            path.push(segment);
        }
        path.push(format!("{}.{}", self.operation, language.extension()));
        path
    }
}

pub const GENERATED_README: &str = r#"# Generated RPC operations

This directory is generated by `ores-stack sync` / `ores-api-docs`.

- Do not edit files in this directory by hand.
- Operation modules are namespaced from the canonical dotted RPC key after the service/root segment.
- Generic RPC transport/runtime code lives outside this directory under `../runtime` (or the language-equivalent runtime path).
- Regeneration temporarily makes this tree writable and then restores read-only permissions.
- Git does not preserve ordinary read-only permission bits, so the generator reapplies read-only permissions after every materialization/check cycle.
"#;

pub const GENERATED_AGENTS: &str = r#"# AGENTS.md — generated RPC operations

This directory is machine-generated and read-only after generation.

Rules for agents and contributors:
1. Never hand-edit operation files under this directory.
2. Change `handlers.rs`, TypeSpec/JSON Schema Contract IR, or the generator instead.
3. Regenerate with `ores-stack sync` and verify with `ores-stack sync --check`.
4. Preserve the canonical dotted RPC wire key; filesystem namespaces are projections only.
5. Runtime/transport implementation belongs outside this generated tree.
"#;

pub fn generated_source_header(language: RpcSdkLanguage, rpc_key: &str) -> String {
    match language {
        RpcSdkLanguage::TypeScript => {
            format!("/** @generated by ores-api-docs/ores-stack from {rpc_key}; DO NOT EDIT. */\n")
        }
        RpcSdkLanguage::Dart => {
            format!("// @generated by ores-api-docs/ores-stack from {rpc_key}; DO NOT EDIT.\n")
        }
        RpcSdkLanguage::Rust => {
            format!("// @generated by ores-api-docs/ores-stack from {rpc_key}; DO NOT EDIT.\n")
        }
        RpcSdkLanguage::Go => {
            format!("// Code generated by ores-api-docs/ores-stack from {rpc_key}; DO NOT EDIT.\n")
        }
        RpcSdkLanguage::Gleam => {
            format!("// @generated by ores-api-docs/ores-stack from {rpc_key}; DO NOT EDIT.\n")
        }
    }
}

fn is_snake_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_lowercase() || first == '_') {
        return false;
    }
    chars.all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_')
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sonus_admin_key_maps_to_admin_version_operation_module() {
        let path = RpcOperationModulePath::from_rpc_key("sonus_auris.admin.version.get_version")
            .expect("valid key");
        assert_eq!(path.service_root, "sonus_auris");
        assert_eq!(path.namespace, vec!["admin", "version"]);
        assert_eq!(path.operation, "get_version");
        assert_eq!(
            path.relative_operation_path(RpcSdkLanguage::TypeScript),
            PathBuf::from("typescript/generated/admin/version/get_version.ts")
        );
        assert_eq!(
            path.relative_operation_path(RpcSdkLanguage::Rust),
            PathBuf::from("rust/generated/admin/version/get_version.rs")
        );
    }

    #[test]
    fn regular_service_root_is_not_repeated_in_filesystem_namespace() {
        let sonus = RpcOperationModulePath::from_rpc_key("sonus_auris.version.get_version")
            .expect("valid key");
        let canonical = RpcOperationModulePath::from_rpc_key("canonical_cloud.version.get_version")
            .expect("valid key");
        assert_eq!(
            sonus.relative_operation_path(RpcSdkLanguage::Go),
            PathBuf::from("go/generated/version/get_version.go")
        );
        assert_eq!(
            canonical.relative_operation_path(RpcSdkLanguage::Dart),
            PathBuf::from("dart/lib/generated/version/get_version.dart")
        );
    }

    #[test]
    fn there_are_exactly_five_generated_roots() {
        let roots = RpcSdkLanguage::ALL
            .into_iter()
            .map(RpcSdkLanguage::generated_root)
            .collect::<std::collections::BTreeSet<_>>();
        assert_eq!(roots.len(), 5);
        assert!(roots.contains(&PathBuf::from("rust/generated")));
        assert!(roots.contains(&PathBuf::from("go/generated")));
        assert!(roots.contains(&PathBuf::from("dart/lib/generated")));
        assert!(roots.contains(&PathBuf::from("typescript/generated")));
        assert!(roots.contains(&PathBuf::from("gleam/src/generated")));
    }

    #[test]
    fn invalid_or_flat_keys_fail_closed() {
        assert!(RpcOperationModulePath::from_rpc_key("get_version").is_err());
        assert!(RpcOperationModulePath::from_rpc_key("Sonus.admin.get_version").is_err());
        assert!(RpcOperationModulePath::from_rpc_key("sonus-auris.admin.get_version").is_err());
    }
}
