//! Transport-neutral typed dispatch primitives.
//!
//! Everything here is part of the `operation-runtime` feature and links no
//! server framework. It is what a generated per-folder dispatcher is built
//! from, whether that dispatcher serves `/v1/rpc` on an Axum server or runs
//! inside a serverless function.
//!
//! # Ownership of the operation-key set
//!
//! This crate owns the reusable pieces: [`dispatch_typed_json_operation_in`],
//! [`DispatchError`], and the receipt mapping for the RPC endpoint. It does
//! **not** own the closed set of operation keys. That set is generated by
//! `ores-stack` from the handlers-authoritative operation inventory
//! (`#[ores_operation]` in `handlers.rs`), as a `match` whose wildcard arm
//! returns [`DispatchError::UnknownOperation`].
//!
//! Nothing in this module takes a `RouteMap`, by design. A route map only
//! knows operations that have an HTTP projection, so consulting one here would
//! make route-less operations undispatchable -- the lossiness this boundary
//! exists to prevent.
//!
//! # Status codes stay outside semantic dispatch
//!
//! [`DispatchError`] carries no HTTP status. Each adapter maps it for its own
//! carrier: an HTTP adapter answers 404, the RPC endpoint answers with
//! [`rpc_receipt_for_dispatch_error`], a direct Lambda invocation returns a
//! structured invocation error, and a queue consumer fails the record under
//! its retry policy.

use std::future::Future;

use serde::{de::DeserializeOwned, Serialize};
use serde_json::{Map, Value};
use thiserror::Error;

use crate::{
    OperationContext, OperationInvokeError, OperationRequestData, OperationSpec, OptionalJson,
    RpcPayloadCodec, RpcV1Call, RpcV1HttpContext, RpcV1Receipt, TypedOperationContext,
};

/// Why a generated dispatcher could not hand a call to an operation.
///
/// `#[non_exhaustive]`: further reasons are expected (for example a stream
/// mode the selected target cannot carry). Adapters must map the wildcard arm
/// to a hard failure.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum DispatchError {
    /// The key is not in the dispatcher's closed, handlers-authoritative set.
    #[error("operation {key:?} is not owned by this dispatcher")]
    UnknownOperation { key: String },
}

impl DispatchError {
    #[must_use]
    pub fn unknown_operation(key: impl Into<String>) -> Self {
        Self::UnknownOperation { key: key.into() }
    }

    /// Stable machine-readable slug, shared by every adapter's rendering.
    #[must_use]
    pub fn code(&self) -> &'static str {
        match self {
            Self::UnknownOperation { .. } => "unknown_operation",
        }
    }
}

/// The RPC endpoint's rendering of a [`DispatchError`].
///
/// This is an adapter mapping, kept here only because receipts are this
/// crate's wire type. Other carriers must not reuse its status.
#[must_use]
pub fn rpc_receipt_for_dispatch_error(call: &RpcV1Call, error: &DispatchError) -> RpcV1Receipt {
    let status = match error {
        DispatchError::UnknownOperation { .. } => 404,
    };
    failure_receipt(call, status, error.code(), error.to_string())
}

/// Canonical generated adapter for a context-centric operation served from the
/// `/v1/rpc` endpoint of a server.
///
/// `ores-stack rpc sync` emits only the stable type/operation binding and calls
/// this helper. Request section decoding, construction of `TypedOperationContext`,
/// invocation of the shared policy boundary, and receipt encoding therefore
/// remain identical for every generated `rpc.rs` file.
///
/// Equivalent to [`dispatch_typed_json_operation_in`] with
/// `OperationContext::rpc(state, http_context)`.
pub async fn dispatch_typed_json_operation<S, O, Invoke, Fut>(
    state: S,
    http_context: RpcV1HttpContext,
    call: RpcV1Call,
    invoke: Invoke,
) -> RpcV1Receipt
where
    O: OperationSpec,
    O::Path: DeserializeOwned,
    O::Query: DeserializeOwned,
    O::RequestHeaders: DeserializeOwned,
    O::RequestBody: DeserializeOwned,
    O::ResponseBody: Serialize,
    O::Error: Serialize,
    Invoke: FnOnce(TypedOperationContext<S, O>) -> Fut,
    Fut: Future<Output = Result<O::ResponseBody, OperationInvokeError<O::Error>>>,
{
    dispatch_typed_json_operation_in::<S, O, Invoke, Fut>(
        OperationContext::rpc(state, http_context),
        call,
        invoke,
    )
    .await
}

/// [`dispatch_typed_json_operation`] for a caller that builds the base context
/// itself.
///
/// An adapter that is not the server RPC endpoint needs to say how the call
/// arrived and where it is running -- transport, execution environment, whether
/// any ingress vouched for headers, and which policy applies. It builds that
/// `OperationContext` and passes it here; decoding, policy invocation and
/// receipt encoding stay byte-identical to the server path.
pub async fn dispatch_typed_json_operation_in<S, O, Invoke, Fut>(
    base: OperationContext<S>,
    call: RpcV1Call,
    invoke: Invoke,
) -> RpcV1Receipt
where
    O: OperationSpec,
    O::Path: DeserializeOwned,
    O::Query: DeserializeOwned,
    O::RequestHeaders: DeserializeOwned,
    O::RequestBody: DeserializeOwned,
    O::ResponseBody: Serialize,
    O::Error: Serialize,
    Invoke: FnOnce(TypedOperationContext<S, O>) -> Fut,
    Fut: Future<Output = Result<O::ResponseBody, OperationInvokeError<O::Error>>>,
{
    let path = match decode_section::<O::Path>(
        &call,
        "path",
        call.path.clone().map(Value::Object).unwrap_or(Value::Null),
    ) {
        Ok(value) => value,
        Err(receipt) => return *receipt,
    };
    let query = match decode_section::<O::Query>(
        &call,
        "query",
        call.query.clone().map(Value::Object).unwrap_or(Value::Null),
    ) {
        Ok(value) => value,
        Err(receipt) => return *receipt,
    };
    let headers = match decode_section::<O::RequestHeaders>(
        &call,
        "headers",
        call.headers
            .clone()
            .map(Value::Object)
            .unwrap_or(Value::Null),
    ) {
        Ok(value) => value,
        Err(receipt) => return *receipt,
    };
    let body_value = call.body.value().cloned().unwrap_or(Value::Null);
    let body = match decode_section::<O::RequestBody>(&call, "body", body_value.clone()) {
        Ok(value) => value,
        Err(receipt) => return *receipt,
    };

    let request = OperationRequestData::new(RpcPayloadCodec::Json);
    request.insert_path::<O>(path);
    request.insert_query::<O>(query);
    request.insert_headers::<O>(headers);
    request.insert_body::<O>(body);
    request.set_semantic_input(serde_json::json!({
        "path": &call.path,
        "query": &call.query,
        "headers": &call.headers,
        "body": body_value,
    }));

    let context = TypedOperationContext::<S, O>::new(base, request);

    match invoke(context).await {
        Ok(output) => match serde_json::to_value(output) {
            Ok(value) => {
                let mut receipt = RpcV1Receipt::success(
                    call.id.clone(),
                    call.key.clone(),
                    OptionalJson::present(value),
                );
                receipt.status = Some(200);
                receipt.trace_id = call.trace_id.clone();
                receipt.span_id = call.span_id.clone();
                receipt
            }
            Err(error) => failure_receipt(&call, 500, "response_encode_failed", error.to_string()),
        },
        Err(OperationInvokeError::Policy(rejection)) => {
            failure_receipt(&call, rejection.status, &rejection.code, rejection.message)
        }
        Err(error) => {
            let value = serde_json::to_value(error).unwrap_or_else(|encode_error| {
                serde_json::json!({
                    "code": "operation_error_encode_failed",
                    "message": encode_error.to_string(),
                })
            });
            let mut object = value
                .as_object()
                .cloned()
                .unwrap_or_else(|| Map::from_iter([("detail".to_owned(), value)]));
            object
                .entry("code".to_owned())
                .or_insert_with(|| Value::String("operation_error".to_owned()));
            let mut receipt = RpcV1Receipt::failure(call.id.clone(), call.key.clone(), 500, object);
            receipt.trace_id = call.trace_id.clone();
            receipt.span_id = call.span_id.clone();
            receipt
        }
    }
}

fn decode_section<T>(
    call: &RpcV1Call,
    section: &'static str,
    value: Value,
) -> Result<T, Box<RpcV1Receipt>>
where
    T: DeserializeOwned,
{
    serde_json::from_value(value).map_err(|error| {
        Box::new(failure_receipt(
            call,
            400,
            "request_decode_failed",
            format!("{section}: {error}"),
        ))
    })
}

fn failure_receipt(call: &RpcV1Call, status: u16, code: &str, message: String) -> RpcV1Receipt {
    let error = Map::from_iter([
        ("code".to_owned(), Value::String(code.to_owned())),
        ("message".to_owned(), Value::String(message)),
    ]);
    let mut receipt = RpcV1Receipt::failure(call.id.clone(), call.key.clone(), status, error);
    receipt.trace_id = call.trace_id.clone();
    receipt.span_id = call.span_id.clone();
    receipt
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use http::{HeaderMap, HeaderValue};
    use serde::{Deserialize, Serialize};

    use super::*;
    use crate::{
        invoke_typed_context_operation, ExecutionEnvironmentKind, NoSection, OperationDescriptor,
        OperationPolicy, OperationPolicyFuture, OperationPolicyOutcome, OperationPolicyPermit,
        OperationPolicyRejection, OperationPolicyRequest, OperationTransportKind, RpcStreamMode,
    };

    #[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
    struct EchoBody {
        value: String,
    }

    #[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
    struct EchoReply {
        value: String,
        transport: String,
        environment: String,
        has_trusted_ingress: bool,
    }

    #[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
    struct EchoError {
        code: String,
    }

    macro_rules! echo_operation {
        ($name:ident, $key:literal) => {
            struct $name;
            impl OperationSpec for $name {
                type Path = NoSection;
                type Query = NoSection;
                type RequestHeaders = NoSection;
                type RequestBody = EchoBody;
                type ResponseBody = EchoReply;
                type ResponseHeaders = NoSection;
                type ResponseTrailers = NoSection;
                type Error = EchoError;

                const KEY: &'static str = $key;
                const CODECS: &'static [RpcPayloadCodec] = &[RpcPayloadCodec::Json];
                const DEFAULT_CODEC: RpcPayloadCodec = RpcPayloadCodec::Json;
            }
        };
    }

    // `WithRoute` stands for an operation that also has an HTTP projection.
    // `RouteLess` has none: no route map anywhere names it. Both must dispatch,
    // because the key set below is authored from the operation inventory.
    echo_operation!(WithRoute, "demo.echo.with_route");
    echo_operation!(RouteLess, "demo.echo.route_less");

    static DESCRIPTOR: OperationDescriptor = OperationDescriptor {
        key: "demo.echo",
        codecs: &["json"],
        default_codec: "json",
        audiences: &["server"],
        scope: "regular",
        stream: RpcStreamMode::Unary,
    };

    async fn echo<O>(
        context: TypedOperationContext<(), O>,
    ) -> Result<EchoReply, OperationInvokeError<EchoError>>
    where
        O: OperationSpec<RequestBody = EchoBody>,
    {
        invoke_typed_context_operation(&DESCRIPTOR, context, |context| async move {
            let body = context.body().map_err(|_| EchoError {
                code: "body_missing".into(),
            })?;
            Ok(EchoReply {
                value: body.value.clone(),
                transport: format!("{:?}", context.transport()),
                environment: format!("{:?}", context.environment()),
                has_trusted_ingress: context.has_trusted_ingress(),
            })
        })
        .await
    }

    /// The exact shape `ores-stack` generates: a closed `match` over the
    /// handlers-authoritative keys, no `RouteMap`, and a wildcard arm that
    /// returns an error instead of `unreachable!`.
    async fn generated_style_try_dispatch(
        base: OperationContext<()>,
        call: RpcV1Call,
    ) -> Result<RpcV1Receipt, DispatchError> {
        match call.key.as_str() {
            "demo.echo.with_route" => {
                Ok(dispatch_typed_json_operation_in::<_, WithRoute, _, _>(base, call, echo).await)
            }
            "demo.echo.route_less" => {
                Ok(dispatch_typed_json_operation_in::<_, RouteLess, _, _>(base, call, echo).await)
            }
            other => Err(DispatchError::unknown_operation(other)),
        }
    }

    fn call(key: &str, value: &str) -> RpcV1Call {
        let mut call = RpcV1Call::new("call-1", key);
        call.body = OptionalJson::present(serde_json::json!({ "value": value }));
        call
    }

    fn reply(receipt: &RpcV1Receipt) -> EchoReply {
        assert!(receipt.ok, "expected success receipt, got {receipt:?}");
        serde_json::from_value(receipt.body.value().cloned().expect("receipt body"))
            .expect("typed reply")
    }

    #[tokio::test]
    async fn route_less_operation_dispatches_without_any_route_map() {
        let receipt = generated_style_try_dispatch(
            OperationContext::rpc_without_ingress(()),
            call("demo.echo.route_less", "hello"),
        )
        .await
        .expect("route-less operation is in the closed key set");
        assert_eq!(receipt.status, Some(200));
        assert_eq!(reply(&receipt).value, "hello");
    }

    #[tokio::test]
    async fn unknown_key_is_an_error_value_not_a_panic() {
        let error = generated_style_try_dispatch(
            OperationContext::rpc_without_ingress(()),
            call("demo.echo.nope", "x"),
        )
        .await
        .expect_err("unknown key must not dispatch");
        assert_eq!(
            error,
            DispatchError::UnknownOperation {
                key: "demo.echo.nope".into()
            }
        );
        assert_eq!(error.code(), "unknown_operation");
    }

    #[test]
    fn rpc_endpoint_rendering_of_unknown_operation_is_a_correlated_404_receipt() {
        let mut call = call("demo.echo.nope", "x");
        call.trace_id = Some("trace-1".into());
        let receipt = rpc_receipt_for_dispatch_error(
            &call,
            &DispatchError::unknown_operation("demo.echo.nope"),
        );
        assert!(!receipt.ok);
        assert_eq!(receipt.status, Some(404));
        assert_eq!(receipt.id, call.id);
        assert_eq!(receipt.key, call.key);
        assert_eq!(receipt.trace_id.as_deref(), Some("trace-1"));
        let error = receipt.error.as_ref().expect("error object");
        assert_eq!(
            error.get("code").and_then(Value::as_str),
            Some("unknown_operation")
        );
    }

    #[tokio::test]
    async fn adapter_supplied_context_reaches_the_authored_operation() {
        let mut headers = HeaderMap::new();
        headers.insert("x-forwarded-for", HeaderValue::from_static("203.0.113.9"));
        let base = OperationContext::http_with_headers((), headers)
            .with_environment(ExecutionEnvironmentKind::Lambda);
        let receipt = generated_style_try_dispatch(base, call("demo.echo.with_route", "v"))
            .await
            .expect("known key");
        let reply = reply(&receipt);
        assert_eq!(reply.transport, "Http");
        assert_eq!(reply.environment, "Lambda");
        assert!(reply.has_trusted_ingress);

        let direct = OperationContext::rpc_without_ingress(())
            .with_environment(ExecutionEnvironmentKind::Lambda);
        let receipt = generated_style_try_dispatch(direct, call("demo.echo.with_route", "v"))
            .await
            .expect("known key");
        let reply = self::reply(&receipt);
        assert_eq!(reply.transport, "Rpc");
        assert_eq!(reply.environment, "Lambda");
        assert!(!reply.has_trusted_ingress);
    }

    /// The pre-existing entry point must be exactly the `_in` variant with a
    /// server RPC context, so already-generated `rpc.rs` keeps its behaviour.
    #[tokio::test]
    async fn legacy_entry_point_equals_in_variant_with_server_rpc_context() {
        let mut headers = HeaderMap::new();
        headers.insert("x-request-id", HeaderValue::from_static("r-1"));
        let legacy = dispatch_typed_json_operation::<_, WithRoute, _, _>(
            (),
            RpcV1HttpContext::from_headers(headers.clone()),
            call("demo.echo.with_route", "same"),
            echo,
        )
        .await;
        let explicit = dispatch_typed_json_operation_in::<_, WithRoute, _, _>(
            OperationContext::rpc((), RpcV1HttpContext::from_headers(headers)),
            call("demo.echo.with_route", "same"),
            echo,
        )
        .await;
        assert_eq!(
            legacy.encode().expect("legacy receipt bytes"),
            explicit.encode().expect("explicit receipt bytes"),
        );
        let reply = reply(&legacy);
        assert_eq!(reply.transport, "Rpc");
        assert_eq!(reply.environment, "Server");
        assert!(reply.has_trusted_ingress);
    }

    #[tokio::test]
    async fn undecodable_section_is_a_400_receipt() {
        let mut bad = RpcV1Call::new("call-2", "demo.echo.with_route");
        bad.body = OptionalJson::present(serde_json::json!({ "value": 7 }));
        let receipt = generated_style_try_dispatch(OperationContext::rpc_without_ingress(()), bad)
            .await
            .expect("known key");
        assert!(!receipt.ok);
        assert_eq!(receipt.status, Some(400));
        let error = receipt.error.as_ref().expect("error object");
        assert_eq!(
            error.get("code").and_then(Value::as_str),
            Some("request_decode_failed")
        );
    }

    #[derive(Default)]
    struct RecordingPolicy {
        seen: Mutex<Vec<(OperationTransportKind, ExecutionEnvironmentKind, bool, bool)>>,
    }

    impl OperationPolicy for RecordingPolicy {
        fn before<'a>(
            &'a self,
            request: OperationPolicyRequest<'a>,
        ) -> OperationPolicyFuture<'a, Result<OperationPolicyPermit, OperationPolicyRejection>>
        {
            self.seen.lock().expect("lock").push((
                request.transport,
                request.environment,
                request.has_trusted_ingress,
                request.trusted_headers.is_empty(),
            ));
            // A policy that refuses header-derived identity when nothing
            // vouched for headers -- the decision this flag exists to enable.
            let admit = request.has_trusted_ingress
                || request.environment != ExecutionEnvironmentKind::Lambda;
            Box::pin(async move {
                if admit {
                    Ok(OperationPolicyPermit::default())
                } else {
                    Err(OperationPolicyRejection::new(
                        401,
                        "no_trusted_ingress",
                        "no ingress vouched for caller identity",
                    ))
                }
            })
        }

        fn after<'a>(
            &'a self,
            outcome: OperationPolicyOutcome<'a>,
        ) -> OperationPolicyFuture<'a, ()> {
            assert_eq!(outcome.environment, ExecutionEnvironmentKind::Lambda);
            Box::pin(async {})
        }
    }

    #[tokio::test]
    async fn policy_sees_environment_and_can_tell_no_ingress_from_empty_headers() {
        let policy = Arc::new(RecordingPolicy::default());

        // Ingress vouched for an empty header set: admitted.
        let empty_but_vouched = OperationContext::http_with_headers((), HeaderMap::new())
            .with_environment(ExecutionEnvironmentKind::Lambda)
            .with_policy(policy.clone());
        let receipt =
            generated_style_try_dispatch(empty_but_vouched, call("demo.echo.with_route", "a"))
                .await
                .expect("known key");
        assert!(receipt.ok);

        // Nothing vouched for anything: same empty headers, different answer.
        let no_ingress = OperationContext::rpc_without_ingress(())
            .with_environment(ExecutionEnvironmentKind::Lambda)
            .with_policy(policy.clone());
        let receipt = generated_style_try_dispatch(no_ingress, call("demo.echo.with_route", "b"))
            .await
            .expect("known key");
        assert!(!receipt.ok);
        assert_eq!(receipt.status, Some(401));
        let error = receipt.error.as_ref().expect("policy rejection error");
        assert_eq!(
            error.get("code").and_then(Value::as_str),
            Some("no_trusted_ingress")
        );
        assert_eq!(
            error.get("message").and_then(Value::as_str),
            Some("no ingress vouched for caller identity")
        );

        assert_eq!(
            *policy.seen.lock().expect("lock"),
            vec![
                (
                    OperationTransportKind::Http,
                    ExecutionEnvironmentKind::Lambda,
                    true,
                    true
                ),
                (
                    OperationTransportKind::Rpc,
                    ExecutionEnvironmentKind::Lambda,
                    false,
                    true
                ),
            ]
        );
    }
}
