use crate::{FsRoute, FsRouteKind};

/// Marker written at the top of generated web-page `lambda.rs` files.
pub const GENERATED_PAGE_LAMBDA_MARKER: &str =
    "// @generated by ores-api-docs for a *-web-server.rs page; DO NOT EDIT.";

/// Generate one provider-neutral executable source file for a browser page.
///
/// The same sibling `lambda.rs` is compiled twice (or more) with a mutually
/// exclusive provider feature selected by the generated `ores-stack` build
/// manifest. This keeps `src/pages/**/lambda.rs` 1:1 with `page.rs` while
/// allowing the artifact to target both AWS and GCP.
///
/// This is intentionally a **web-page** projection. It never imports RPC
/// dispatch code, never generates `rpc.rs`, and never turns the page into an
/// api-docs operation. `ores-stack` owns when/where this file is materialized.
pub fn page_lambda_glue(route: &FsRoute) -> Result<String, String> {
    if route.kind != FsRouteKind::Page {
        return Err("page_lambda_glue accepts only src/pages/**/page.rs routes".to_owned());
    }

    let canonical_path = route.canonical_path();
    let axum_paths = route.axum_paths();

    let mut out = String::new();
    out.push_str(GENERATED_PAGE_LAMBDA_MARKER);
    out.push('\n');
    out.push_str("// WEB SERVER PAGE LAMBDA ONLY — not an API-server RPC adapter.\n\n");
    out.push_str("#[path = \"page.rs\"]\nmod __ores_page;\n\n");
    out.push_str(&format!(
        "pub const ORES_PAGE_SOURCE: &str = {:?};\npub const ORES_PAGE_ROUTE: &str = {:?};\npub const ORES_PAGE_AXUM_PATHS: &[&str] = &[{}];\n\n",
        route.source,
        canonical_path,
        axum_paths
            .iter()
            .map(|path| format!("{path:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str(
        "async fn __ores_handle_page(\n    request: ::ores_page_lambda_runtime::PageHttpRequest,\n) -> Result<::ores_page_lambda_runtime::PageHttpResponse, ::ores_page_lambda_runtime::RuntimeError> {\n    ::ores_page_lambda_runtime::invoke_page(\n        request,\n        ORES_PAGE_ROUTE,\n        ORES_PAGE_AXUM_PATHS,\n        |ctx| __ores_page::__ores_page_boxed(ctx),\n    ).await\n}\n\n",
    );
    out.push_str(
        "#[cfg(all(feature = \"ores-page-lambda-aws\", feature = \"ores-page-lambda-gcp\"))]\ncompile_error!(\"generated page lambda provider features are mutually exclusive\");\n\n",
    );
    out.push_str(
        "#[cfg(all(not(feature = \"ores-page-lambda-aws\"), not(feature = \"ores-page-lambda-gcp\")))]\ncompile_error!(\"generated page lambda requires exactly one provider feature: ores-page-lambda-aws or ores-page-lambda-gcp\");\n\n",
    );
    out.push_str(
        "#[cfg(all(feature = \"ores-page-lambda-aws\", not(feature = \"ores-page-lambda-gcp\")))]\n#[tokio::main]\nasync fn main() -> Result<(), ::ores_page_lambda_runtime::RuntimeError> {\n    ::ores_page_lambda_runtime::aws::run_page(__ores_handle_page).await\n}\n\n",
    );
    out.push_str(
        "#[cfg(all(feature = \"ores-page-lambda-gcp\", not(feature = \"ores-page-lambda-aws\")))]\n#[tokio::main]\nasync fn main() -> Result<(), ::ores_page_lambda_runtime::RuntimeError> {\n    ::ores_page_lambda_runtime::gcp::run_page(__ores_handle_page).await\n}\n",
    );
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_one_web_only_source_for_aws_and_gcp() {
        let route = FsRoute::page("src/pages/users/[id]/page.rs").expect("page route");
        let source = page_lambda_glue(&route).expect("lambda source");
        assert!(source.starts_with(GENERATED_PAGE_LAMBDA_MARKER));
        assert!(source.contains("WEB SERVER PAGE LAMBDA ONLY"));
        assert!(source.contains("ORES_PAGE_ROUTE: &str = \"/users/{id}\""));
        assert!(source.contains("ores-page-lambda-aws"));
        assert!(source.contains("ores-page-lambda-gcp"));
        assert!(source.contains("ores_page_lambda_runtime::aws::run_page"));
        assert!(source.contains("ores_page_lambda_runtime::gcp::run_page"));
        assert!(source.contains("provider features are mutually exclusive"));
        assert!(!source.contains("rpc.rs"));
        assert!(!source.contains("RpcV1"));
    }

    #[test]
    fn preserves_optional_catch_all_projection() {
        let route = FsRoute::page("src/pages/docs/[[...slug]]/page.rs").expect("page route");
        let source = page_lambda_glue(&route).expect("lambda source");
        assert!(source.contains("\"/docs\", \"/docs/{*slug}\""));
    }

    #[test]
    fn refuses_api_routes() {
        let route = FsRoute::api_handler("src/routes/v1/health/route.rs").expect("api route");
        let error = page_lambda_glue(&route).expect_err("must refuse api");
        assert!(error.contains("only src/pages/**/page.rs"));
    }
}
