//! Deterministic generated projections of the admitted web-page manifest.
//!
//! The JSON manifest is the machine-readable source/docs projection. Markdown
//! and HTML are derived views of those exact admitted entries. All three files
//! are generator-owned artifacts and are written only through the fail-closed
//! ownership/path checks in this module.

use crate::{
    page_layout::manifest::{
        web_page_manifest, WebPageManifest, WebPageManifestError, WEB_PAGE_MANIFEST_GENERATOR,
        WEB_PAGE_MANIFEST_SCHEMA,
    },
    PageBuildManifest,
};
use std::{
    fs::{self, OpenOptions},
    io::Write,
    path::{Component, Path, PathBuf},
    process,
    time::{SystemTime, UNIX_EPOCH},
};
use thiserror::Error;

pub const WEB_PAGE_DOCS_MARKER: &str =
    "<!-- @generated by ores-api-docs page docs; do not edit -->";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WebPageDocOutputs {
    pub manifest_path: PathBuf,
    pub markdown_path: PathBuf,
    pub html_path: PathBuf,
}

#[derive(Debug, Error)]
pub enum WebPageDocProjectionError {
    #[error(transparent)]
    Manifest(#[from] WebPageManifestError),
    #[error("page-doc projection I/O at {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },
    #[error("page-doc projection JSON error at {path}: {message}")]
    Json { path: String, message: String },
    #[error("page-doc generated-output ownership refused at {path}: {reason}")]
    Ownership { path: String, reason: String },
    #[error("page-doc generated-output drift at {path}")]
    Drift { path: String },
}

#[must_use]
pub fn render_web_page_markdown(manifest: &WebPageManifest) -> String {
    let mut out = String::new();
    out.push_str(WEB_PAGE_DOCS_MARKER);
    out.push_str("\n# Web pages\n\n");
    out.push_str(&format!(
        "Manifest: `{}` · digest: `{}`\n\n",
        manifest.schema, manifest.manifest_sha256
    ));
    out.push_str("| URL | Source | Render | Auth | Layouts | Generator | RPC dependencies |\n");
    out.push_str("| --- | --- | --- | --- | ---: | --- | --- |\n");
    for page in &manifest.pages {
        let rpc = if page.rpc_dependencies.is_empty() {
            "—".to_owned()
        } else {
            page.rpc_dependencies.join(", ")
        };
        let generator = page
            .generator_source
            .as_ref()
            .map(|source| source.source.as_str())
            .unwrap_or("—");
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` / `{}` | `{}` | {} | `{}` | {} |\n",
            markdown_cell(&page.canonical_url),
            markdown_cell(&page.source_page_rs),
            markdown_cell(&page.renderer),
            markdown_cell(&page.render_mode),
            markdown_cell(&page.auth),
            page.layout_sources.len(),
            markdown_cell(generator),
            markdown_cell(&rpc),
        ));
    }
    out
}

#[must_use]
pub fn render_web_page_html(manifest: &WebPageManifest) -> String {
    let mut rows = String::new();
    for page in &manifest.pages {
        let rpc = if page.rpc_dependencies.is_empty() {
            "—".to_owned()
        } else {
            page.rpc_dependencies.join(", ")
        };
        let render = format!("{} / {}", page.renderer, page.render_mode);
        let generator = page
            .generator_source
            .as_ref()
            .map(|source| source.source.as_str())
            .unwrap_or("—");
        rows.push_str("<tr>");
        for value in [
            page.canonical_url.as_str(),
            page.source_page_rs.as_str(),
            render.as_str(),
            page.auth.as_str(),
        ] {
            rows.push_str("<td><code>");
            rows.push_str(&html_escape(value));
            rows.push_str("</code></td>");
        }
        rows.push_str(&format!("<td>{}</td>", page.layout_sources.len()));
        for value in [generator, rpc.as_str()] {
            rows.push_str("<td><code>");
            rows.push_str(&html_escape(value));
            rows.push_str("</code></td>");
        }
        rows.push_str("</tr>\n");
    }
    format!(
        "{marker}\n<!doctype html>\n<meta charset=\"utf-8\">\n<title>Web pages</title>\n<h1>Web pages</h1>\n<p>Manifest <code>{schema}</code> · digest <code>{digest}</code></p>\n<table><thead><tr><th>URL</th><th>Source</th><th>Render</th><th>Auth</th><th>Layouts</th><th>Generator</th><th>RPC dependencies</th></tr></thead><tbody>\n{rows}</tbody></table>\n",
        marker = WEB_PAGE_DOCS_MARKER,
        schema = html_escape(&manifest.schema),
        digest = html_escape(&manifest.manifest_sha256),
    )
}

pub fn sync_web_page_docs(
    repo_root: &Path,
    build: &PageBuildManifest,
    out_dir: &Path,
    check: bool,
) -> Result<WebPageDocOutputs, WebPageDocProjectionError> {
    let root = fs::canonicalize(repo_root).map_err(|source| WebPageDocProjectionError::Io {
        path: repo_root.display().to_string(),
        source,
    })?;
    let out_dir = if out_dir.is_absolute() {
        out_dir.to_path_buf()
    } else {
        root.join(out_dir)
    };
    verify_confined_path(&root, &out_dir, false)?;

    let manifest = web_page_manifest(&root, build)?;
    let mut manifest_bytes = serde_json::to_vec_pretty(&manifest).map_err(|error| {
        WebPageDocProjectionError::Json {
            path: out_dir.join("page-manifest.json").display().to_string(),
            message: error.to_string(),
        }
    })?;
    manifest_bytes.push(b'\n');
    let markdown = render_web_page_markdown(&manifest).into_bytes();
    let html = render_web_page_html(&manifest).into_bytes();

    let manifest_path = out_dir.join("page-manifest.json");
    let markdown_path = out_dir.join("pages.md");
    let html_path = out_dir.join("pages.html");

    sync_owned_file(
        &root,
        &manifest_path,
        &manifest_bytes,
        check,
        OutputKind::Manifest,
    )?;
    sync_owned_file(
        &root,
        &markdown_path,
        &markdown,
        check,
        OutputKind::MarkedText,
    )?;
    sync_owned_file(&root, &html_path, &html, check, OutputKind::MarkedText)?;

    Ok(WebPageDocOutputs {
        manifest_path,
        markdown_path,
        html_path,
    })
}

#[derive(Clone, Copy)]
enum OutputKind {
    Manifest,
    MarkedText,
}

fn sync_owned_file(
    root: &Path,
    path: &Path,
    expected: &[u8],
    check: bool,
    kind: OutputKind,
) -> Result<(), WebPageDocProjectionError> {
    verify_confined_path(root, path, true)?;
    if check {
        let actual = fs::read(path).map_err(|source| WebPageDocProjectionError::Io {
            path: path.display().to_string(),
            source,
        })?;
        if actual != expected {
            return Err(WebPageDocProjectionError::Drift {
                path: path.display().to_string(),
            });
        }
        return Ok(());
    }

    ensure_confined_parent_dirs(root, path)?;
    verify_confined_path(root, path, true)?;
    verify_owned_destination(path, kind)?;

    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("page-docs");
    let temp = path.with_file_name(format!(
        ".{file_name}.ores-page-docs-{}-{nonce:x}",
        process::id()
    ));
    verify_confined_path(root, &temp, true)?;

    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&temp)
        .map_err(|source| WebPageDocProjectionError::Io {
            path: temp.display().to_string(),
            source,
        })?;
    if let Err(source) = file.write_all(expected).and_then(|()| file.sync_all()) {
        let _ = fs::remove_file(&temp);
        return Err(WebPageDocProjectionError::Io {
            path: temp.display().to_string(),
            source,
        });
    }
    drop(file);

    if let Err(error) =
        verify_confined_path(root, path, true).and_then(|_| verify_owned_destination(path, kind))
    {
        let _ = fs::remove_file(&temp);
        return Err(error);
    }
    if let Err(source) = fs::rename(&temp, path) {
        let _ = fs::remove_file(&temp);
        return Err(WebPageDocProjectionError::Io {
            path: path.display().to_string(),
            source,
        });
    }
    Ok(())
}

fn verify_owned_destination(
    path: &Path,
    kind: OutputKind,
) -> Result<(), WebPageDocProjectionError> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(source) => {
            return Err(WebPageDocProjectionError::Io {
                path: path.display().to_string(),
                source,
            })
        }
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(WebPageDocProjectionError::Ownership {
            path: path.display().to_string(),
            reason: "existing generated destination must be a regular non-symlink file".to_owned(),
        });
    }

    let bytes = fs::read(path).map_err(|source| WebPageDocProjectionError::Io {
        path: path.display().to_string(),
        source,
    })?;
    let owned = match kind {
        OutputKind::MarkedText => first_line(&bytes) == Some(WEB_PAGE_DOCS_MARKER.as_bytes()),
        OutputKind::Manifest => {
            let manifest = serde_json::from_slice::<WebPageManifest>(&bytes).map_err(|error| {
                WebPageDocProjectionError::Ownership {
                    path: path.display().to_string(),
                    reason: format!("existing JSON manifest is not an owned manifest: {error}"),
                }
            })?;
            manifest.schema == WEB_PAGE_MANIFEST_SCHEMA
                && manifest.generated_by == WEB_PAGE_MANIFEST_GENERATOR
        }
    };
    if owned {
        Ok(())
    } else {
        Err(WebPageDocProjectionError::Ownership {
            path: path.display().to_string(),
            reason: "existing destination does not carry the exact page-doc generator ownership marker"
                .to_owned(),
        })
    }
}

fn first_line(bytes: &[u8]) -> Option<&[u8]> {
    let line = bytes
        .split(|byte| *byte == b'\n')
        .next()
        .unwrap_or(bytes);
    Some(line.strip_suffix(b"\r").unwrap_or(line))
}

fn confined_relative<'a>(
    root: &Path,
    path: &'a Path,
) -> Result<&'a Path, WebPageDocProjectionError> {
    let relative = path
        .strip_prefix(root)
        .map_err(|_| WebPageDocProjectionError::Ownership {
            path: path.display().to_string(),
            reason: format!("output escapes repository root {}", root.display()),
        })?;
    if relative.as_os_str().is_empty()
        || relative.components().any(|component| {
            matches!(
                component,
                Component::ParentDir | Component::RootDir | Component::Prefix(_)
            )
        })
    {
        return Err(WebPageDocProjectionError::Ownership {
            path: path.display().to_string(),
            reason: "output path must be a normalized child of the repository root".to_owned(),
        });
    }
    Ok(relative)
}

fn verify_confined_path(
    root: &Path,
    path: &Path,
    leaf_may_be_file: bool,
) -> Result<(), WebPageDocProjectionError> {
    let relative = confined_relative(root, path)?;
    let mut current = root.to_path_buf();
    let components = relative.components().collect::<Vec<_>>();
    for (index, component) in components.iter().enumerate() {
        let Component::Normal(segment) = component else {
            return Err(WebPageDocProjectionError::Ownership {
                path: path.display().to_string(),
                reason: "output path contains a non-normal component".to_owned(),
            });
        };
        current.push(segment);
        match fs::symlink_metadata(&current) {
            Ok(metadata) => {
                if metadata.file_type().is_symlink() {
                    return Err(WebPageDocProjectionError::Ownership {
                        path: current.display().to_string(),
                        reason: "output path traverses a symlink".to_owned(),
                    });
                }
                let is_leaf = index + 1 == components.len();
                if (!is_leaf || !leaf_may_be_file) && !metadata.is_dir() {
                    return Err(WebPageDocProjectionError::Ownership {
                        path: current.display().to_string(),
                        reason: "output parent component is not a directory".to_owned(),
                    });
                }
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => break,
            Err(source) => {
                return Err(WebPageDocProjectionError::Io {
                    path: current.display().to_string(),
                    source,
                })
            }
        }
    }
    Ok(())
}

fn ensure_confined_parent_dirs(
    root: &Path,
    path: &Path,
) -> Result<(), WebPageDocProjectionError> {
    let parent = path
        .parent()
        .ok_or_else(|| WebPageDocProjectionError::Ownership {
            path: path.display().to_string(),
            reason: "generated output has no parent directory".to_owned(),
        })?;
    let relative = confined_relative(root, parent)?;
    let mut current = root.to_path_buf();
    for component in relative.components() {
        let Component::Normal(segment) = component else {
            return Err(WebPageDocProjectionError::Ownership {
                path: parent.display().to_string(),
                reason: "output parent contains a non-normal component".to_owned(),
            });
        };
        current.push(segment);
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(WebPageDocProjectionError::Ownership {
                    path: current.display().to_string(),
                    reason: "output parent traverses a symlink".to_owned(),
                });
            }
            Ok(metadata) if !metadata.is_dir() => {
                return Err(WebPageDocProjectionError::Ownership {
                    path: current.display().to_string(),
                    reason: "output parent component is not a directory".to_owned(),
                });
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                fs::create_dir(&current).map_err(|source| WebPageDocProjectionError::Io {
                    path: current.display().to_string(),
                    source,
                })?;
                let metadata = fs::symlink_metadata(&current).map_err(|source| {
                    WebPageDocProjectionError::Io {
                        path: current.display().to_string(),
                        source,
                    }
                })?;
                if metadata.file_type().is_symlink() || !metadata.is_dir() {
                    return Err(WebPageDocProjectionError::Ownership {
                        path: current.display().to_string(),
                        reason: "created output parent is not a real directory".to_owned(),
                    });
                }
            }
            Err(source) => {
                return Err(WebPageDocProjectionError::Io {
                    path: current.display().to_string(),
                    source,
                })
            }
        }
    }
    Ok(())
}

fn markdown_cell(value: &str) -> String {
    value.replace('\\', "\\\\").replace('|', "\\|").replace('`', "\\`")
}

fn html_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::PageBuildRoute;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_root(label: &str) -> PathBuf {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "ores-page-doc-projection-{label}-{}-{nonce}",
            std::process::id()
        ));
        fs::create_dir_all(root.join("src/pages/a")).unwrap();
        fs::write(root.join("src/pages/layout.rs"), "// layout\n").unwrap();
        fs::write(root.join("src/pages/a/page.rs"), "// page\n").unwrap();
        root
    }

    fn build() -> PageBuildManifest {
        PageBuildManifest {
            schema_version: "1.2.0".to_owned(),
            route_root: "src/pages".to_owned(),
            wasm_have_header: "x-ores-wasm-have".to_owned(),
            wasm_have_cookie: "ores_wasm_have".to_owned(),
            routes: vec![PageBuildRoute {
                source: "src/pages/a/page.rs".to_owned(),
                generator: None,
                canonical_path: "/a".to_owned(),
                axum_paths: vec!["/a".to_owned()],
                dioxus_paths: vec!["/a".to_owned()],
                renderer: "mash".to_owned(),
                delivery: "ssr_only".to_owned(),
                render: "dynamic".to_owned(),
                revalidate_secs: None,
                on_demand: None,
                title: Some("A | `page`".to_owned()),
                summary: None,
                auth: "public".to_owned(),
                stability: "stable".to_owned(),
                database: "none".to_owned(),
                features: vec![],
                data_sources: vec![],
                tags: vec![],
                css: None,
                wasm: None,
            }],
        }
    }

    #[test]
    fn sync_then_check_is_byte_exact_and_deterministic() {
        let root = temp_root("sync-check");
        let outputs = sync_web_page_docs(&root, &build(), Path::new("generated/web"), false)
            .unwrap();
        let first_manifest = fs::read(&outputs.manifest_path).unwrap();
        let first_markdown = fs::read(&outputs.markdown_path).unwrap();
        let first_html = fs::read(&outputs.html_path).unwrap();
        sync_web_page_docs(&root, &build(), Path::new("generated/web"), true).unwrap();
        sync_web_page_docs(&root, &build(), Path::new("generated/web"), false).unwrap();
        assert_eq!(first_manifest, fs::read(&outputs.manifest_path).unwrap());
        assert_eq!(first_markdown, fs::read(&outputs.markdown_path).unwrap());
        assert_eq!(first_html, fs::read(&outputs.html_path).unwrap());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn authored_destination_is_never_overwritten() {
        let root = temp_root("authored-collision");
        let out = root.join("generated/web");
        fs::create_dir_all(&out).unwrap();
        let path = out.join("pages.md");
        fs::write(&path, "# authored\n").unwrap();
        assert!(matches!(
            sync_web_page_docs(&root, &build(), Path::new("generated/web"), false),
            Err(WebPageDocProjectionError::Ownership { .. })
        ));
        assert_eq!(fs::read_to_string(path).unwrap(), "# authored\n");
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn schema_shaped_but_unowned_json_is_never_overwritten() {
        let root = temp_root("json-collision");
        let out = root.join("generated/web");
        fs::create_dir_all(&out).unwrap();
        let path = out.join("page-manifest.json");
        fs::write(
            &path,
            r#"{"schema":"ores.web.page-manifest/v1","generatedBy":"someone-else","generatorVersion":"1","routeRoot":"src/pages","manifestSha256":"0000000000000000000000000000000000000000000000000000000000000000","pages":[]}"#,
        )
        .unwrap();
        assert!(matches!(
            sync_web_page_docs(&root, &build(), Path::new("generated/web"), false),
            Err(WebPageDocProjectionError::Ownership { .. })
        ));
        assert!(fs::read_to_string(path).unwrap().contains("someone-else"));
        let _ = fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn symlinked_output_parent_is_refused() {
        use std::os::unix::fs::symlink;
        let root = temp_root("symlink-parent");
        let outside = temp_root("outside");
        fs::create_dir_all(root.join("generated")).unwrap();
        symlink(&outside, root.join("generated/web")).unwrap();
        assert!(matches!(
            sync_web_page_docs(&root, &build(), Path::new("generated/web"), false),
            Err(WebPageDocProjectionError::Ownership { .. })
        ));
        let _ = fs::remove_dir_all(root);
        let _ = fs::remove_dir_all(outside);
    }
}
