use crate::{fs_codegen::module_ident, FsRoute, FsRouteKind};

/// Marker written at the top of generated web-page `lambda.rs` files.
pub const GENERATED_PAGE_LAMBDA_MARKER: &str =
    "// @generated by ores-api-docs for a *-web-server.rs page; DO NOT EDIT.";

/// Stable Cargo alias for the owning web-server library crate. `ores-stack`
/// points it at the product crate in the generated build-unit manifest, so the
/// generated source never names an organization.
pub const PAGE_LAMBDA_WEB_APP_ALIAS: &str = "ores_web_app";

/// Stable Cargo alias for the organization's `*-lambdas` provider runtime.
pub const PAGE_LAMBDA_RUNTIME_ALIAS: &str = "ores_page_lambda_runtime";

/// Generate one provider-neutral executable source file for a browser page.
///
/// The same sibling `lambda.rs` is compiled twice (or more) with a mutually
/// exclusive provider feature selected by the generated `ores-stack` build
/// manifest. This keeps `src/pages/**/lambda.rs` 1:1 with `page.rs` while
/// allowing the artifact to target both AWS and GCP.
///
/// `lambda.rs` is a separate bin crate root, so it must not mount `page.rs`
/// with `#[path]`: every `crate::` reference inside the page would then resolve
/// against the Lambda bin instead of the web server. The page is reached
/// through the web-server library instead, which must expose
///
/// - `pub mod ores_pages` containing the [`crate::page_compile_glue`] /
///   [`crate::page_router_glue`] output, and
/// - `pub async fn ores_page_lambda_state()` building the same application
///   state the standalone Axum server hands to `PageContext::with_state`.
///
/// This is intentionally a **web-page** projection. It never imports RPC
/// dispatch code, never generates `rpc.rs`, and never turns the page into an
/// api-docs operation. `ores-stack` owns when/where this file is materialized.
pub fn page_lambda_glue(route: &FsRoute) -> Result<String, String> {
    if route.kind != FsRouteKind::Page {
        return Err("page_lambda_glue accepts only src/pages/**/page.rs routes".to_owned());
    }

    let canonical_path = route.canonical_path();
    let axum_paths = route.axum_paths();
    let module = module_ident("page", &route.source);
    let app = PAGE_LAMBDA_WEB_APP_ALIAS;
    let runtime = PAGE_LAMBDA_RUNTIME_ALIAS;

    let mut out = String::new();
    out.push_str(GENERATED_PAGE_LAMBDA_MARKER);
    out.push('\n');
    out.push_str("// WEB SERVER PAGE LAMBDA ONLY — not an API-server RPC adapter.\n\n");
    out.push_str(&format!(
        "use ::{app}::ores_pages::{module} as __ores_page;\n\n"
    ));
    out.push_str(&format!(
        "pub const ORES_PAGE_SOURCE: &str = {:?};\npub const ORES_PAGE_ROUTE: &str = {:?};\npub const ORES_PAGE_AXUM_PATHS: &[&str] = &[{}];\n\n",
        route.source,
        canonical_path,
        axum_paths
            .iter()
            .map(|path| format!("{path:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str(&format!(
        "async fn __ores_handle_page(\n    state: ::ores_api_docs_client::PageState,\n    request: ::{runtime}::PageHttpRequest,\n) -> Result<::{runtime}::PageHttpResponse, ::{runtime}::RuntimeError> {{\n    ::{runtime}::invoke_page(\n        request,\n        state,\n        ORES_PAGE_ROUTE,\n        ORES_PAGE_AXUM_PATHS,\n        |ctx| __ores_page::__ores_page_boxed(ctx),\n    ).await\n}}\n\n"
    ));
    out.push_str(
        "#[cfg(all(feature = \"ores-page-lambda-aws\", feature = \"ores-page-lambda-gcp\"))]\ncompile_error!(\"generated page lambda provider features are mutually exclusive\");\n\n",
    );
    out.push_str(
        "#[cfg(all(not(feature = \"ores-page-lambda-aws\"), not(feature = \"ores-page-lambda-gcp\")))]\ncompile_error!(\"generated page lambda requires exactly one provider feature: ores-page-lambda-aws or ores-page-lambda-gcp\");\n\n",
    );
    for provider in ["aws", "gcp"] {
        let other = if provider == "aws" { "gcp" } else { "aws" };
        out.push_str(&format!(
            "#[cfg(all(feature = \"ores-page-lambda-{provider}\", not(feature = \"ores-page-lambda-{other}\")))]\n#[tokio::main]\nasync fn main() -> Result<(), ::{runtime}::RuntimeError> {{\n    let state = ::{app}::ores_page_lambda_state()\n        .await\n        .map_err(::{runtime}::RuntimeError::state_init)?;\n    ::{runtime}::{provider}::run_page(state, __ores_handle_page).await\n}}\n"
        ));
        if provider == "aws" {
            out.push('\n');
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_one_web_only_source_for_aws_and_gcp() {
        let route = FsRoute::page("src/pages/users/[id]/page.rs").expect("page route");
        let source = page_lambda_glue(&route).expect("lambda source");
        assert!(source.starts_with(GENERATED_PAGE_LAMBDA_MARKER));
        assert!(source.contains("WEB SERVER PAGE LAMBDA ONLY"));
        assert!(source.contains("ORES_PAGE_ROUTE: &str = \"/users/{id}\""));
        assert!(source.contains("ores-page-lambda-aws"));
        assert!(source.contains("ores-page-lambda-gcp"));
        assert!(source.contains("ores_page_lambda_runtime::aws::run_page"));
        assert!(source.contains("ores_page_lambda_runtime::gcp::run_page"));
        assert!(source.contains("provider features are mutually exclusive"));
        assert!(!source.contains("rpc.rs"));
        assert!(!source.contains("RpcV1"));
    }

    #[test]
    fn reaches_the_page_through_the_web_server_library() {
        let route = FsRoute::page("src/pages/users/[id]/page.rs").expect("page route");
        let source = page_lambda_glue(&route).expect("lambda source");
        // A bin crate root must not re-mount page.rs: `crate::` inside the page
        // would stop meaning the web server.
        assert!(!source.contains("#[path"));
        assert!(source.contains(
            "use ::ores_web_app::ores_pages::__ores_page_src_pages_users__id__page_rs as __ores_page;"
        ));
        assert_eq!(
            source
                .matches("::ores_web_app::ores_page_lambda_state()")
                .count(),
            2
        );
        assert_eq!(source.matches("async fn main()").count(), 2);
    }

    #[test]
    fn output_is_deterministic() {
        let route = FsRoute::page("src/pages/page.rs").expect("page route");
        assert_eq!(page_lambda_glue(&route), page_lambda_glue(&route));
    }

    #[test]
    fn preserves_optional_catch_all_projection() {
        let route = FsRoute::page("src/pages/docs/[[...slug]]/page.rs").expect("page route");
        let source = page_lambda_glue(&route).expect("lambda source");
        assert!(source.contains("\"/docs\", \"/docs/{*slug}\""));
    }

    #[test]
    fn refuses_api_routes() {
        let route = FsRoute::api_handler("src/routes/v1/health/route.rs").expect("api route");
        let error = page_lambda_glue(&route).expect_err("must refuse api");
        assert!(error.contains("only src/pages/**/page.rs"));
    }
}
