//! Deterministic generated documentation for the admitted web-page manifest.
//!
//! The semantic manifest model lives in [`crate::page_layout::manifest`]. This
//! module is only the generated-output projection/ownership boundary: JSON,
//! Markdown and HTML all consume the exact same admitted manifest value.

use crate::{
    page_layout::manifest::{
        web_page_manifest, WebPageManifest, WebPageManifestError, WEB_PAGE_MANIFEST_GENERATOR,
        WEB_PAGE_MANIFEST_SCHEMA,
    },
    PageBuildManifest,
};
use std::{
    fs::{self, OpenOptions},
    io::Write,
    path::{Component, Path, PathBuf},
    process,
    time::{SystemTime, UNIX_EPOCH},
};
use thiserror::Error;

pub const WEB_PAGE_DOCS_MARKER: &str =
    "<!-- @generated by ores-api-docs page docs; do not edit -->";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WebPageDocsOutputs {
    pub manifest_path: PathBuf,
    pub markdown_path: PathBuf,
    pub html_path: PathBuf,
}

#[derive(Debug, Error)]
pub enum WebPageDocsError {
    #[error(transparent)]
    Manifest(#[from] WebPageManifestError),
    #[error("I/O at {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },
    #[error("JSON: {0}")]
    Json(#[from] serde_json::Error),
    #[error("generated output ownership refused at {path}: {reason}")]
    Ownership { path: String, reason: String },
    #[error("generated output drift at {path}")]
    Drift { path: String },
}

#[must_use]
pub fn render_web_page_docs_markdown(manifest: &WebPageManifest) -> String {
    let mut out = String::new();
    out.push_str(WEB_PAGE_DOCS_MARKER);
    out.push_str("\n# Web pages\n\n");
    out.push_str(&format!(
        "Manifest: `{}` · generator: `{}` `{}` · digest: `{}`\n\n",
        manifest.schema,
        manifest.generated_by,
        manifest.generator_version,
        manifest.manifest_sha256
    ));
    out.push_str(
        "| URL | Page source | Render identity | Layouts | Generator | Render | Auth | RPC dependencies |\n",
    );
    out.push_str("| --- | --- | --- | --- | --- | --- | --- | --- |\n");
    for page in &manifest.pages {
        let layouts = if page.layout_sources.is_empty() {
            "—".to_owned()
        } else {
            page.layout_sources
                .iter()
                .map(|source| source.source.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        };
        let generator = page
            .generator_source
            .as_ref()
            .map(|source| source.source.as_str())
            .unwrap_or("—");
        let rpc = if page.rpc_dependencies.is_empty() {
            "—".to_owned()
        } else {
            page.rpc_dependencies.join(", ")
        };
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} | `{}` | `{}` / `{}` | `{}` | {} |\n",
            markdown_cell(&page.canonical_url),
            markdown_cell(&page.source_page_rs),
            markdown_cell(&page.render_sha256),
            markdown_cell(&layouts),
            markdown_cell(generator),
            markdown_cell(&page.renderer),
            markdown_cell(&page.render_mode),
            markdown_cell(&page.auth),
            markdown_cell(&rpc),
        ));
    }
    out
}

#[must_use]
pub fn render_web_page_docs_html(manifest: &WebPageManifest) -> String {
    let mut rows = String::new();
    for page in &manifest.pages {
        let layouts = if page.layout_sources.is_empty() {
            "—".to_owned()
        } else {
            page.layout_sources
                .iter()
                .map(|source| source.source.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        };
        let generator = page
            .generator_source
            .as_ref()
            .map(|source| source.source.as_str())
            .unwrap_or("—");
        let rpc = if page.rpc_dependencies.is_empty() {
            "—".to_owned()
        } else {
            page.rpc_dependencies.join(", ")
        };
        let render = format!("{} / {}", page.renderer, page.render_mode);
        rows.push_str("<tr>");
        for value in [
            page.canonical_url.as_str(),
            page.source_page_rs.as_str(),
            page.render_sha256.as_str(),
            layouts.as_str(),
            generator,
            render.as_str(),
            page.auth.as_str(),
            rpc.as_str(),
        ] {
            rows.push_str("<td><code>");
            rows.push_str(&html_escape(value));
            rows.push_str("</code></td>");
        }
        rows.push_str("</tr>\n");
    }
    format!(
        "{marker}\n<!doctype html>\n<meta charset=\"utf-8\">\n<title>Web pages</title>\n<h1>Web pages</h1>\n<p>Manifest <code>{schema}</code> · generator <code>{generator}</code> <code>{version}</code> · digest <code>{digest}</code></p>\n<table><thead><tr><th>URL</th><th>Page source</th><th>Render identity</th><th>Layouts</th><th>Generator</th><th>Render</th><th>Auth</th><th>RPC dependencies</th></tr></thead><tbody>\n{rows}</tbody></table>\n",
        marker = WEB_PAGE_DOCS_MARKER,
        schema = html_escape(&manifest.schema),
        generator = html_escape(&manifest.generated_by),
        version = html_escape(&manifest.generator_version),
        digest = html_escape(&manifest.manifest_sha256),
    )
}

pub fn sync_web_page_docs(
    repo_root: &Path,
    build: &PageBuildManifest,
    out_dir: &Path,
    check: bool,
) -> Result<WebPageDocsOutputs, WebPageDocsError> {
    let root = fs::canonicalize(repo_root).map_err(|source| WebPageDocsError::Io {
        path: repo_root.display().to_string(),
        source,
    })?;
    let out_dir = if out_dir.is_absolute() {
        out_dir.to_path_buf()
    } else {
        root.join(out_dir)
    };
    verify_confined_path(&root, &out_dir, false)?;

    let manifest = web_page_manifest(&root, build)?;
    let mut manifest_bytes = serde_json::to_vec_pretty(&manifest)?;
    manifest_bytes.push(b'\n');
    let markdown = render_web_page_docs_markdown(&manifest).into_bytes();
    let html = render_web_page_docs_html(&manifest).into_bytes();

    let manifest_path = out_dir.join("page-manifest.json");
    let markdown_path = out_dir.join("pages.md");
    let html_path = out_dir.join("pages.html");

    sync_owned_file(
        &root,
        &manifest_path,
        &manifest_bytes,
        check,
        OutputKind::Manifest,
    )?;
    sync_owned_file(
        &root,
        &markdown_path,
        &markdown,
        check,
        OutputKind::MarkedText,
    )?;
    sync_owned_file(&root, &html_path, &html, check, OutputKind::MarkedText)?;

    Ok(WebPageDocsOutputs {
        manifest_path,
        markdown_path,
        html_path,
    })
}

#[derive(Clone, Copy)]
enum OutputKind {
    Manifest,
    MarkedText,
}

fn sync_owned_file(
    root: &Path,
    path: &Path,
    expected: &[u8],
    check: bool,
    kind: OutputKind,
) -> Result<(), WebPageDocsError> {
    verify_confined_path(root, path, true)?;
    if check {
        let actual = fs::read(path).map_err(|source| WebPageDocsError::Io {
            path: path.display().to_string(),
            source,
        })?;
        if actual != expected {
            return Err(WebPageDocsError::Drift {
                path: path.display().to_string(),
            });
        }
        return Ok(());
    }

    ensure_confined_parent_dirs(root, path)?;
    verify_confined_path(root, path, true)?;
    let existing_permissions = verify_owned_destination(path, kind)?;

    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("page-docs");
    let temp = path.with_file_name(format!(".{file_name}.ores-tmp-{}-{nonce:x}", process::id()));
    verify_confined_path(root, &temp, true)?;
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&temp)
        .map_err(|source| WebPageDocsError::Io {
            path: temp.display().to_string(),
            source,
        })?;
    if let Some(permissions) = existing_permissions {
        if let Err(source) = file.set_permissions(permissions) {
            let _ = fs::remove_file(&temp);
            return Err(WebPageDocsError::Io {
                path: temp.display().to_string(),
                source,
            });
        }
    }
    if let Err(source) = file.write_all(expected).and_then(|_| file.sync_all()) {
        let _ = fs::remove_file(&temp);
        return Err(WebPageDocsError::Io {
            path: temp.display().to_string(),
            source,
        });
    }
    drop(file);

    if let Err(error) =
        verify_confined_path(root, path, true).and_then(|_| verify_owned_destination(path, kind).map(|_| ()))
    {
        let _ = fs::remove_file(&temp);
        return Err(error);
    }
    if let Err(source) = fs::rename(&temp, path) {
        let _ = fs::remove_file(&temp);
        return Err(WebPageDocsError::Io {
            path: path.display().to_string(),
            source,
        });
    }
    Ok(())
}

fn confined_relative<'a>(root: &Path, path: &'a Path) -> Result<&'a Path, WebPageDocsError> {
    let relative = path
        .strip_prefix(root)
        .map_err(|_| WebPageDocsError::Ownership {
            path: path.display().to_string(),
            reason: format!("output escapes repository root {}", root.display()),
        })?;
    if relative.as_os_str().is_empty()
        || relative.components().any(|component| {
            matches!(
                component,
                Component::ParentDir | Component::RootDir | Component::Prefix(_)
            )
        })
    {
        return Err(WebPageDocsError::Ownership {
            path: path.display().to_string(),
            reason: "output path must be a normalized child of the repository root".to_owned(),
        });
    }
    Ok(relative)
}

fn verify_confined_path(
    root: &Path,
    path: &Path,
    leaf_may_be_file: bool,
) -> Result<(), WebPageDocsError> {
    let relative = confined_relative(root, path)?;
    let mut current = root.to_path_buf();
    let components = relative.components().collect::<Vec<_>>();
    for (index, component) in components.iter().enumerate() {
        let Component::Normal(segment) = component else {
            return Err(WebPageDocsError::Ownership {
                path: path.display().to_string(),
                reason: "output path contains a non-normal component".to_owned(),
            });
        };
        current.push(segment);
        match fs::symlink_metadata(&current) {
            Ok(metadata) => {
                if metadata.file_type().is_symlink() {
                    return Err(WebPageDocsError::Ownership {
                        path: current.display().to_string(),
                        reason: "output path traverses a symlink".to_owned(),
                    });
                }
                let is_leaf = index + 1 == components.len();
                if (!is_leaf || !leaf_may_be_file) && !metadata.is_dir() {
                    return Err(WebPageDocsError::Ownership {
                        path: current.display().to_string(),
                        reason: "output parent component is not a directory".to_owned(),
                    });
                }
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => break,
            Err(source) => {
                return Err(WebPageDocsError::Io {
                    path: current.display().to_string(),
                    source,
                })
            }
        }
    }
    Ok(())
}

fn ensure_confined_parent_dirs(root: &Path, path: &Path) -> Result<(), WebPageDocsError> {
    let parent = path.parent().ok_or_else(|| WebPageDocsError::Ownership {
        path: path.display().to_string(),
        reason: "generated output has no parent directory".to_owned(),
    })?;
    let relative = confined_relative(root, parent)?;
    let mut current = root.to_path_buf();
    for component in relative.components() {
        let Component::Normal(segment) = component else {
            return Err(WebPageDocsError::Ownership {
                path: parent.display().to_string(),
                reason: "output parent contains a non-normal component".to_owned(),
            });
        };
        current.push(segment);
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(WebPageDocsError::Ownership {
                    path: current.display().to_string(),
                    reason: "output parent traverses a symlink".to_owned(),
                });
            }
            Ok(metadata) if !metadata.is_dir() => {
                return Err(WebPageDocsError::Ownership {
                    path: current.display().to_string(),
                    reason: "output parent component is not a directory".to_owned(),
                });
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                fs::create_dir(&current).map_err(|source| WebPageDocsError::Io {
                    path: current.display().to_string(),
                    source,
                })?;
                let metadata = fs::symlink_metadata(&current).map_err(|source| WebPageDocsError::Io {
                    path: current.display().to_string(),
                    source,
                })?;
                if metadata.file_type().is_symlink() || !metadata.is_dir() {
                    return Err(WebPageDocsError::Ownership {
                        path: current.display().to_string(),
                        reason: "new output parent is not a real directory".to_owned(),
                    });
                }
            }
            Err(source) => {
                return Err(WebPageDocsError::Io {
                    path: current.display().to_string(),
                    source,
                })
            }
        }
    }
    Ok(())
}

fn verify_owned_destination(
    path: &Path,
    kind: OutputKind,
) -> Result<Option<fs::Permissions>, WebPageDocsError> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(source) => {
            return Err(WebPageDocsError::Io {
                path: path.display().to_string(),
                source,
            })
        }
    };
    if metadata.file_type().is_symlink() || !metadata.file_type().is_file() {
        return Err(WebPageDocsError::Ownership {
            path: path.display().to_string(),
            reason: "destination must be a regular generated file".to_owned(),
        });
    }
    let bytes = fs::read(path).map_err(|source| WebPageDocsError::Io {
        path: path.display().to_string(),
        source,
    })?;
    let owned = match kind {
        OutputKind::MarkedText => has_exact_text_marker(&bytes),
        OutputKind::Manifest => manifest_is_owned(&bytes),
    };
    if !owned {
        return Err(WebPageDocsError::Ownership {
            path: path.display().to_string(),
            reason: "existing file is not owned by the web page docs generator".to_owned(),
        });
    }
    Ok(Some(metadata.permissions()))
}

fn has_exact_text_marker(bytes: &[u8]) -> bool {
    let first_line = bytes.split(|byte| *byte == b'\n').next().unwrap_or(bytes);
    let first_line = first_line.strip_suffix(b"\r").unwrap_or(first_line);
    first_line == WEB_PAGE_DOCS_MARKER.as_bytes()
}

fn manifest_is_owned(bytes: &[u8]) -> bool {
    let Ok(value) = serde_json::from_slice::<serde_json::Value>(bytes) else {
        return false;
    };
    value.get("schema").and_then(serde_json::Value::as_str) == Some(WEB_PAGE_MANIFEST_SCHEMA)
        && value
            .get("generatedBy")
            .and_then(serde_json::Value::as_str)
            == Some(WEB_PAGE_MANIFEST_GENERATOR)
}

fn markdown_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn html_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::PageBuildRoute;

    fn temp_root(label: &str) -> PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock after epoch")
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "ores-api-docs-page-docs-{label}-{}-{unique}",
            process::id()
        ));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).expect("fixture root");
        root
    }

    fn fixture(root: &Path) -> PageBuildManifest {
        let page_dir = root.join("src/pages/users/[id]");
        fs::create_dir_all(&page_dir).unwrap();
        fs::write(root.join("src/pages/layout.rs"), "// root layout v1\n").unwrap();
        fs::write(page_dir.join("page.rs"), "pub async fn page() {}\n").unwrap();
        fs::write(
            page_dir.join("gen.rs"),
            "pub async fn generate_static_params() {}\n",
        )
        .unwrap();
        PageBuildManifest {
            schema_version: "1.2.0".to_owned(),
            route_root: "src/pages".to_owned(),
            wasm_have_header: "x-ores-wasm-have".to_owned(),
            wasm_have_cookie: "ores_wasm_have".to_owned(),
            routes: vec![PageBuildRoute {
                source: "src/pages/users/[id]/page.rs".to_owned(),
                generator: Some("src/pages/users/[id]/gen.rs".to_owned()),
                canonical_path: "/users/{id}".to_owned(),
                axum_paths: vec!["/users/{id}".to_owned()],
                dioxus_paths: vec!["/users/:id".to_owned()],
                renderer: "leptos".to_owned(),
                delivery: "ssr_only".to_owned(),
                render: "static_with_fallback".to_owned(),
                revalidate_secs: Some(60),
                on_demand: None,
                title: Some("User".to_owned()),
                summary: None,
                auth: "session".to_owned(),
                stability: "stable".to_owned(),
                database: "read_only".to_owned(),
                features: vec!["users".to_owned()],
                data_sources: vec![
                    "rpc:demo.users.find".to_owned(),
                    "orm:user_read".to_owned(),
                ],
                tags: vec!["account".to_owned()],
                css: None,
                wasm: None,
            }],
        }
    }

    #[test]
    fn docs_expose_render_chain_identity_and_rpc_dependencies() {
        let root = temp_root("render-chain");
        let manifest = web_page_manifest(&root, &fixture(&root)).unwrap();
        let markdown = render_web_page_docs_markdown(&manifest);
        assert!(markdown.contains(&manifest.pages[0].render_sha256));
        assert!(markdown.contains("src/pages/layout.rs"));
        assert!(markdown.contains("src/pages/users/[id]/gen.rs"));
        assert!(markdown.contains("demo.users.find"));
        assert!(!markdown.contains("rpcOperations"));
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn projection_is_deterministic_and_check_mode_is_read_only() {
        let root = temp_root("deterministic");
        let build = fixture(&root);
        let out = root.join("generated/web");
        sync_web_page_docs(&root, &build, &out, false).unwrap();
        let first = fs::read(out.join("page-manifest.json")).unwrap();
        sync_web_page_docs(&root, &build, &out, true).unwrap();
        let second = fs::read(out.join("page-manifest.json")).unwrap();
        assert_eq!(first, second);
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn json_ownership_requires_schema_and_fixed_generator_identity() {
        let root = temp_root("json-owner");
        let build = fixture(&root);
        let out = root.join("generated/web");
        fs::create_dir_all(&out).unwrap();
        fs::write(
            out.join("page-manifest.json"),
            format!(
                "{{\"schema\":{schema:?},\"generatedBy\":\"someone-else\"}}\n",
                schema = WEB_PAGE_MANIFEST_SCHEMA
            ),
        )
        .unwrap();
        let error = sync_web_page_docs(&root, &build, &out, false).unwrap_err();
        assert!(matches!(error, WebPageDocsError::Ownership { .. }));
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn text_ownership_requires_exact_first_line_marker() {
        assert!(has_exact_text_marker(format!("{WEB_PAGE_DOCS_MARKER}\nbody").as_bytes()));
        assert!(has_exact_text_marker(format!("{WEB_PAGE_DOCS_MARKER}\r\nbody").as_bytes()));
        assert!(!has_exact_text_marker(format!("{WEB_PAGE_DOCS_MARKER}evil\n").as_bytes()));
        assert!(!has_exact_text_marker(format!("{WEB_PAGE_DOCS_MARKER} \n").as_bytes()));
    }

    #[test]
    fn refuses_authored_output_and_symlink_destination() {
        let root = temp_root("ownership");
        let build = fixture(&root);
        let out = root.join("generated/web");
        fs::create_dir_all(&out).unwrap();
        fs::write(out.join("pages.md"), "authored\n").unwrap();
        let error = sync_web_page_docs(&root, &build, &out, false).unwrap_err();
        assert!(matches!(error, WebPageDocsError::Ownership { .. }));

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            fs::remove_file(out.join("pages.md")).unwrap();
            fs::write(out.join("target"), WEB_PAGE_DOCS_MARKER).unwrap();
            symlink(out.join("target"), out.join("pages.md")).unwrap();
            let error = sync_web_page_docs(&root, &build, &out, false).unwrap_err();
            assert!(matches!(error, WebPageDocsError::Ownership { .. }));
        }
        fs::remove_dir_all(root).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn refuses_symlinked_parent_and_never_writes_outside_repo() {
        use std::os::unix::fs::symlink;

        let root = temp_root("parent-symlink");
        let build = fixture(&root);
        let outside = temp_root("outside");
        fs::create_dir_all(root.join("generated")).unwrap();
        symlink(&outside, root.join("generated/web")).unwrap();

        let error = sync_web_page_docs(&root, &build, &root.join("generated/web"), false)
            .expect_err("symlinked output parent must fail closed");
        assert!(matches!(error, WebPageDocsError::Ownership { .. }));
        assert!(!outside.join("page-manifest.json").exists());
        assert!(!outside.join("pages.md").exists());
        assert!(!outside.join("pages.html").exists());

        fs::remove_dir_all(root).unwrap();
        fs::remove_dir_all(outside).unwrap();
    }
}
