use crate::{project::sha256_hex, FsRoute, FsRouteKind};

/// Marker written at the top of generated web-page `lambda.rs` files.
pub const GENERATED_PAGE_LAMBDA_MARKER: &str =
    "// @generated by ores-api-docs for a *-web-server.rs page; DO NOT EDIT.";

/// Stable Cargo alias for the owning web-server library crate. `ores-stack`
/// points it at the product crate in generated build manifests, so generated
/// source never names an organization.
pub const PAGE_LAMBDA_WEB_APP_ALIAS: &str = "ores_web_app";

/// Module the web-server library must export with the generated page glue.
pub const PAGE_LAMBDA_PAGES_MODULE: &str = "ores_pages";

/// Function the web-server library must export, typed
/// `ores_api_docs_client::PageLambdaStateFn`.
pub const PAGE_LAMBDA_STATE_FN: &str = "ores_page_lambda_state";

fn page_lambda_symbol_ident(kind: &str, source: &str) -> String {
    let mut out = format!("__ores_{kind}_");
    for ch in source.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    out.push('_');
    out.push_str(&sha256_hex(source.as_bytes())[..16]);
    out
}

pub fn page_lambda_entry_ident(source: &str) -> String {
    page_lambda_symbol_ident("invoke_page", source)
}

pub fn page_lambda_finalize_ident(source: &str) -> String {
    page_lambda_symbol_ident("finalize_page", source)
}

/// Generate one provider-neutral page-function module.
///
/// The sibling `lambda.rs` is deliberately not an AWS/GCP executable. It owns
/// the stable server-side function ABI and metadata only. `ores-stack` generates
/// provider-specific `main.rs` wrappers into an ignored `*-lambdas/build/`
/// tree, and server-side conformance uses the same wrapper generator in a temp
/// directory. This keeps the page function testable in the web-server repo while
/// keeping provider runtime ownership in `*-lambdas`.
///
/// Exactly one page function is represented here. Optional catch-all routing may
/// yield multiple HTTP path templates, but they still enter this same page.
pub fn page_lambda_glue(route: &FsRoute) -> Result<String, String> {
    if route.kind != FsRouteKind::Page {
        return Err("page_lambda_glue accepts only src/pages/**/page.rs routes".to_owned());
    }

    let canonical_path = route.canonical_path();
    let axum_paths = route.axum_paths();
    let app = PAGE_LAMBDA_WEB_APP_ALIAS;
    let entry = format!(
        "::{app}::{PAGE_LAMBDA_PAGES_MODULE}::{}",
        page_lambda_entry_ident(&route.source)
    );
    let finalize = format!(
        "::{app}::{PAGE_LAMBDA_PAGES_MODULE}::{}",
        page_lambda_finalize_ident(&route.source)
    );
    let state_fn = format!("::{app}::{PAGE_LAMBDA_STATE_FN}");

    let mut out = String::new();
    out.push_str(GENERATED_PAGE_LAMBDA_MARKER);
    out.push('\n');
    out.push_str("// WEB SERVER PAGE LAMBDA MODULE ONLY — provider main() is generated elsewhere.\n");
    out.push_str("// No RPC surface is introduced by this file.\n\n");
    out.push_str(&format!(
        "pub const ORES_PAGE_SOURCE: &str = {:?};\npub const ORES_PAGE_ROUTE: &str = {:?};\npub const ORES_PAGE_AXUM_PATHS: &[&str] = &[{}];\n\n",
        route.source,
        canonical_path,
        axum_paths
            .iter()
            .map(|path| format!("{path:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str(&format!(
        "const __ORES_PAGE: ::ores_api_docs_client::PageFn = {entry};\n\
         const __ORES_PAGE_FINALIZE: ::ores_api_docs_client::PageFinalizeFn = {finalize};\n\
         const __ORES_PAGE_STATE: ::ores_api_docs_client::PageLambdaStateFn = {state_fn};\n\n"
    ));
    out.push_str(
        "/// Build the product web-server state once per provider cold start.\n\
         pub async fn init_state() -> Result<\n    ::ores_api_docs_client::PageState,\n    ::ores_api_docs_client::PageLambdaStateError,\n> {\n    __ORES_PAGE_STATE().await\n}\n\n",
    );
    out.push_str(
        "/// Execute this one page and apply the same admitted response finalizer\n\
         /// used by the standalone web server. Provider wrappers own request\n\
         /// normalization and response-envelope conversion only.\n\
         pub async fn run(\n    context: ::ores_api_docs_client::PageContext,\n    hints: ::ores_api_docs_client::PageResponseRequestHints<'_>,\n) -> ::ores_api_docs_client::FinalizedPageResponse {\n    let result = __ORES_PAGE(context).await;\n    __ORES_PAGE_FINALIZE(result, hints)\n}\n",
    );
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_one_provider_neutral_web_page_function() {
        let route = FsRoute::page("src/pages/users/[id]/page.rs").expect("page route");
        let source = page_lambda_glue(&route).expect("lambda source");
        assert!(source.starts_with(GENERATED_PAGE_LAMBDA_MARKER));
        assert!(source.contains("ORES_PAGE_ROUTE: &str = \"/users/{id}\""));
        assert!(source.contains("pub async fn init_state()"));
        assert!(source.contains("pub async fn run("));
        assert!(!source.contains("fn main()"));
        assert!(!source.contains("ores_page_lambda_runtime"));
        assert!(!source.contains("ores-page-lambda-aws"));
        assert!(!source.contains("ores-page-lambda-gcp"));
        assert!(!source.contains("rpc.rs"));
        assert!(!source.contains("RpcV1"));
    }

    #[test]
    fn reaches_the_page_only_through_typed_library_trampolines() {
        let route = FsRoute::page("src/pages/users/[id]/page.rs").expect("page route");
        let source = page_lambda_glue(&route).expect("lambda source");
        assert!(!source.contains("#[path"));
        assert!(!source.contains("__ores_page_boxed"));
        let entry = page_lambda_entry_ident("src/pages/users/[id]/page.rs");
        let finalize = page_lambda_finalize_ident("src/pages/users/[id]/page.rs");
        assert!(source.contains(&format!(
            "const __ORES_PAGE: ::ores_api_docs_client::PageFn = ::ores_web_app::ores_pages::{entry};"
        )));
        assert!(source.contains(&format!(
            "const __ORES_PAGE_FINALIZE: ::ores_api_docs_client::PageFinalizeFn = ::ores_web_app::ores_pages::{finalize};"
        )));
    }

    #[test]
    fn exported_identifiers_are_injective_where_readable_parts_collide() {
        for make in [
            page_lambda_entry_ident as fn(&str) -> String,
            page_lambda_finalize_ident as fn(&str) -> String,
        ] {
            let dash = make("src/pages/a-b/page.rs");
            let underscore = make("src/pages/a_b/page.rs");
            let nested = make("src/pages/a/b/page.rs");
            assert_ne!(dash, underscore);
            assert_ne!(dash, nested);
            assert_ne!(underscore, nested);
            assert_eq!(dash[..dash.len() - 16], underscore[..underscore.len() - 16]);
            assert!(dash
                .chars()
                .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_'));
            assert_eq!(dash, make("src/pages/a-b/page.rs"));
        }
    }

    #[test]
    fn output_is_deterministic() {
        let route = FsRoute::page("src/pages/page.rs").expect("page route");
        assert_eq!(page_lambda_glue(&route), page_lambda_glue(&route));
    }

    #[test]
    fn preserves_optional_catch_all_projection_as_one_page_function() {
        let route = FsRoute::page("src/pages/docs/[[...slug]]/page.rs").expect("page route");
        let source = page_lambda_glue(&route).expect("lambda source");
        assert!(source.contains("\"/docs\", \"/docs/{*slug}\""));
        assert_eq!(source.matches("pub async fn run(").count(), 1);
    }

    #[test]
    fn refuses_api_routes() {
        let route = FsRoute::api_handler("src/routes/v1/health/route.rs").expect("api route");
        let error = page_lambda_glue(&route).expect_err("must refuse api");
        assert!(error.contains("only src/pages/**/page.rs"));
    }
}
