//! Rust projection from an authoritative `RouteMap` into the reusable
//! `ores-rpc-calls-http-tcp-pool` transport traits.
//!
//! The route map and generated DTO module remain the authority. This module
//! emits only transport marker types/impls, so HTTP/TCP connection reuse never
//! becomes a second schema source.

use crate::{RouteEntry, RouteMap};

/// Emit companion Rust source that binds generated route DTOs to
/// `ores-rpc-calls-http-tcp-pool`.
///
/// `dto_module` is a Rust path such as `crate::interfaces::canonical_api`.
/// The companion source expects the normal api-docs generated naming convention
/// (`FooPath`, `FooQuery`, `FooHeaders`, `FooRequest`, `FooResponse`).
pub fn rpc_pool_bindings(map: &RouteMap, dto_module: &str) -> Result<String, String> {
    if dto_module.trim().is_empty() {
        return Err("dto_module must not be empty".to_owned());
    }
    let mut out = String::from(
        "// @generated by ores-api-docs rpc_pool_bindings; do not edit\n\
         // RouteMap + generated DTOs remain authoritative.\n\n",
    );

    for (key, entry) in &map.map {
        emit_operation(&mut out, &map.service, key, entry, dto_module)?;
    }
    Ok(out)
}

fn emit_operation(
    out: &mut String,
    service: &str,
    key: &str,
    entry: &RouteEntry,
    dto_module: &str,
) -> Result<(), String> {
    let name = pascal(key);
    if name.is_empty() {
        return Err(format!("route key {key:?} cannot form a Rust marker name"));
    }
    let marker = format!("{name}Call");
    let path_ty = projected_type(dto_module, &name, "Path", entry.path_params.as_ref(), "()");
    let query_ty = projected_type(
        dto_module,
        &name,
        "Query",
        entry.query_schema.as_ref(),
        "()",
    );
    let headers_ty = projected_type(
        dto_module,
        &name,
        "Headers",
        entry.header_schema.as_ref(),
        "()",
    );
    let body_ty = projected_type(
        dto_module,
        &name,
        "Request",
        entry.request_schema.as_ref(),
        "()",
    );
    let response_ty = projected_type(
        dto_module,
        &name,
        "Response",
        entry.response_schema.as_ref(),
        "::serde_json::Value",
    );
    let rpc_key = entry
        .rpc_key
        .as_deref()
        .map(|value| format!("Some({value:?})"))
        .unwrap_or_else(|| "None".to_owned());
    let has_body = entry.request_schema.is_some();

    out.push_str(&format!(
        "#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]\n\
         pub struct {marker};\n\n\
         impl ::ores_rpc_calls_http_tcp_pool::RpcCall for {marker} {{\n\
             type Path = {path_ty};\n\
             type Query = {query_ty};\n\
             type Headers = {headers_ty};\n\
             type Body = {body_ty};\n\
             type Response = {response_ty};\n\n\
             const SERVICE: &'static str = {service:?};\n\
             const KEY: &'static str = {key:?};\n\
             const RPC_KEY: Option<&'static str> = {rpc_key};\n\
             const PATH_TEMPLATE: &'static str = {path:?};\n\
             const HAS_BODY: bool = {has_body};\n\
         }}\n",
        path = entry.path,
    ));

    if entry.transports.iter().any(|value| value == "http") {
        for method in &entry.methods {
            let verb = match method.as_str() {
                "GET" => "Get",
                "POST" => "Post",
                "PUT" => "Put",
                "PATCH" => "Patch",
                "DELETE" => "Delete",
                "HEAD" => "Head",
                "OPTIONS" => "Options",
                other => return Err(format!("{key}: unsupported HTTP method {other}")),
            };
            out.push_str(&format!(
                "impl ::ores_rpc_calls_http_tcp_pool::HttpRpcCall<\
                 ::ores_rpc_calls_http_tcp_pool::{verb}> for {marker} {{}}\n"
            ));
        }
    }
    if entry.transports.iter().any(|value| value == "tcp") {
        let framing = match entry.tcp_framing.as_deref().unwrap_or("ndjson") {
            "ndjson" => "Ndjson",
            "length-prefixed" => "LengthPrefixed",
            other => return Err(format!("{key}: unsupported TCP framing {other}")),
        };
        out.push_str(&format!(
            "impl ::ores_rpc_calls_http_tcp_pool::TcpRpcCall for {marker} {{\n\
                 const FRAMING: ::ores_rpc_calls_http_tcp_pool::TcpFraming =\n\
                     ::ores_rpc_calls_http_tcp_pool::TcpFraming::{framing};\n\
             }}\n"
        ));
    }
    if entry.transports.iter().any(|value| value == "nats") {
        let subject = entry.rpc_key.as_deref().unwrap_or(key);
        out.push_str(&format!(
            "impl ::ores_rpc_calls_http_tcp_pool::NatsRpcCall for {marker} {{\n\
                 const SUBJECT: &'static str = {subject:?};\n\
             }}\n"
        ));
    }
    out.push('\n');
    Ok(())
}

fn projected_type(
    module: &str,
    operation: &str,
    suffix: &str,
    schema: Option<&serde_json::Value>,
    absent: &str,
) -> String {
    match schema {
        None => absent.to_owned(),
        Some(value) if has_nonempty_properties(value) => {
            format!("{module}::{operation}{suffix}")
        }
        Some(_) => "::serde_json::Value".to_owned(),
    }
}

fn has_nonempty_properties(schema: &serde_json::Value) -> bool {
    schema
        .get("properties")
        .and_then(serde_json::Value::as_object)
        .is_some_and(|properties| !properties.is_empty())
}

fn pascal(key: &str) -> String {
    if key.chars().next().is_some_and(char::is_uppercase) && !key.contains('_') {
        return key.to_owned();
    }
    key.replace('-', "_")
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn canonical_route_emits_typed_pool_marker() {
        let map =
            RouteMap::from_json_str(include_str!("../../examples/canonical-api.route-map.json"))
                .expect("canonical map");
        let output = rpc_pool_bindings(&map, "crate::canonical_api").expect("bindings");
        assert!(output.contains("pub struct GetQuoteCall;"));
        assert!(output.contains("type Path = crate::canonical_api::GetQuotePath;"));
        assert!(
            output.contains("HttpRpcCall<::ores_rpc_calls_http_tcp_pool::Get> for GetQuoteCall")
        );
        assert!(
            output.contains("const PATH_TEMPLATE: &'static str = \"/api/v1/quotes/{quoteId}\";")
        );
    }
}
