//! Rust projection from an authoritative `RouteMap` into the reusable
//! `ores-rpc-calls-http-tcp-pool` transport traits.
//!
//! The route map and generated DTO module remain the authority. This module
//! emits only transport marker types/impls, so HTTP/TCP connection reuse never
//! becomes a second schema source.

use crate::{RouteEntry, RouteMap};

/// Emit companion Rust source that binds generated route DTOs to
/// `ores-rpc-calls-http-tcp-pool`.
///
/// `dto_module` is a Rust path such as `crate::interfaces::canonical_api`.
/// Inline route schemas use the normal api-docs generated naming convention
/// (`FooPath`, `FooQuery`, `FooHeaders`, `FooRequest`, `FooResponse`). When an
/// operation deliberately points at an independently authored DTO surface
/// instead of duplicating that schema into the route map, a single body
/// `binding.param_types` entry and/or `binding.return_type` may name the
/// existing DTO. Those names are emitted under `dto_module` and are restricted
/// to simple Rust identifiers so route metadata cannot inject arbitrary source.
pub fn rpc_pool_bindings(map: &RouteMap, dto_module: &str) -> Result<String, String> {
    if dto_module.trim().is_empty() {
        return Err("dto_module must not be empty".to_owned());
    }
    let mut out = String::from(
        "// @generated by ores-api-docs rpc_pool_bindings; do not edit\n\
         // RouteMap + generated DTOs remain authoritative.\n\n",
    );

    for (key, entry) in &map.map {
        emit_operation(&mut out, &map.service, key, entry, dto_module)?;
    }
    Ok(out)
}

fn emit_operation(
    out: &mut String,
    service: &str,
    key: &str,
    entry: &RouteEntry,
    dto_module: &str,
) -> Result<(), String> {
    let name = pascal(key);
    if name.is_empty() {
        return Err(format!("route key {key:?} cannot form a Rust marker name"));
    }
    let marker = format!("{name}Call");
    let path_ty = projected_type(dto_module, &name, "Path", entry.path_params.as_ref(), "()");
    let query_ty = projected_type(
        dto_module,
        &name,
        "Query",
        entry.query_schema.as_ref(),
        "()",
    );
    let headers_ty = projected_type(
        dto_module,
        &name,
        "Headers",
        entry.header_schema.as_ref(),
        "()",
    );
    let body_ty = body_type(entry, dto_module, &name)?;
    let response_ty = response_type(entry, dto_module, &name)?;
    let rpc_key = entry
        .rpc_key
        .as_deref()
        .map(|value| format!("Some({value:?})"))
        .unwrap_or_else(|| "None".to_owned());
    let has_body = body_ty != "()";

    out.push_str(&format!(
        "#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]\n\
         pub struct {marker};\n\n\
         impl ::ores_rpc_calls_http_tcp_pool::RpcCall for {marker} {{\n\
             type Path = {path_ty};\n\
             type Query = {query_ty};\n\
             type Headers = {headers_ty};\n\
             type Body = {body_ty};\n\
             type Response = {response_ty};\n\n\
             const SERVICE: &'static str = {service:?};\n\
             const KEY: &'static str = {key:?};\n\
             const RPC_KEY: Option<&'static str> = {rpc_key};\n\
             const PATH_TEMPLATE: &'static str = {path:?};\n\
             const HAS_BODY: bool = {has_body};\n\
         }}\n",
        path = entry.path,
    ));

    if entry.transports.iter().any(|value| value == "http") {
        for method in &entry.methods {
            let verb = match method.as_str() {
                "GET" => "Get",
                "POST" => "Post",
                "PUT" => "Put",
                "PATCH" => "Patch",
                "DELETE" => "Delete",
                "HEAD" => "Head",
                "OPTIONS" => "Options",
                other => return Err(format!("{key}: unsupported HTTP method {other}")),
            };
            out.push_str(&format!(
                "impl ::ores_rpc_calls_http_tcp_pool::HttpRpcCall<\
                 ::ores_rpc_calls_http_tcp_pool::{verb}> for {marker} {{}}\n"
            ));
        }
    }
    if entry.transports.iter().any(|value| value == "tcp") {
        let framing = match entry.tcp_framing.as_deref().unwrap_or("ndjson") {
            "ndjson" => "Ndjson",
            "length-prefixed" => "LengthPrefixed",
            other => return Err(format!("{key}: unsupported TCP framing {other}")),
        };
        out.push_str(&format!(
            "impl ::ores_rpc_calls_http_tcp_pool::TcpRpcCall for {marker} {{\n\
                 const FRAMING: ::ores_rpc_calls_http_tcp_pool::TcpFraming =\n\
                     ::ores_rpc_calls_http_tcp_pool::TcpFraming::{framing};\n\
             }}\n"
        ));
    }
    if entry.transports.iter().any(|value| value == "nats") {
        let subject = entry.rpc_key.as_deref().unwrap_or(key);
        out.push_str(&format!(
            "impl ::ores_rpc_calls_http_tcp_pool::NatsRpcCall for {marker} {{\n\
                 const SUBJECT: &'static str = {subject:?};\n\
             }}\n"
        ));
    }
    out.push('\n');
    Ok(())
}

fn body_type(entry: &RouteEntry, module: &str, operation: &str) -> Result<String, String> {
    if entry.request_schema.is_some() {
        return Ok(projected_type(
            module,
            operation,
            "Request",
            entry.request_schema.as_ref(),
            "()",
        ));
    }

    let Some(binding) = &entry.binding else {
        return Ok("()".to_owned());
    };
    if binding.param_types.is_empty() {
        return Ok("()".to_owned());
    }
    if entry.path_params.is_some() || entry.query_schema.is_some() {
        return Err(format!(
            "{operation}: binding.param_types cannot infer a body when path/query schemas are present"
        ));
    }
    if !entry
        .methods
        .iter()
        .all(|method| matches!(method.as_str(), "POST" | "PUT" | "PATCH" | "DELETE"))
    {
        return Err(format!(
            "{operation}: binding.param_types can infer a body only for body-capable HTTP methods"
        ));
    }
    if binding.param_types.len() != 1 {
        return Err(format!(
            "{operation}: exactly one binding.param_types entry is required to infer an authored body DTO"
        ));
    }
    qualify_bound_type(module, &binding.param_types[0], operation, "body")
}

fn response_type(entry: &RouteEntry, module: &str, operation: &str) -> Result<String, String> {
    if entry.response_schema.is_some() {
        return Ok(projected_type(
            module,
            operation,
            "Response",
            entry.response_schema.as_ref(),
            "::serde_json::Value",
        ));
    }
    match entry
        .binding
        .as_ref()
        .and_then(|binding| binding.return_type.as_deref())
    {
        Some(value) => qualify_bound_type(module, value, operation, "response"),
        None => Ok("::serde_json::Value".to_owned()),
    }
}

fn qualify_bound_type(
    module: &str,
    value: &str,
    operation: &str,
    position: &str,
) -> Result<String, String> {
    if value == "()" {
        return Ok("()".to_owned());
    }
    if !is_rust_identifier(value) {
        return Err(format!(
            "{operation}: bound {position} type {value:?} must be a simple Rust identifier"
        ));
    }
    Ok(format!("{module}::{value}"))
}

fn is_rust_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn projected_type(
    module: &str,
    operation: &str,
    suffix: &str,
    schema: Option<&serde_json::Value>,
    absent: &str,
) -> String {
    match schema {
        None => absent.to_owned(),
        Some(value) if has_nonempty_properties(value) => {
            format!("{module}::{operation}{suffix}")
        }
        Some(_) => "::serde_json::Value".to_owned(),
    }
}

fn has_nonempty_properties(schema: &serde_json::Value) -> bool {
    schema
        .get("properties")
        .and_then(serde_json::Value::as_object)
        .is_some_and(|properties| !properties.is_empty())
}

fn pascal(key: &str) -> String {
    if key.chars().next().is_some_and(char::is_uppercase) && !key.contains('_') {
        return key.to_owned();
    }
    key.replace('-', "_")
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn canonical_route_emits_typed_pool_marker() {
        let map =
            RouteMap::from_json_str(include_str!("../../examples/canonical-api.route-map.json"))
                .expect("canonical map");
        let output = rpc_pool_bindings(&map, "crate::canonical_api").expect("bindings");
        assert!(output.contains("pub struct GetQuoteCall;"));
        assert!(output.contains("type Path = crate::canonical_api::GetQuotePath;"));
        assert!(
            output.contains("HttpRpcCall<::ores_rpc_calls_http_tcp_pool::Get> for GetQuoteCall")
        );
        assert!(
            output.contains("const PATH_TEMPLATE: &'static str = \"/api/v1/quotes/{quoteId}\";")
        );
    }

    #[test]
    fn authored_binding_types_can_supply_body_and_response_without_schema_duplication() {
        let map = RouteMap::from_json_str(
            r#"{
              "schema_version": "1.0.0",
              "service": "fiducia-api-server",
              "map": {
                "create_quote": {
                  "path": "/v1/quotes",
                  "methods": ["POST"],
                  "transports": ["http"],
                  "header_schema": {
                    "type": "object",
                    "properties": {
                      "idempotency-key": { "type": "string" }
                    },
                    "required": ["idempotency-key"]
                  },
                  "binding": {
                    "param_types": ["QuoteRequest"],
                    "return_type": "QuoteReceipt",
                    "file": "schema/commercial_intake.schema.json",
                    "symbol": "QuoteRequest"
                  }
                }
              }
            }"#,
        )
        .expect("binding-only route map");
        let output = rpc_pool_bindings(&map, "fiducia_interfaces")
            .expect("binding-only typed pool projection");
        assert!(output.contains("type Body = fiducia_interfaces::QuoteRequest;"));
        assert!(output.contains("type Response = fiducia_interfaces::QuoteReceipt;"));
        assert!(output.contains("type Headers = fiducia_interfaces::CreateQuoteHeaders;"));
        assert!(output.contains("const HAS_BODY: bool = true;"));
    }

    #[test]
    fn authored_binding_type_rejects_source_injection() {
        let map = RouteMap::from_json_str(
            r#"{
              "schema_version": "1.0.0",
              "service": "bad-api",
              "map": {
                "create": {
                  "path": "/v1/create",
                  "methods": ["POST"],
                  "transports": ["http"],
                  "binding": {
                    "param_types": ["QuoteRequest; panic!()"]
                  }
                }
              }
            }"#,
        )
        .expect("route map parses before Rust projection");
        let error = rpc_pool_bindings(&map, "dto").expect_err("unsafe type must fail closed");
        assert!(error.contains("simple Rust identifier"));
    }
}
