//! Rust projection from an authoritative `RouteMap` into the reusable
//! `ores-rpc-calls-http-tcp-pool` transport traits.
//!
//! The route map and generated/authored DTO module remain the authority. Inline
//! route schemas are emitted as companion transport DTOs in the generated file;
//! independently authored body/response DTOs remain references into the
//! supplied module. This keeps generated clients self-contained without
//! turning the transport layer into a second contract authority.

use std::collections::{BTreeMap, BTreeSet};

use crate::{RouteEntry, RouteMap};

/// Emit companion Rust source that binds one route map to
/// `ores-rpc-calls-http-tcp-pool`.
///
/// `dto_module` is a Rust path such as `crate::interfaces::canonical_api` or
/// `fiducia_interfaces`. Inline path/query/header/request/response schemas are
/// emitted directly beside the operation marker. When an operation deliberately
/// points at an independently authored DTO surface, a single body
/// `binding.param_types` entry and/or `binding.return_type` may name that DTO;
/// those names are qualified under `dto_module` and restricted to simple Rust
/// identifiers so route metadata cannot inject arbitrary source.
pub fn rpc_pool_bindings(map: &RouteMap, dto_module: &str) -> Result<String, String> {
    if dto_module.trim().is_empty() {
        return Err("dto_module must not be empty".to_owned());
    }
    let mut out = String::from(
        "// @generated by ores-api-docs rpc_pool_bindings; do not edit\n\
         // RouteMap + generated/authored DTOs remain authoritative.\n\n",
    );

    for (key, entry) in &map.map {
        emit_operation(&mut out, &map.service, key, entry, dto_module)?;
    }
    Ok(out)
}

fn emit_operation(
    out: &mut String,
    service: &str,
    key: &str,
    entry: &RouteEntry,
    dto_module: &str,
) -> Result<(), String> {
    let name = pascal(key);
    if name.is_empty() {
        return Err(format!("route key {key:?} cannot form a Rust marker name"));
    }
    let marker = format!("{name}Call");
    let path_ty = projected_inline_type(out, &name, "Path", entry.path_params.as_ref(), "()")?;
    let query_ty = projected_inline_type(out, &name, "Query", entry.query_schema.as_ref(), "()")?;
    let headers_ty =
        projected_inline_type(out, &name, "Headers", entry.header_schema.as_ref(), "()")?;
    let body_ty = body_type(out, entry, dto_module, &name)?;
    let response_ty = response_type(out, entry, dto_module, &name)?;
    let rpc_key = entry
        .rpc_key
        .as_deref()
        .map(|value| format!("Some({value:?})"))
        .unwrap_or_else(|| "None".to_owned());
    let has_body = body_ty != "()";

    out.push_str(&format!(
        "#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]\n\
         pub struct {marker};\n\n\
         impl ::ores_rpc_calls_http_tcp_pool::RpcCall for {marker} {{\n\
             type Path = {path_ty};\n\
             type Query = {query_ty};\n\
             type Headers = {headers_ty};\n\
             type Body = {body_ty};\n\
             type Response = {response_ty};\n\n\
             const SERVICE: &'static str = {service:?};\n\
             const KEY: &'static str = {key:?};\n\
             const RPC_KEY: Option<&'static str> = {rpc_key};\n\
             const PATH_TEMPLATE: &'static str = {path:?};\n\
             const HAS_BODY: bool = {has_body};\n\
         }}\n",
        path = entry.path,
    ));

    if entry.transports.iter().any(|value| value == "http") {
        for method in &entry.methods {
            let verb = match method.as_str() {
                "GET" => "Get",
                "POST" => "Post",
                "PUT" => "Put",
                "PATCH" => "Patch",
                "DELETE" => "Delete",
                "HEAD" => "Head",
                "OPTIONS" => "Options",
                other => return Err(format!("{key}: unsupported HTTP method {other}")),
            };
            out.push_str(&format!(
                "impl ::ores_rpc_calls_http_tcp_pool::HttpRpcCall<\
                 ::ores_rpc_calls_http_tcp_pool::{verb}> for {marker} {{}}\n"
            ));
        }
    }
    if entry.transports.iter().any(|value| value == "tcp") {
        let framing = match entry.tcp_framing.as_deref().unwrap_or("ndjson") {
            "ndjson" => "Ndjson",
            "length-prefixed" => "LengthPrefixed",
            other => return Err(format!("{key}: unsupported TCP framing {other}")),
        };
        out.push_str(&format!(
            "impl ::ores_rpc_calls_http_tcp_pool::TcpRpcCall for {marker} {{\n\
                 const FRAMING: ::ores_rpc_calls_http_tcp_pool::TcpFraming =\n\
                     ::ores_rpc_calls_http_tcp_pool::TcpFraming::{framing};\n\
             }}\n"
        ));
    }
    if entry.transports.iter().any(|value| value == "nats") {
        let subject = entry.rpc_key.as_deref().unwrap_or(key);
        out.push_str(&format!(
            "impl ::ores_rpc_calls_http_tcp_pool::NatsRpcCall for {marker} {{\n\
                 const SUBJECT: &'static str = {subject:?};\n\
             }}\n"
        ));
    }
    out.push('\n');
    Ok(())
}

fn body_type(
    out: &mut String,
    entry: &RouteEntry,
    module: &str,
    operation: &str,
) -> Result<String, String> {
    if entry.request_schema.is_some() {
        return projected_inline_type(
            out,
            operation,
            "Request",
            entry.request_schema.as_ref(),
            "()",
        );
    }

    let Some(binding) = &entry.binding else {
        return Ok("()".to_owned());
    };
    if binding.param_types.is_empty() {
        return Ok("()".to_owned());
    }
    if entry.path_params.is_some() || entry.query_schema.is_some() {
        return Err(format!(
            "{operation}: binding.param_types cannot infer a body when path/query schemas are present"
        ));
    }
    if !entry
        .methods
        .iter()
        .all(|method| matches!(method.as_str(), "POST" | "PUT" | "PATCH" | "DELETE"))
    {
        return Err(format!(
            "{operation}: binding.param_types can infer a body only for body-capable HTTP methods"
        ));
    }
    if binding.param_types.len() != 1 {
        return Err(format!(
            "{operation}: exactly one binding.param_types entry is required to infer an authored body DTO"
        ));
    }
    qualify_bound_type(module, &binding.param_types[0], operation, "body")
}

fn response_type(
    out: &mut String,
    entry: &RouteEntry,
    module: &str,
    operation: &str,
) -> Result<String, String> {
    if entry.response_schema.is_some() {
        return projected_inline_type(
            out,
            operation,
            "Response",
            entry.response_schema.as_ref(),
            "::serde_json::Value",
        );
    }
    match entry
        .binding
        .as_ref()
        .and_then(|binding| binding.return_type.as_deref())
    {
        Some(value) => qualify_bound_type(module, value, operation, "response"),
        None => Ok("::serde_json::Value".to_owned()),
    }
}

fn qualify_bound_type(
    module: &str,
    value: &str,
    operation: &str,
    position: &str,
) -> Result<String, String> {
    if value == "()" {
        return Ok("()".to_owned());
    }
    if !is_rust_identifier(value) {
        return Err(format!(
            "{operation}: bound {position} type {value:?} must be a simple Rust identifier"
        ));
    }
    Ok(format!("{module}::{value}"))
}

fn is_rust_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn projected_inline_type(
    out: &mut String,
    operation: &str,
    suffix: &str,
    schema: Option<&serde_json::Value>,
    absent: &str,
) -> Result<String, String> {
    match schema {
        None => Ok(absent.to_owned()),
        Some(value) if has_nonempty_properties(value) => {
            let name = format!("{operation}{suffix}");
            emit_inline_struct(out, &name, value)?;
            Ok(name)
        }
        Some(_) => Ok("::serde_json::Value".to_owned()),
    }
}

fn emit_inline_struct(
    out: &mut String,
    name: &str,
    schema: &serde_json::Value,
) -> Result<(), String> {
    let properties = schema
        .get("properties")
        .and_then(serde_json::Value::as_object)
        .ok_or_else(|| format!("{name}: inline object schema must contain properties"))?;
    let required = schema
        .get("required")
        .and_then(serde_json::Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(serde_json::Value::as_str)
        .collect::<BTreeSet<_>>();
    let mut occupied = BTreeMap::<String, String>::new();
    let mut fields = Vec::new();

    for (wire_name, property) in properties {
        let rust_name = rust_field_name(wire_name);
        if let Some(previous) = occupied.insert(rust_name.clone(), wire_name.clone()) {
            return Err(format!(
                "{name}: wire fields {previous:?} and {wire_name:?} both normalize to Rust field {rust_name:?}"
            ));
        }
        let nullable = schema_nullable(property);
        let required_field = required.contains(wire_name.as_str());
        let mut field_type = schema_rust_type(property);
        let optional = !required_field || nullable;
        if optional {
            field_type = format!("Option<{field_type}>");
        }
        let rename = if rust_name != *wire_name {
            format!("    #[serde(rename = {wire_name:?})]\n")
        } else {
            String::new()
        };
        let default = if optional {
            "    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n"
        } else {
            ""
        };
        fields.push(format!(
            "{rename}{default}    pub {rust_name}: {field_type},"
        ));
    }

    out.push_str(&format!(
        "#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]\n\
         pub struct {name} {{\n{}\n}}\n\n",
        fields.join("\n")
    ));
    Ok(())
}

fn schema_nullable(schema: &serde_json::Value) -> bool {
    schema
        .get("type")
        .and_then(serde_json::Value::as_array)
        .is_some_and(|items| items.iter().any(|item| item.as_str() == Some("null")))
}

fn schema_rust_type(schema: &serde_json::Value) -> String {
    if let Some(types) = schema.get("type").and_then(serde_json::Value::as_array) {
        if let Some(non_null) = types.iter().find_map(|item| {
            let kind = item.as_str()?;
            (kind != "null").then_some(kind)
        }) {
            return rust_type_for_kind(non_null, schema);
        }
    }
    schema
        .get("type")
        .and_then(serde_json::Value::as_str)
        .map(|kind| rust_type_for_kind(kind, schema))
        .unwrap_or_else(|| "::serde_json::Value".to_owned())
}

fn rust_type_for_kind(kind: &str, schema: &serde_json::Value) -> String {
    match kind {
        "string" => "String".to_owned(),
        "integer" => "i64".to_owned(),
        "number" => "f64".to_owned(),
        "boolean" => "bool".to_owned(),
        "array" => {
            let item = schema
                .get("items")
                .map(schema_rust_type)
                .unwrap_or_else(|| "::serde_json::Value".to_owned());
            format!("Vec<{item}>")
        }
        "object" => "::serde_json::Value".to_owned(),
        _ => "::serde_json::Value".to_owned(),
    }
}

fn rust_field_name(wire_name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super", "trait",
        "true", "type", "union", "unsafe", "use", "where", "while", "yield",
    ];
    let mut out = String::with_capacity(wire_name.len() + 2);
    for character in wire_name.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            out.push(character.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    while out.contains("__") {
        out = out.replace("__", "_");
    }
    let out = out.trim_matches('_').to_owned();
    let mut out = if out.is_empty() {
        "field".to_owned()
    } else {
        out
    };
    if out.as_bytes().first().is_some_and(u8::is_ascii_digit) {
        out.insert_str(0, "field_");
    }
    if KEYWORDS.contains(&out.as_str()) {
        out.push('_');
    }
    out
}

fn has_nonempty_properties(schema: &serde_json::Value) -> bool {
    schema
        .get("properties")
        .and_then(serde_json::Value::as_object)
        .is_some_and(|properties| !properties.is_empty())
}

fn pascal(key: &str) -> String {
    let mut out = String::with_capacity(key.len());
    let mut uppercase_next = true;
    for character in key.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase_next {
                out.extend(character.to_uppercase());
                uppercase_next = false;
            } else {
                out.push(character);
            }
        } else {
            uppercase_next = true;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn canonical_route_emits_self_contained_typed_pool_marker() {
        let map =
            RouteMap::from_json_str(include_str!("../../examples/canonical-api.route-map.json"))
                .expect("canonical map");
        let output = rpc_pool_bindings(&map, "crate::canonical_api").expect("bindings");
        assert!(output.contains("pub struct GetQuoteCall;"));
        assert!(output.contains("pub struct GetQuotePath"));
        assert!(output.contains("type Path = GetQuotePath;"));
        assert!(
            output.contains("HttpRpcCall<::ores_rpc_calls_http_tcp_pool::Get> for GetQuoteCall")
        );
        assert!(
            output.contains("const PATH_TEMPLATE: &'static str = \"/api/v1/quotes/{quoteId}\";")
        );
    }

    #[test]
    fn dotted_rpc_key_emits_valid_rust_marker() {
        let map = RouteMap::from_json_str(
            r#"{
              "schema_version": "1.0.0",
              "service": "canonical-api-server",
              "map": {
                "canonical_cloud.version.get_version": {
                  "path": "/v1/version",
                  "methods": ["GET"],
                  "rpc_key": "canonical_cloud.version.get_version",
                  "transports": ["http"]
                }
              }
            }"#,
        )
        .expect("dotted-key route map");
        let output = rpc_pool_bindings(&map, "crate::canonical_api").expect("bindings");
        assert!(output.contains("pub struct CanonicalCloudVersionGetVersionCall;"));
        assert!(
            output.contains("const KEY: &'static str = \"canonical_cloud.version.get_version\";")
        );
    }

    #[test]
    fn authored_binding_types_keep_body_response_external_but_emit_inline_headers() {
        let map = RouteMap::from_json_str(
            r#"{
              "schema_version": "1.0.0",
              "service": "fiducia-api-server",
              "map": {
                "create_quote": {
                  "path": "/v1/quotes",
                  "methods": ["POST"],
                  "transports": ["http"],
                  "header_schema": {
                    "type": "object",
                    "properties": {
                      "idempotency-key": { "type": "string" }
                    },
                    "required": ["idempotency-key"]
                  },
                  "binding": {
                    "param_types": ["QuoteRequest"],
                    "return_type": "QuoteReceipt",
                    "file": "schema/commercial_intake.schema.json",
                    "symbol": "QuoteRequest"
                  }
                }
              }
            }"#,
        )
        .expect("binding-only route map");
        let output = rpc_pool_bindings(&map, "fiducia_interfaces")
            .expect("binding-only typed pool projection");
        assert!(output.contains("type Body = fiducia_interfaces::QuoteRequest;"));
        assert!(output.contains("type Response = fiducia_interfaces::QuoteReceipt;"));
        assert!(output.contains("pub struct CreateQuoteHeaders"));
        assert!(output.contains("#[serde(rename = \"idempotency-key\")]"));
        assert!(output.contains("pub idempotency_key: String"));
        assert!(output.contains("type Headers = CreateQuoteHeaders;"));
        assert!(output.contains("const HAS_BODY: bool = true;"));
    }

    #[test]
    fn optional_inline_fields_are_omitted_when_none() {
        let map = RouteMap::from_json_str(
            r#"{
              "schema_version": "1.0.0",
              "service": "demo-api",
              "map": {
                "list_items": {
                  "path": "/v1/items",
                  "methods": ["GET"],
                  "query_schema": {
                    "type": "object",
                    "properties": {
                      "cursor": { "type": ["string", "null"] },
                      "limit": { "type": "integer" }
                    }
                  },
                  "transports": ["http"]
                }
              }
            }"#,
        )
        .expect("route map");
        let output = rpc_pool_bindings(&map, "dto").expect("projection");
        assert!(output.contains("pub cursor: Option<String>"));
        assert!(output.contains("pub limit: Option<i64>"));
        assert!(output.contains("skip_serializing_if = \"Option::is_none\""));
    }

    #[test]
    fn authored_binding_type_rejects_source_injection() {
        let map = RouteMap::from_json_str(
            r#"{
              "schema_version": "1.0.0",
              "service": "bad-api",
              "map": {
                "create": {
                  "path": "/v1/create",
                  "methods": ["POST"],
                  "transports": ["http"],
                  "binding": {
                    "param_types": ["QuoteRequest; panic!()"]
                  }
                }
              }
            }"#,
        )
        .expect("route map parses before Rust projection");
        let error = rpc_pool_bindings(&map, "dto").expect_err("unsafe type must fail closed");
        assert!(error.contains("simple Rust identifier"));
    }
}
