//! Deterministic publication bundles for API docs and MCP-facing discovery docs.
//!
//! The semantic API contract remains the validated [`Catalog`]. Publication
//! metadata only distinguishes who owns the rendered bundle. In particular,
//! project-owned output is never promoted to platform-publisher authority merely
//! because it was generated by the same renderer.

#![allow(clippy::needless_return)]

use std::collections::BTreeMap;

use serde::Serialize;
use serde_json::Value;
use thiserror::Error;

use crate::catalog::Catalog;
use crate::discovery::DocsDiscoveryManifest;
use crate::html::render_html;
use crate::project::contract_sha256;

pub const PUBLICATION_SCHEMA_VERSION: &str = "ores.api-docs.publication.v1";
pub const PUBLICATION_GENERATOR: &str = "ores-api-docs";
pub const PUBLICATION_ARTIFACTS: [&str; 9] = [
    "api/catalog.json",
    "api/openapi.json",
    "api/openrpc.json",
    "api/connect.json",
    "api/hyper-schema.json",
    "api/index.html",
    "mcp/manifest.json",
    "mcp/server.md",
    "publication.json",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PublicationMode {
    PublisherExternal,
    ConsumerProject,
}

impl PublicationMode {
    #[must_use]
    pub const fn authority_scope(self) -> &'static str {
        match self {
            Self::PublisherExternal => {
                return "platform_external_developers";
            }
            Self::ConsumerProject => {
                return "project_owned";
            }
        }
    }

    #[must_use]
    pub const fn publisher_provenance_required(self) -> bool {
        match self {
            Self::PublisherExternal => {
                return true;
            }
            Self::ConsumerProject => {
                return false;
            }
        }
    }

    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::PublisherExternal => {
                return "publisher_external";
            }
            Self::ConsumerProject => {
                return "consumer_project";
            }
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct DocsPublicationManifest {
    pub schema_version: &'static str,
    pub generator: &'static str,
    pub service: String,
    pub publication_mode: PublicationMode,
    pub producer: String,
    pub authority_scope: &'static str,
    pub publisher_provenance_required: bool,
    pub contract_sha256: String,
    pub route_count: u32,
    pub mcp_discovery: &'static str,
    pub artifacts: [&'static str; 9],
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DocsPublicationBundle {
    pub manifest: DocsPublicationManifest,
    pub files: BTreeMap<String, String>,
}

impl DocsPublicationBundle {
    #[must_use]
    pub fn file(&self, path: &str) -> Option<&str> {
        return self.files.get(path).map(String::as_str);
    }
}

#[derive(Debug, Error)]
pub enum PublicationError {
    #[error("producer must match ^[A-Za-z][A-Za-z0-9._-]{{0,127}}$")]
    InvalidProducer,
    #[error("route count exceeds uint32 publication contract")]
    RouteCountOverflow,
    #[error("api-docs catalog error: {0}")]
    Catalog(#[from] crate::schema::SchemaError),
    #[error("serialize publication artifact: {0}")]
    Serialize(#[from] serde_json::Error),
    #[error("docs publication JSON Schema is invalid: {0}")]
    InvalidSchema(String),
    #[error("docs publication manifest violates its JSON Schema authority: {0}")]
    InvalidManifest(String),
}

/// Render one complete documentation bundle as a pure function of a validated
/// catalog plus explicit publication identity.
///
/// No clock, network, environment, host header, git checkout, or model is read.
/// Equal inputs therefore produce byte-identical output maps.
pub fn render_docs_publication(
    catalog: &Catalog,
    mode: PublicationMode,
    producer: &str,
) -> Result<DocsPublicationBundle, PublicationError> {
    if !valid_identity(producer) {
        return Err(PublicationError::InvalidProducer);
    }

    let route_count = match u32::try_from(catalog.map.map.len()) {
        Ok(route_count) if route_count > 0 => route_count,
        _ => {
            return Err(PublicationError::RouteCountOverflow);
        }
    };
    let discovery = DocsDiscoveryManifest::from_catalog(catalog);
    let manifest = DocsPublicationManifest {
        schema_version: PUBLICATION_SCHEMA_VERSION,
        generator: PUBLICATION_GENERATOR,
        service: catalog.map.service.clone(),
        publication_mode: mode,
        producer: producer.to_owned(),
        authority_scope: mode.authority_scope(),
        publisher_provenance_required: mode.publisher_provenance_required(),
        contract_sha256: contract_sha256(&catalog.map),
        route_count,
        mcp_discovery: discovery.discovery,
        artifacts: PUBLICATION_ARTIFACTS,
    };
    validate_manifest(&manifest)?;

    let mut files = BTreeMap::new();
    files.insert(
        "api/catalog.json".to_owned(),
        with_final_newline(catalog.to_pretty_json()?),
    );
    files.insert(
        "api/openapi.json".to_owned(),
        pretty_json(&catalog.openapi)?,
    );
    files.insert(
        "api/openrpc.json".to_owned(),
        pretty_json(&catalog.openrpc)?,
    );
    files.insert(
        "api/connect.json".to_owned(),
        pretty_json(&catalog.connect)?,
    );
    files.insert(
        "api/hyper-schema.json".to_owned(),
        pretty_json(&catalog.hyper_schema)?,
    );
    files.insert("api/index.html".to_owned(), render_html(catalog));
    files.insert(
        "mcp/manifest.json".to_owned(),
        with_final_newline(discovery.to_pretty_json()?),
    );
    files.insert(
        "mcp/server.md".to_owned(),
        render_mcp_server_markdown(catalog, &manifest),
    );
    files.insert(
        "publication.json".to_owned(),
        pretty_json(&serde_json::to_value(&manifest)?)?,
    );

    return Ok(DocsPublicationBundle { manifest, files });
}

fn validate_manifest(manifest: &DocsPublicationManifest) -> Result<(), PublicationError> {
    let schema: Value = serde_json::from_str(include_str!(
        "../../json-schema/docs-publication.schema.json"
    ))?;
    let validator = jsonschema::validator_for(&schema)
        .map_err(|error| PublicationError::InvalidSchema(error.to_string()))?;
    let value = serde_json::to_value(manifest)?;
    validator
        .validate(&value)
        .map_err(|error| PublicationError::InvalidManifest(error.to_string()))?;

    return Ok(());
}

fn render_mcp_server_markdown(catalog: &Catalog, manifest: &DocsPublicationManifest) -> String {
    let mut output = format!(
        "# {} MCP server docs\n\nPublication mode: `{}`\n\nAuthority scope: `{}`\n\nContract SHA-256: `{}`\n\nMCP/API-docs discovery: `{}`\n\n",
        markdown_cell(&catalog.map.service),
        manifest.publication_mode.as_str(),
        manifest.authority_scope,
        manifest.contract_sha256,
        manifest.mcp_discovery,
    );

    if manifest.publisher_provenance_required {
        output.push_str(
            "This bundle is intended for platform-publisher external documentation. Publication infrastructure MUST attach and verify publisher provenance before presenting it as official platform documentation.\n\n",
        );
    } else {
        output.push_str(
            "This bundle is project-owned consumer documentation. It is not authoritative documentation for the platform that hosts or executes the project.\n\n",
        );
    }

    output.push_str(
        "The MCP server should discover the digest-bound API catalog through the relative manifest above and reject a fetched catalog whose contract digest differs.\n\n## Operations\n\n| operation | methods | path |\n| --- | --- | --- |\n",
    );
    for (operation, route) in &catalog.map.map {
        output.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            markdown_cell(operation),
            markdown_cell(&route.methods.join(", ")),
            markdown_cell(&route.path),
        ));
    }

    return output;
}

fn pretty_json(value: &Value) -> Result<String, serde_json::Error> {
    let json = serde_json::to_string_pretty(value)?;
    return Ok(with_final_newline(json));
}

fn with_final_newline(mut value: String) -> String {
    if !value.ends_with('\n') {
        value.push('\n');
    }

    return value;
}

fn markdown_cell(value: &str) -> String {
    return value.replace('|', "\\|").replace('\n', " ");
}

fn valid_identity(value: &str) -> bool {
    if value.is_empty() || value.len() > 128 {
        return false;
    }
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !first.is_ascii_alphabetic() {
        return false;
    }

    return chars.all(|character| {
        character.is_ascii_alphanumeric() || matches!(character, '.' | '_' | '-')
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::map::RouteMap;

    fn catalog(service: &str) -> Catalog {
        let route_map_json = match service {
            "beamscale" => {
                include_str!("../../conformance/docs-publication/beamscale.route-map.json")
            }
            "fiducia-cloud" => {
                include_str!("../../conformance/docs-publication/fiducia-cloud.route-map.json")
            }
            "scintilla-run" => {
                include_str!("../../conformance/docs-publication/scintilla-run.route-map.json")
            }
            other => {
                panic!("unknown docs-publication fixture: {other}");
            }
        };
        let map = RouteMap::from_json_str(route_map_json).expect("publication fixture route map");
        return Catalog::from_map_with_language(map, None).expect("publication fixture catalog");
    }

    #[test]
    fn beamscale_fiducia_and_scintilla_reproduce_byte_identically() {
        for service in ["beamscale", "fiducia-cloud", "scintilla-run"] {
            let catalog = catalog(service);
            let first =
                render_docs_publication(&catalog, PublicationMode::PublisherExternal, service)
                    .expect("first publication render");
            let second =
                render_docs_publication(&catalog, PublicationMode::PublisherExternal, service)
                    .expect("second publication render");

            assert_eq!(first, second, "{service} publication drifted between runs");
            assert_eq!(first.files.len(), PUBLICATION_ARTIFACTS.len());
            assert_eq!(first.manifest.contract_sha256.len(), 64);
        }
    }

    #[test]
    fn publisher_and_consumer_modes_do_not_change_the_api_contract() {
        let catalog = catalog("scintilla-run");
        let publisher = render_docs_publication(
            &catalog,
            PublicationMode::PublisherExternal,
            "scintilla-run",
        )
        .expect("publisher docs");
        let consumer = render_docs_publication(
            &catalog,
            PublicationMode::ConsumerProject,
            "example-project",
        )
        .expect("consumer docs");

        assert_eq!(
            publisher.manifest.contract_sha256,
            consumer.manifest.contract_sha256
        );
        for path in [
            "api/catalog.json",
            "api/openapi.json",
            "api/openrpc.json",
            "api/connect.json",
            "api/hyper-schema.json",
            "api/index.html",
            "mcp/manifest.json",
        ] {
            assert_eq!(
                publisher.file(path),
                consumer.file(path),
                "publication ownership changed semantic artifact {path}"
            );
        }

        assert_ne!(
            publisher.file("publication.json"),
            consumer.file("publication.json")
        );
        assert_ne!(
            publisher.file("mcp/server.md"),
            consumer.file("mcp/server.md")
        );
        assert_eq!(
            publisher.manifest.authority_scope,
            "platform_external_developers"
        );
        assert!(publisher.manifest.publisher_provenance_required);
        assert_eq!(consumer.manifest.authority_scope, "project_owned");
        assert!(!consumer.manifest.publisher_provenance_required);
    }

    #[test]
    fn rejects_ambiguous_or_path_like_producer_identity() {
        let catalog = catalog("beamscale");
        for producer in ["", "../beamscale", "beamscale/org", "-beamscale"] {
            assert!(matches!(
                render_docs_publication(&catalog, PublicationMode::ConsumerProject, producer,),
                Err(PublicationError::InvalidProducer)
            ));
        }
    }

    #[test]
    fn typespec_and_json_schema_modes_match_runtime() {
        let typespec = include_str!("../../idl/typespec/docs-publication.tsp");
        let schema: Value = serde_json::from_str(include_str!(
            "../../json-schema/docs-publication.schema.json"
        ))
        .expect("publication schema");

        for literal in [
            PUBLICATION_SCHEMA_VERSION,
            "publisher_external",
            "consumer_project",
            "platform_external_developers",
            "project_owned",
            "/api-docs/manifest.json",
        ] {
            assert!(typespec.contains(literal), "TypeSpec is missing {literal}");
            assert!(
                schema.to_string().contains(literal),
                "JSON Schema is missing {literal}"
            );
        }
        for artifact in PUBLICATION_ARTIFACTS {
            assert!(
                typespec.contains(artifact),
                "TypeSpec is missing {artifact}"
            );
            assert!(
                schema.to_string().contains(artifact),
                "JSON Schema is missing {artifact}"
            );
        }
    }
}
