//! Filesystem contract for one ORES API route folder.
//!
//! Canonical API-server layout:
//! `route.rs` (handwritten HTTP adapter), `handlers.rs` (handwritten semantic
//! operations), and generated `rpc.rs`. Browser-page generation belongs to the
//! separate `src/pages/**/{page.rs,gen.rs}` web-server contract; `gen.rs` is not
//! part of an API route folder.
//!
//! This module is source-analysis only; it never executes an HTTP or RPC request.

use crate::{
    analyze_shared_operation_route_source, verify_shared_operation_invocations,
    SharedOperationRouteSource, SharedOperationSourceError,
};

pub const ROUTE_FILE: &str = "route.rs";
pub const HANDLERS_FILE: &str = "handlers.rs";
pub const RPC_FILE: &str = "rpc.rs";
/// Compatibility export only. `gen.rs` belongs to `src/pages/**` in web-server
/// repositories and must not be treated as part of an API route folder.
/// Planned for removal once downstream callers use the page-specific contract.
#[deprecated(note = "gen.rs is not part of an API route folder; use the src/pages page contract")]
pub const GEN_FILE: &str = "gen.rs";
pub const GENERATED_RPC_MARKER: &str = "// @generated by ores-stack sync; do not edit";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RouteFolderContract {
    pub route_file: String,
    pub handlers_file: String,
    pub rpc_file: String,
    /// Always `None` for an API route folder. `gen.rs` is a web-server page
    /// companion (`src/pages/**/{page.rs,gen.rs}`), never an API route file.
    /// Kept one release so removing it is not a silent source break for
    /// downstream struct literals and patterns; use the page contract instead.
    #[deprecated(
        note = "gen.rs is not part of an API route folder; use the src/pages page contract"
    )]
    pub gen_file: Option<String>,
    pub analysis: SharedOperationRouteSource,
}

/// Analyze the two handwritten runtime files as one semantic unit.
///
/// `handlers.rs` owns semantic operations. `route.rs`, when present, may refer
/// to those operations with paths such as `handlers::find_user`; it is an HTTP
/// projection, not the operation authority. The shared-operation analyzer
/// intentionally reduces those paths to the terminal operation symbol, which
/// lets the same static binding checks work while keeping the files physically
/// separate.
pub fn analyze_route_folder_sources(
    route_path: &str,
    route_source: &str,
    handlers_path: &str,
    handlers_source: &str,
) -> Result<SharedOperationRouteSource, SharedOperationSourceError> {
    let combined = format!(
        "// --- {handlers_path} ---\n{handlers_source}\n\n// --- {route_path} ---\n{route_source}\n"
    );
    analyze_shared_operation_route_source(route_path, &combined)
}

/// Verify that every HTTP adapter calls the generated invoker for the operation
/// in `handlers.rs`, never the handwritten operation directly.
pub fn verify_route_folder_invocations(
    route_path: &str,
    route_source: &str,
    handlers_path: &str,
    handlers_source: &str,
    analysis: &SharedOperationRouteSource,
) -> Result<(), String> {
    let combined = format!(
        "// --- {handlers_path} ---\n{handlers_source}\n\n// --- {route_path} ---\n{route_source}\n"
    );
    verify_shared_operation_invocations(route_path, &combined, analysis)
}

/// Checked-in `rpc.rs` is generated during the migration period. Once RPC glue
/// is build-only this check can move to the build artifact instead of VCS.
pub fn verify_generated_rpc_source(path: &str, source: &str) -> Result<(), String> {
    let first_nonempty = source.lines().find(|line| !line.trim().is_empty());
    if first_nonempty != Some(GENERATED_RPC_MARKER) {
        return Err(format!(
            "{path}: rpc.rs must begin with {GENERATED_RPC_MARKER:?}; regenerate with `ores-stack sync`"
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const HANDLERS: &str = r#"
        #[ores_operation(
            spec = FindUserOperation,
            key = "demo.users.find_user",
            codecs("json", "protobuf", "messagepack"),
            default_codec = "json",
            audiences("browser", "server")
        )]
        pub async fn find_user(
            ctx: TypedOperationContext<AppState, FindUserOperation>,
        ) -> Result<FindUserOutput, FindUserError> {
            let path = ctx.path()?;
            todo!("{}", path.user_id)
        }
    "#;

    const ROUTE: &str = r#"
        #[ores_route(operation = handlers::find_user)]
        pub async fn get() -> HttpResult {
            handlers::__ores_invoke_find_user(ctx).await.into()
        }
    "#;

    #[test]
    fn sibling_handlers_and_route_form_one_checked_contract() {
        let analysis = analyze_route_folder_sources(
            "src/routes/v1/users/[user_id]/route.rs",
            ROUTE,
            "src/routes/v1/users/[user_id]/handlers.rs",
            HANDLERS,
        )
        .expect("route folder analysis");
        let operation = analysis.operation_for_method("GET").expect("GET op");
        assert_eq!(operation.rust_name, "find_user");
        assert_eq!(operation.spec.as_deref(), Some("FindUserOperation"));
        verify_route_folder_invocations(
            "src/routes/v1/users/[user_id]/route.rs",
            ROUTE,
            "src/routes/v1/users/[user_id]/handlers.rs",
            HANDLERS,
            &analysis,
        )
        .expect("shared invoker");
    }

    #[test]
    fn direct_handler_call_is_rejected_across_files() {
        let bad_route = r#"
            #[ores_route(operation = handlers::find_user)]
            pub async fn get() -> HttpResult {
                handlers::find_user(ctx).await.into()
            }
        "#;
        let analysis = analyze_route_folder_sources(
            "src/routes/v1/users/[user_id]/route.rs",
            bad_route,
            "src/routes/v1/users/[user_id]/handlers.rs",
            HANDLERS,
        )
        .expect("route folder analysis");
        let error = verify_route_folder_invocations(
            "src/routes/v1/users/[user_id]/route.rs",
            bad_route,
            "src/routes/v1/users/[user_id]/handlers.rs",
            HANDLERS,
            &analysis,
        )
        .expect_err("direct operation bypass must fail");
        assert!(error.contains("must not call"));
    }

    #[test]
    fn generated_rpc_file_is_marked() {
        verify_generated_rpc_source(
            "src/routes/v1/users/[user_id]/rpc.rs",
            &format!("{GENERATED_RPC_MARKER}\npub fn register() {{}}\n"),
        )
        .expect("generated marker");
        assert!(verify_generated_rpc_source("rpc.rs", "pub fn handwritten() {}\n").is_err());
    }
}
