//! Filesystem contract for one ORES route folder.
//!
//! Canonical layout:
//! `route.rs` (handwritten HTTP adapter), `handlers.rs` (handwritten semantic
//! operations), generated `rpc.rs`, and optional handwritten `gen.rs` for page
//! / static build hooks. This module is source-analysis only; it never executes
//! an HTTP or RPC request.

use crate::{
    analyze_shared_operation_route_source, verify_shared_operation_invocations,
    SharedOperationRouteSource, SharedOperationSourceError,
};

pub const ROUTE_FILE: &str = "route.rs";
pub const HANDLERS_FILE: &str = "handlers.rs";
pub const RPC_FILE: &str = "rpc.rs";
pub const GEN_FILE: &str = "gen.rs";
pub const GENERATED_RPC_MARKER: &str = "// @generated by ores-stack rpc; do not edit";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RouteFolderContract {
    pub route_file: String,
    pub handlers_file: String,
    pub rpc_file: String,
    pub gen_file: Option<String>,
    pub analysis: SharedOperationRouteSource,
}

/// Analyze the two handwritten runtime files as one semantic unit.
///
/// `route.rs` should refer to semantic operations with paths such as
/// `handlers::find_user`. The shared-operation analyzer intentionally reduces
/// those paths to the terminal operation symbol, which lets the same static
/// binding checks work while keeping the files physically separate.
pub fn analyze_route_folder_sources(
    route_path: &str,
    route_source: &str,
    handlers_path: &str,
    handlers_source: &str,
) -> Result<SharedOperationRouteSource, SharedOperationSourceError> {
    let combined = format!(
        "// --- {handlers_path} ---\n{handlers_source}\n\n// --- {route_path} ---\n{route_source}\n"
    );
    analyze_shared_operation_route_source(route_path, &combined)
}

/// Verify that every HTTP adapter calls the generated invoker for the operation
/// in `handlers.rs`, never the handwritten operation directly.
pub fn verify_route_folder_invocations(
    route_path: &str,
    route_source: &str,
    handlers_path: &str,
    handlers_source: &str,
    analysis: &SharedOperationRouteSource,
) -> Result<(), String> {
    let combined = format!(
        "// --- {handlers_path} ---\n{handlers_source}\n\n// --- {route_path} ---\n{route_source}\n"
    );
    verify_shared_operation_invocations(route_path, &combined, analysis)
}

/// Checked-in `rpc.rs` is generated during the migration period. Once RPC glue
/// is build-only this check can move to the build artifact instead of VCS.
pub fn verify_generated_rpc_source(path: &str, source: &str) -> Result<(), String> {
    let first_nonempty = source.lines().find(|line| !line.trim().is_empty());
    if first_nonempty != Some(GENERATED_RPC_MARKER) {
        return Err(format!(
            "{path}: rpc.rs must begin with {GENERATED_RPC_MARKER:?}; regenerate with ores-stack"
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const HANDLERS: &str = r#"
        #[ores_operation(
            spec = FindUserOperation,
            key = "demo.users.find_user",
            codecs("json", "protobuf", "messagepack"),
            default_codec = "json",
            audiences("browser", "server")
        )]
        pub async fn find_user(
            ctx: TypedOperationContext<AppState, FindUserOperation>,
        ) -> Result<FindUserOutput, FindUserError> {
            let path = ctx.path()?;
            todo!("{}", path.user_id)
        }
    "#;

    const ROUTE: &str = r#"
        #[ores_route(operation = handlers::find_user)]
        pub async fn get() -> HttpResult {
            handlers::__ores_invoke_find_user(ctx).await.into()
        }
    "#;

    #[test]
    fn sibling_handlers_and_route_form_one_checked_contract() {
        let analysis = analyze_route_folder_sources(
            "src/routes/v1/users/[user_id]/route.rs",
            ROUTE,
            "src/routes/v1/users/[user_id]/handlers.rs",
            HANDLERS,
        )
        .expect("route folder analysis");
        let operation = analysis.operation_for_method("GET").expect("GET op");
        assert_eq!(operation.rust_name, "find_user");
        assert_eq!(operation.spec.as_deref(), Some("FindUserOperation"));
        verify_route_folder_invocations(
            "src/routes/v1/users/[user_id]/route.rs",
            ROUTE,
            "src/routes/v1/users/[user_id]/handlers.rs",
            HANDLERS,
            &analysis,
        )
        .expect("shared invoker");
    }

    #[test]
    fn direct_handler_call_is_rejected_across_files() {
        let bad_route = r#"
            #[ores_route(operation = handlers::find_user)]
            pub async fn get() -> HttpResult {
                handlers::find_user(ctx).await.into()
            }
        "#;
        let analysis = analyze_route_folder_sources(
            "src/routes/v1/users/[user_id]/route.rs",
            bad_route,
            "src/routes/v1/users/[user_id]/handlers.rs",
            HANDLERS,
        )
        .expect("route folder analysis");
        let error = verify_route_folder_invocations(
            "src/routes/v1/users/[user_id]/route.rs",
            bad_route,
            "src/routes/v1/users/[user_id]/handlers.rs",
            HANDLERS,
            &analysis,
        )
        .expect_err("direct operation bypass must fail");
        assert!(error.contains("must not call"));
    }

    #[test]
    fn generated_rpc_file_is_marked() {
        verify_generated_rpc_source(
            "src/routes/v1/users/[user_id]/rpc.rs",
            &format!("{GENERATED_RPC_MARKER}\npub fn register() {{}}\n"),
        )
        .expect("generated marker");
        assert!(verify_generated_rpc_source("rpc.rs", "pub fn handwritten() {}\n").is_err());
    }
}
