// Generated by `cargo run --bin ores-rpc-docs -- generate`. Do not edit by hand.

use super::rpc_fluent::{Set, StreamCall, UnaryCall, Unset};
use serde_json::{json, Value};

/// Catalog version this surface was generated from.
pub const CATALOG_VERSION: &str = "1.0.0";
pub const DEFAULT_RPC_PATH: &str = "/v1/rpc";

/// Placeholder substituted for any redacted value in a request plan.
pub const REDACTED: &str = "[redacted]";

/// Header names redacted outright, lowercase, sorted.
pub const REDACTED_HEADER_NAMES: &[&str] = &[
    "authentication",
    "authorization",
    "cookie",
    "proxy-authorization",
    "set-cookie",
    "www-authenticate",
    "x-amz-security-token",
    "x-auth-token",
    "x-csrf-token",
    "x-session-token",
    "x-xsrf-token",
];

/// Substrings that mark a header name as credential-bearing.
pub const REDACTED_HEADER_PATTERNS: &[&str] = &[
    "access-token",
    "api-key",
    "apikey",
    "auth-token",
    "credential",
    "id-token",
    "password",
    "private-key",
    "refresh-token",
    "secret",
    "session-id",
    "signature",
];

/// Placeholder for URL userinfo; RFC 3986 unreserved characters only.
pub const REDACTED_URL_USERINFO: &str = "redacted";

/// Query-field names redacted outright, normalized.
pub const REDACTED_QUERY_NAMES: &[&str] = &[
    "access-token",
    "api-key",
    "apikey",
    "auth",
    "password",
    "secret",
    "sig",
    "signature",
    "token",
];

/// Plan fields holding a URL whose userinfo is stripped.
pub const REDACTED_URL_FIELDS: &[&str] = &["proxy_url"];

/// Headers whose value is a comma-separated directive list: writes are merged, never replaced.
pub const LIST_VALUED_HEADERS: &[&str] = &["cache-control"];

/// `Rpc.Strat` in the catalog; wire values are stable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum SerialStrategy {
    Json,
    MessagePack,
    Protobuf,
}

impl SerialStrategy {
    /// Canonical wire value written into the request plan.
    #[must_use]
    pub fn wire_value(self) -> Value {
        match self {
            Self::Json => json!("json"),
            Self::MessagePack => json!("message_pack"),
            Self::Protobuf => json!("protobuf"),
        }
    }

    /// Header effect this variant applies to the outbound request.
    #[must_use]
    pub fn header_effect(self) -> &'static [(&'static str, &'static str)] {
        match self {
            Self::Json => &[
                ("content-type", "application/json"),
                ("accept", "application/json"),
            ],
            Self::MessagePack => &[
                ("content-type", "application/msgpack"),
                ("accept", "application/msgpack"),
            ],
            Self::Protobuf => &[
                ("content-type", "application/x-protobuf"),
                ("accept", "application/x-protobuf"),
            ],
        }
    }
}

/// `Rpc.Compression` in the catalog; wire values are stable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Compression {
    Identity,
    Gzip,
    Brotli,
    Zstd,
}

impl Compression {
    /// Canonical wire value written into the request plan.
    #[must_use]
    pub fn wire_value(self) -> Value {
        match self {
            Self::Identity => json!("identity"),
            Self::Gzip => json!("gzip"),
            Self::Brotli => json!("brotli"),
            Self::Zstd => json!("zstd"),
        }
    }

    /// Header effect this variant applies to the outbound request.
    #[must_use]
    pub fn header_effect(self) -> &'static [(&'static str, &'static str)] {
        match self {
            Self::Identity => &[("content-encoding", "identity")],
            Self::Gzip => &[("content-encoding", "gzip")],
            Self::Brotli => &[("content-encoding", "br")],
            Self::Zstd => &[("content-encoding", "zstd")],
        }
    }
}

/// `Rpc.QPriority` in the catalog; wire values are stable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum QueuePriority {
    Zero,
    One,
    Two,
    Three,
    Four,
}

impl QueuePriority {
    /// Canonical wire value written into the request plan.
    #[must_use]
    pub fn wire_value(self) -> Value {
        match self {
            Self::Zero => json!(0),
            Self::One => json!(1),
            Self::Two => json!(2),
            Self::Three => json!(3),
            Self::Four => json!(4),
        }
    }

    /// Header effect this variant applies to the outbound request.
    #[must_use]
    pub fn header_effect(self) -> &'static [(&'static str, &'static str)] {
        match self {
            Self::Zero => &[],
            Self::One => &[],
            Self::Two => &[],
            Self::Three => &[],
            Self::Four => &[],
        }
    }
}

/// `Rpc.Backpressure` in the catalog; wire values are stable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Backpressure {
    Buffer,
    DropOldest,
    DropNewest,
    Error,
}

impl Backpressure {
    /// Canonical wire value written into the request plan.
    #[must_use]
    pub fn wire_value(self) -> Value {
        match self {
            Self::Buffer => json!("buffer"),
            Self::DropOldest => json!("drop_oldest"),
            Self::DropNewest => json!("drop_newest"),
            Self::Error => json!("error"),
        }
    }

    /// Header effect this variant applies to the outbound request.
    #[must_use]
    pub fn header_effect(self) -> &'static [(&'static str, &'static str)] {
        match self {
            Self::Buffer => &[],
            Self::DropOldest => &[],
            Self::DropNewest => &[],
            Self::Error => &[],
        }
    }
}

/// Options available on a unary chain in any type-state.
impl<Auth, Ip, Rate, Serial> UnaryCall<Auth, Ip, Rate, Serial> {
    /// Set one field on an object request body.
    #[must_use]
    pub fn add_body_field(mut self, name: &str, value: Value) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_body_field(name, value);
        self.transmute()
    }

    /// Set one normalized request header on the call envelope.
    #[must_use]
    pub fn add_header(mut self, name: &str, value: Value) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_header(&name.to_ascii_lowercase(), value);
        self.transmute()
    }

    /// Merge several request headers at once.
    #[must_use]
    pub fn add_headers(
        mut self,
        values: serde_json::Map<String, Value>,
    ) -> UnaryCall<Auth, Ip, Rate, Serial> {
        for (name, value) in values {
            self.set_header(&name.to_ascii_lowercase(), value);
        }
        self.transmute()
    }

    /// Add a uniform random delay up to this bound, to break up thundering herds.
    #[must_use]
    pub fn add_jitter(mut self, millis: u32) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(millis >= 1, "add_jitter: millis must be at least 1");
        assert!(millis <= 60000, "add_jitter: millis must be at most 60000");
        self.set_plan("jitter_millis", json!(millis));
        self.transmute()
    }

    /// Bind one path-template variable.
    #[must_use]
    pub fn add_path_field(mut self, name: &str, value: Value) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_section("path", name, value);
        self.transmute()
    }

    /// Bind one query-string field.
    #[must_use]
    pub fn add_query_field(
        mut self,
        name: &str,
        value: Value,
    ) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_section("query", name, value);
        self.transmute()
    }

    /// Force or disable request-payload compression for this call.
    #[must_use]
    pub fn compress(mut self, compression: Compression) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("compression", compression.wire_value());
        for (name, value) in compression.header_effect() {
            self.set_wire_header(name, (*value).to_owned());
        }
        self.transmute()
    }

    /// Serialize this call against every other call sharing the same named queue.
    #[must_use]
    pub fn concurrency_key(mut self, key: &str) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(
            key.len() <= 128,
            "concurrency_key: key must be at most 128 characters"
        );
        self.set_plan("concurrency_key", json!(key));
        self.transmute()
    }

    /// Log the exact outbound and inbound payload for this call only, with secret options redacted.
    #[must_use]
    pub fn debug(mut self) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("debug", json!(true));
        self.transmute()
    }

    /// Join an identical in-flight call instead of opening a second socket. Both callers receive the same receipt.
    #[must_use]
    pub fn dedupe(mut self) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("dedupe", json!(true));
        self.transmute()
    }

    /// Hold the outbound call for a fixed interval before sending.
    #[must_use]
    pub fn delay(mut self, millis: u32) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(millis <= 60000, "delay: millis must be at most 60000");
        self.set_plan("delay_millis", json!(millis));
        self.transmute()
    }

    /// Fail immediately rather than queue when the outbound queue is saturated. For telemetry where dropping beats memory pressure.
    #[must_use]
    pub fn drop_if_busy(mut self) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("drop_if_busy", json!(true));
        self.transmute()
    }

    /// Validate payload, headers and authorization server-side without executing the mutation.
    #[must_use]
    pub fn dry_run(mut self) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("dry_run", json!(true));
        self.set_wire_header("x-ores-dry-run", "1".to_owned());
        self.transmute()
    }

    /// Override connection pooling. Disabling closes the socket immediately after the receipt.
    #[must_use]
    pub fn keep_alive(mut self, enabled: bool) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("keep_alive", json!(enabled));
        self.set_wire_header(
            "connection",
            format!(
                "{}{}{}",
                "",
                if enabled { "keep-alive" } else { "close" },
                ""
            ),
        );
        self.transmute()
    }

    /// Observe inbound byte progress for this call.
    #[must_use]
    pub fn on_download_progress(
        mut self,
        callback: impl Fn(u64, Option<u64>) + Send + Sync + 'static,
    ) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.push_progress_hook(
            "download_progress_hook_count",
            ::std::sync::Arc::new(callback),
        );
        self.transmute()
    }

    /// Observe each retry attempt without changing the outcome.
    #[must_use]
    pub fn on_retry(
        mut self,
        callback: impl Fn(u8, &str) + Send + Sync + 'static,
    ) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.push_retry_hook("retry_hook_count", ::std::sync::Arc::new(callback));
        self.transmute()
    }

    /// Observe outbound byte progress for this call.
    #[must_use]
    pub fn on_upload_progress(
        mut self,
        callback: impl Fn(u64, Option<u64>) + Send + Sync + 'static,
    ) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.push_progress_hook(
            "upload_progress_hook_count",
            ::std::sync::Arc::new(callback),
        );
        self.transmute()
    }

    /// Order this call inside the client's outbound queue. Higher drains first.
    #[must_use]
    pub fn queue_priority(mut self, priority: QueuePriority) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("queue_priority", priority.wire_value());
        self.set_wire_header(
            "x-ores-queue-priority",
            format!("{}{}{}", "", priority.wire_value(), ""),
        );
        self.transmute()
    }

    /// Bust intermediate proxy and CDN caches for this call.
    #[must_use]
    pub fn require_fresh(mut self) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("require_fresh", json!(true));
        self.set_wire_header("cache-control", "no-cache".to_owned());
        self.set_wire_header("pragma", "no-cache".to_owned());
        self.transmute()
    }

    /// Bypass the client-side response cache and always open the network.
    #[must_use]
    pub fn skip_cache(mut self) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("skip_local_cache", json!(true));
        self.transmute()
    }

    /// Ask the CDN edge to bypass its cache for this call.
    #[must_use]
    pub fn skip_cloudflare_cache(mut self) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("skip_edge_cache", json!(true));
        self.set_wire_header("cache-control", "no-store".to_owned());
        self.set_wire_header("cf-cache-status", "BYPASS".to_owned());
        self.transmute()
    }

    /// Disable strict TLS validation for this call. Refused unless the client was constructed with the insecure_local_dev capability.
    ///
    /// # Errors
    /// Refused unless the client declares the `insecure_local_dev` capability.
    #[must_use]
    pub fn skip_tls_verify(mut self) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("skip_tls_verify", json!(true));
        self.transmute()
    }

    /// Serve a cached receipt for this many seconds past its TTL while one background call refreshes it.
    #[must_use]
    pub fn stale_while_revalidate(mut self, seconds: u32) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(
            seconds >= 1,
            "stale_while_revalidate: seconds must be at least 1"
        );
        assert!(
            seconds <= 86400,
            "stale_while_revalidate: seconds must be at most 86400"
        );
        self.set_plan("stale_while_revalidate_seconds", json!(seconds));
        self.set_wire_header(
            "cache-control",
            format!("{}{}{}", "stale-while-revalidate=", seconds, ""),
        );
        self.transmute()
    }

    /// Open this call on a fresh connection pool instead of the shared agent.
    #[must_use]
    pub fn use_new_agent(mut self) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("new_agent", json!(true));
        self.transmute()
    }

    /// Route only this call through the given proxy.
    #[must_use]
    pub fn via_proxy(mut self, url: &str) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("proxy_url", json!(url));
        self.transmute()
    }

    /// Replace the whole request body.
    #[must_use]
    pub fn with_body(mut self, body: Value) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_body(body);
        self.transmute()
    }

    /// Cache a successful receipt locally for this many seconds to collapse duplicate outbound calls. Errors and fallbacks are never cached.
    #[must_use]
    pub fn with_cache_ttl(mut self, seconds: u32) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(
            seconds <= 86400,
            "with_cache_ttl: seconds must be at most 86400"
        );
        self.set_plan("cache_ttl_seconds", json!(seconds));
        self.transmute()
    }

    /// Abort at an absolute wall-clock instant and advertise it to the server.
    #[must_use]
    pub fn with_deadline(mut self, unix_millis: i64) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(
            unix_millis >= 0,
            "with_deadline: unix_millis must be at least 0"
        );
        self.set_plan("deadline_unix_millis", json!(unix_millis));
        self.set_wire_header("x-ores-deadline", format!("{}{}{}", "", unix_millis, ""));
        self.transmute()
    }

    /// Resolve with this value instead of failing when the call exhausts its retries.
    #[must_use]
    pub fn with_fallback(mut self, value: Value) -> UnaryCall<Auth, Ip, Rate, Serial> {
        self.set_plan("fallback", json!(value));
        self.transmute()
    }

    /// Retry budget for this call. Only admitted on operations declared idempotent.
    #[must_use]
    pub fn with_retries(mut self, count: u8) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(count <= 16, "with_retries: count must be at most 16");
        self.set_plan("retry_count", json!(count));
        self.transmute()
    }

    /// Exponential backoff schedule applied between retries.
    #[must_use]
    pub fn with_retry_backoff(
        mut self,
        base_millis: u32,
        factor: f64,
    ) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(
            base_millis >= 1,
            "with_retry_backoff: base_millis must be at least 1"
        );
        assert!(
            base_millis <= 60000,
            "with_retry_backoff: base_millis must be at most 60000"
        );
        assert!(
            factor >= 1.0,
            "with_retry_backoff: factor must be at least 1.0"
        );
        assert!(
            factor <= 10.0,
            "with_retry_backoff: factor must be at most 10.0"
        );
        self.set_plan(
            "retry_backoff",
            json!({ "base_millis": base_millis, "factor": factor }),
        );
        self.transmute()
    }

    /// Attach the parent span id for this call.
    #[must_use]
    pub fn with_span_id(mut self, span_id: &str) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(
            span_id.len() <= 32,
            "with_span_id: span_id must be at most 32 characters"
        );
        self.set_plan("span_id", json!(span_id));
        self.transmute()
    }

    /// Abort this call locally after the given elapsed time.
    #[must_use]
    pub fn with_timeout(mut self, millis: u32) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(millis >= 1, "with_timeout: millis must be at least 1");
        assert!(
            millis <= 600000,
            "with_timeout: millis must be at most 600000"
        );
        self.set_plan("timeout_millis", json!(millis));
        self.transmute()
    }

    /// Attach a distributed trace id, propagated on the envelope and copied to the receipt.
    #[must_use]
    pub fn with_trace_id(mut self, trace_id: &str) -> UnaryCall<Auth, Ip, Rate, Serial> {
        assert!(
            trace_id.len() <= 64,
            "with_trace_id: trace_id must be at most 64 characters"
        );
        self.set_plan("trace_id", json!(trace_id));
        self.transmute()
    }
}

/// `auth_mode` is unspent here. Every method below spends it, so a
/// contradictory second selection has no method to call.
impl<Ip, Rate, Serial> UnaryCall<Unset, Ip, Rate, Serial> {
    /// Drop the client's default Authorization header for this call only.
    #[must_use]
    pub fn omit_auth(mut self) -> UnaryCall<Set, Ip, Rate, Serial> {
        self.set_plan("auth_mode", json!("omitted"));
        self.drop_header("authorization");
        self.transmute()
    }

    /// Override the client's default credential for this call only. The token is redacted in plans, logs and debug output.
    ///
    /// The credential reaches the wire but is redacted from every plan.
    #[must_use]
    pub fn with_bearer_token(mut self, token: &str) -> UnaryCall<Set, Ip, Rate, Serial> {
        self.set_plan("auth_mode", json!("bearer_override"));
        self.set_wire_header("authorization", format!("{}{}{}", "Bearer ", token, ""));
        self.mark_secret_header("authorization");
        self.transmute()
    }
}

/// `ip_version` is unspent here. Every method below spends it, so a
/// contradictory second selection has no method to call.
impl<Auth, Rate, Serial> UnaryCall<Auth, Unset, Rate, Serial> {
    /// Pin address-family resolution to IPv4 for this call.
    #[must_use]
    pub fn force_ipv4(mut self) -> UnaryCall<Auth, Set, Rate, Serial> {
        self.set_plan("ip_version", json!("v4"));
        self.transmute()
    }

    /// Pin address-family resolution to IPv6 for this call.
    #[must_use]
    pub fn force_ipv6(mut self) -> UnaryCall<Auth, Set, Rate, Serial> {
        self.set_plan("ip_version", json!("v6"));
        self.transmute()
    }
}

/// `rate_limit` is unspent here. Every method below spends it, so a
/// contradictory second selection has no method to call.
impl<Auth, Ip, Serial> UnaryCall<Auth, Ip, Unset, Serial> {
    /// Send only after the caller has been quiet for this interval. Keyed by operation plus concurrency_key.
    #[must_use]
    pub fn debounce(mut self, millis: u32) -> UnaryCall<Auth, Ip, Set, Serial> {
        assert!(millis >= 1, "debounce: millis must be at least 1");
        assert!(millis <= 60000, "debounce: millis must be at most 60000");
        self.set_plan("debounce_millis", json!(millis));
        self.transmute()
    }

    /// Emit the leading call in each window and discard the rest. Keyed by operation plus concurrency_key.
    #[must_use]
    pub fn throttle(mut self, millis: u32) -> UnaryCall<Auth, Ip, Set, Serial> {
        assert!(millis >= 1, "throttle: millis must be at least 1");
        assert!(millis <= 60000, "throttle: millis must be at most 60000");
        self.set_plan("throttle_millis", json!(millis));
        self.transmute()
    }
}

/// `serialization` is unspent here. Every method below spends it, so a
/// contradictory second selection has no method to call.
impl<Auth, Ip, Rate> UnaryCall<Auth, Ip, Rate, Unset> {
    /// Serialize the envelope as JSON. Default when no strategy is chosen.
    #[must_use]
    pub fn use_json(mut self) -> UnaryCall<Auth, Ip, Rate, Set> {
        self.set_plan("serial_strategy", json!("json"));
        self.set_wire_header("accept", "application/json".to_owned());
        self.set_wire_header("content-type", "application/json".to_owned());
        self.transmute()
    }

    /// Serialize the envelope as MessagePack.
    #[must_use]
    pub fn use_message_pack(mut self) -> UnaryCall<Auth, Ip, Rate, Set> {
        self.set_plan("serial_strategy", json!("message_pack"));
        self.set_wire_header("accept", "application/msgpack".to_owned());
        self.set_wire_header("content-type", "application/msgpack".to_owned());
        self.transmute()
    }

    /// Serialize the envelope as protobuf using the operation's frozen descriptor.
    #[must_use]
    pub fn use_protobuf(mut self) -> UnaryCall<Auth, Ip, Rate, Set> {
        self.set_plan("serial_strategy", json!("protobuf"));
        self.set_wire_header("accept", "application/x-protobuf".to_owned());
        self.set_wire_header("content-type", "application/x-protobuf".to_owned());
        self.transmute()
    }

    /// Select the serialization strategy from a value instead of a dedicated method.
    #[must_use]
    pub fn use_serial_strategy(
        mut self,
        strategy: SerialStrategy,
    ) -> UnaryCall<Auth, Ip, Rate, Set> {
        self.set_plan("serial_strategy", strategy.wire_value());
        for (name, value) in strategy.header_effect() {
            self.set_wire_header(name, (*value).to_owned());
        }
        self.transmute()
    }
}

/// Options available on a streaming chain in any type-state.
impl<Auth, Ip, Serial, StreamRate> StreamCall<Auth, Ip, Serial, StreamRate> {
    /// Set one field on an object request body.
    #[must_use]
    pub fn add_body_field(
        mut self,
        name: &str,
        value: Value,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_body_field(name, value);
        self.transmute()
    }

    /// Set one normalized request header on the call envelope.
    #[must_use]
    pub fn add_header(
        mut self,
        name: &str,
        value: Value,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_header(&name.to_ascii_lowercase(), value);
        self.transmute()
    }

    /// Merge several request headers at once.
    #[must_use]
    pub fn add_headers(
        mut self,
        values: serde_json::Map<String, Value>,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        for (name, value) in values {
            self.set_header(&name.to_ascii_lowercase(), value);
        }
        self.transmute()
    }

    /// Add a uniform random delay up to this bound, to break up thundering herds.
    #[must_use]
    pub fn add_jitter(mut self, millis: u32) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(millis >= 1, "add_jitter: millis must be at least 1");
        assert!(millis <= 60000, "add_jitter: millis must be at most 60000");
        self.set_plan("jitter_millis", json!(millis));
        self.transmute()
    }

    /// Bind one path-template variable.
    #[must_use]
    pub fn add_path_field(
        mut self,
        name: &str,
        value: Value,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_section("path", name, value);
        self.transmute()
    }

    /// Bind one query-string field.
    #[must_use]
    pub fn add_query_field(
        mut self,
        name: &str,
        value: Value,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_section("query", name, value);
        self.transmute()
    }

    /// Force or disable request-payload compression for this call.
    #[must_use]
    pub fn compress(
        mut self,
        compression: Compression,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("compression", compression.wire_value());
        for (name, value) in compression.header_effect() {
            self.set_wire_header(name, (*value).to_owned());
        }
        self.transmute()
    }

    /// Serialize this call against every other call sharing the same named queue.
    #[must_use]
    pub fn concurrency_key(mut self, key: &str) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(
            key.len() <= 128,
            "concurrency_key: key must be at most 128 characters"
        );
        self.set_plan("concurrency_key", json!(key));
        self.transmute()
    }

    /// Log the exact outbound and inbound payload for this call only, with secret options redacted.
    #[must_use]
    pub fn debug(mut self) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("debug", json!(true));
        self.transmute()
    }

    /// Hold the outbound call for a fixed interval before sending.
    #[must_use]
    pub fn delay(mut self, millis: u32) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(millis <= 60000, "delay: millis must be at most 60000");
        self.set_plan("delay_millis", json!(millis));
        self.transmute()
    }

    /// Fail immediately rather than queue when the outbound queue is saturated. For telemetry where dropping beats memory pressure.
    #[must_use]
    pub fn drop_if_busy(mut self) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("drop_if_busy", json!(true));
        self.transmute()
    }

    /// Override connection pooling. Disabling closes the socket immediately after the receipt.
    #[must_use]
    pub fn keep_alive(mut self, enabled: bool) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("keep_alive", json!(enabled));
        self.set_wire_header(
            "connection",
            format!(
                "{}{}{}",
                "",
                if enabled { "keep-alive" } else { "close" },
                ""
            ),
        );
        self.transmute()
    }

    /// Observe inbound byte progress for this call.
    #[must_use]
    pub fn on_download_progress(
        mut self,
        callback: impl Fn(u64, Option<u64>) + Send + Sync + 'static,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.push_progress_hook(
            "download_progress_hook_count",
            ::std::sync::Arc::new(callback),
        );
        self.transmute()
    }

    /// Observe each retry attempt without changing the outcome.
    #[must_use]
    pub fn on_retry(
        mut self,
        callback: impl Fn(u8, &str) + Send + Sync + 'static,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.push_retry_hook("retry_hook_count", ::std::sync::Arc::new(callback));
        self.transmute()
    }

    /// Observe outbound byte progress for this call.
    #[must_use]
    pub fn on_upload_progress(
        mut self,
        callback: impl Fn(u64, Option<u64>) + Send + Sync + 'static,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.push_progress_hook(
            "upload_progress_hook_count",
            ::std::sync::Arc::new(callback),
        );
        self.transmute()
    }

    /// Order this call inside the client's outbound queue. Higher drains first.
    #[must_use]
    pub fn queue_priority(
        mut self,
        priority: QueuePriority,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("queue_priority", priority.wire_value());
        self.set_wire_header(
            "x-ores-queue-priority",
            format!("{}{}{}", "", priority.wire_value(), ""),
        );
        self.transmute()
    }

    /// Bust intermediate proxy and CDN caches for this call.
    #[must_use]
    pub fn require_fresh(mut self) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("require_fresh", json!(true));
        self.set_wire_header("cache-control", "no-cache".to_owned());
        self.set_wire_header("pragma", "no-cache".to_owned());
        self.transmute()
    }

    /// Bypass the client-side response cache and always open the network.
    #[must_use]
    pub fn skip_cache(mut self) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("skip_local_cache", json!(true));
        self.transmute()
    }

    /// Ask the CDN edge to bypass its cache for this call.
    #[must_use]
    pub fn skip_cloudflare_cache(mut self) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("skip_edge_cache", json!(true));
        self.set_wire_header("cache-control", "no-store".to_owned());
        self.set_wire_header("cf-cache-status", "BYPASS".to_owned());
        self.transmute()
    }

    /// Disable strict TLS validation for this call. Refused unless the client was constructed with the insecure_local_dev capability.
    ///
    /// # Errors
    /// Refused unless the client declares the `insecure_local_dev` capability.
    #[must_use]
    pub fn skip_tls_verify(mut self) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("skip_tls_verify", json!(true));
        self.transmute()
    }

    /// Open this call on a fresh connection pool instead of the shared agent.
    #[must_use]
    pub fn use_new_agent(mut self) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("new_agent", json!(true));
        self.transmute()
    }

    /// Route only this call through the given proxy.
    #[must_use]
    pub fn via_proxy(mut self, url: &str) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("proxy_url", json!(url));
        self.transmute()
    }

    /// Decide what happens when the consumer falls behind the producer.
    #[must_use]
    pub fn with_backpressure(
        mut self,
        strategy: Backpressure,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_plan("backpressure", strategy.wire_value());
        self.transmute()
    }

    /// Replace the whole request body.
    #[must_use]
    pub fn with_body(mut self, body: Value) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        self.set_body(body);
        self.transmute()
    }

    /// Abort at an absolute wall-clock instant and advertise it to the server.
    #[must_use]
    pub fn with_deadline(mut self, unix_millis: i64) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(
            unix_millis >= 0,
            "with_deadline: unix_millis must be at least 0"
        );
        self.set_plan("deadline_unix_millis", json!(unix_millis));
        self.set_wire_header("x-ores-deadline", format!("{}{}{}", "", unix_millis, ""));
        self.transmute()
    }

    /// Retry budget for this call. Only admitted on operations declared idempotent.
    #[must_use]
    pub fn with_retries(mut self, count: u8) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(count <= 16, "with_retries: count must be at most 16");
        self.set_plan("retry_count", json!(count));
        self.transmute()
    }

    /// Exponential backoff schedule applied between retries.
    #[must_use]
    pub fn with_retry_backoff(
        mut self,
        base_millis: u32,
        factor: f64,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(
            base_millis >= 1,
            "with_retry_backoff: base_millis must be at least 1"
        );
        assert!(
            base_millis <= 60000,
            "with_retry_backoff: base_millis must be at most 60000"
        );
        assert!(
            factor >= 1.0,
            "with_retry_backoff: factor must be at least 1.0"
        );
        assert!(
            factor <= 10.0,
            "with_retry_backoff: factor must be at most 10.0"
        );
        self.set_plan(
            "retry_backoff",
            json!({ "base_millis": base_millis, "factor": factor }),
        );
        self.transmute()
    }

    /// Attach the parent span id for this call.
    #[must_use]
    pub fn with_span_id(mut self, span_id: &str) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(
            span_id.len() <= 32,
            "with_span_id: span_id must be at most 32 characters"
        );
        self.set_plan("span_id", json!(span_id));
        self.transmute()
    }

    /// Bound the number of buffered inbound items before the backpressure strategy applies.
    #[must_use]
    pub fn with_stream_buffer(mut self, capacity: u32) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(
            capacity >= 1,
            "with_stream_buffer: capacity must be at least 1"
        );
        assert!(
            capacity <= 65536,
            "with_stream_buffer: capacity must be at most 65536"
        );
        self.set_plan("stream_buffer_capacity", json!(capacity));
        self.transmute()
    }

    /// Fail the stream when no frame arrives for this long. Distinct from the total-call timeout.
    #[must_use]
    pub fn with_stream_idle_timeout(
        mut self,
        millis: u32,
    ) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(
            millis >= 1,
            "with_stream_idle_timeout: millis must be at least 1"
        );
        assert!(
            millis <= 3600000,
            "with_stream_idle_timeout: millis must be at most 3600000"
        );
        self.set_plan("stream_idle_timeout_millis", json!(millis));
        self.transmute()
    }

    /// Abort this call locally after the given elapsed time.
    #[must_use]
    pub fn with_timeout(mut self, millis: u32) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(millis >= 1, "with_timeout: millis must be at least 1");
        assert!(
            millis <= 600000,
            "with_timeout: millis must be at most 600000"
        );
        self.set_plan("timeout_millis", json!(millis));
        self.transmute()
    }

    /// Attach a distributed trace id, propagated on the envelope and copied to the receipt.
    #[must_use]
    pub fn with_trace_id(mut self, trace_id: &str) -> StreamCall<Auth, Ip, Serial, StreamRate> {
        assert!(
            trace_id.len() <= 64,
            "with_trace_id: trace_id must be at most 64 characters"
        );
        self.set_plan("trace_id", json!(trace_id));
        self.transmute()
    }
}

/// `auth_mode` is unspent here. Every method below spends it, so a
/// contradictory second selection has no method to call.
impl<Ip, Serial, StreamRate> StreamCall<Unset, Ip, Serial, StreamRate> {
    /// Drop the client's default Authorization header for this call only.
    #[must_use]
    pub fn omit_auth(mut self) -> StreamCall<Set, Ip, Serial, StreamRate> {
        self.set_plan("auth_mode", json!("omitted"));
        self.drop_header("authorization");
        self.transmute()
    }

    /// Override the client's default credential for this call only. The token is redacted in plans, logs and debug output.
    ///
    /// The credential reaches the wire but is redacted from every plan.
    #[must_use]
    pub fn with_bearer_token(mut self, token: &str) -> StreamCall<Set, Ip, Serial, StreamRate> {
        self.set_plan("auth_mode", json!("bearer_override"));
        self.set_wire_header("authorization", format!("{}{}{}", "Bearer ", token, ""));
        self.mark_secret_header("authorization");
        self.transmute()
    }
}

/// `ip_version` is unspent here. Every method below spends it, so a
/// contradictory second selection has no method to call.
impl<Auth, Serial, StreamRate> StreamCall<Auth, Unset, Serial, StreamRate> {
    /// Pin address-family resolution to IPv4 for this call.
    #[must_use]
    pub fn force_ipv4(mut self) -> StreamCall<Auth, Set, Serial, StreamRate> {
        self.set_plan("ip_version", json!("v4"));
        self.transmute()
    }

    /// Pin address-family resolution to IPv6 for this call.
    #[must_use]
    pub fn force_ipv6(mut self) -> StreamCall<Auth, Set, Serial, StreamRate> {
        self.set_plan("ip_version", json!("v6"));
        self.transmute()
    }
}

/// `serialization` is unspent here. Every method below spends it, so a
/// contradictory second selection has no method to call.
impl<Auth, Ip, StreamRate> StreamCall<Auth, Ip, Unset, StreamRate> {
    /// Serialize the envelope as JSON. Default when no strategy is chosen.
    #[must_use]
    pub fn use_json(mut self) -> StreamCall<Auth, Ip, Set, StreamRate> {
        self.set_plan("serial_strategy", json!("json"));
        self.set_wire_header("accept", "application/json".to_owned());
        self.set_wire_header("content-type", "application/json".to_owned());
        self.transmute()
    }

    /// Serialize the envelope as MessagePack.
    #[must_use]
    pub fn use_message_pack(mut self) -> StreamCall<Auth, Ip, Set, StreamRate> {
        self.set_plan("serial_strategy", json!("message_pack"));
        self.set_wire_header("accept", "application/msgpack".to_owned());
        self.set_wire_header("content-type", "application/msgpack".to_owned());
        self.transmute()
    }

    /// Serialize the envelope as protobuf using the operation's frozen descriptor.
    #[must_use]
    pub fn use_protobuf(mut self) -> StreamCall<Auth, Ip, Set, StreamRate> {
        self.set_plan("serial_strategy", json!("protobuf"));
        self.set_wire_header("accept", "application/x-protobuf".to_owned());
        self.set_wire_header("content-type", "application/x-protobuf".to_owned());
        self.transmute()
    }

    /// Select the serialization strategy from a value instead of a dedicated method.
    #[must_use]
    pub fn use_serial_strategy(
        mut self,
        strategy: SerialStrategy,
    ) -> StreamCall<Auth, Ip, Set, StreamRate> {
        self.set_plan("serial_strategy", strategy.wire_value());
        for (name, value) in strategy.header_effect() {
            self.set_wire_header(name, (*value).to_owned());
        }
        self.transmute()
    }
}

/// `stream_rate_limit` is unspent here. Every method below spends it, so a
/// contradictory second selection has no method to call.
impl<Auth, Ip, Serial> StreamCall<Auth, Ip, Serial, Unset> {
    /// Emit an item only after the producer has been quiet for this interval.
    #[must_use]
    pub fn debounce_each(mut self, millis: u32) -> StreamCall<Auth, Ip, Serial, Set> {
        assert!(millis >= 1, "debounce_each: millis must be at least 1");
        assert!(
            millis <= 60000,
            "debounce_each: millis must be at most 60000"
        );
        self.set_plan("debounce_each_millis", json!(millis));
        self.transmute()
    }

    /// Emit the most recent item once per interval.
    #[must_use]
    pub fn sample_each(mut self, millis: u32) -> StreamCall<Auth, Ip, Serial, Set> {
        assert!(millis >= 1, "sample_each: millis must be at least 1");
        assert!(millis <= 60000, "sample_each: millis must be at most 60000");
        self.set_plan("sample_each_millis", json!(millis));
        self.transmute()
    }

    /// Emit the leading item in each interval and drop the rest.
    #[must_use]
    pub fn throttle_each(mut self, millis: u32) -> StreamCall<Auth, Ip, Serial, Set> {
        assert!(millis >= 1, "throttle_each: millis must be at least 1");
        assert!(
            millis <= 60000,
            "throttle_each: millis must be at most 60000"
        );
        self.set_plan("throttle_each_millis", json!(millis));
        self.transmute()
    }
}
