//! Filesystem server glue for the preferred shared-operation RPC model.
//!
//! This generator is additive while the fleet migrates. Legacy
//! `api_server_glue` continues to project RPC through operation-local Axum
//! routers. `api_server_shared_operation_glue` instead verifies every
//! `#[ores_route(operation = ...)]` against its `#[ores_operation]`, verifies
//! that the HTTP adapter calls the generated invoker exactly once, and emits
//! `/v1/rpc` handlers that call that same invoker directly.

use std::{collections::{BTreeMap, BTreeSet}, fs, path::{Path, PathBuf}};

use crate::{
    analyze_http_route_source, verified_rpc_operation_contract, FsRoute, FsRouteKind,
    RouteMap, RpcOperationScope,
};

const RPC_V1_CANONICAL_PATH: &str = "/v1/rpc";
const RPC_V1_LEGACY_PATH: &str = "/rpc/v1";

pub fn api_server_shared_operation_glue(
    repo_root: &Path,
    routes: &[FsRoute],
    route_map: &RouteMap,
    scope: RpcOperationScope,
) -> Result<String, String> {
    let mut out = String::from("// @generated by ores-api-docs shared-operation RPC; do not edit\n");
    let mut mounts = Vec::new();
    let mut http_rows = Vec::new();
    let mut binding_rows = Vec::new();
    let mut handler_rows = Vec::new();

    for route in routes {
        if route.kind != FsRouteKind::ApiHandler {
            return Err(format!("{} is not an API route", route.source));
        }

        let canonical = route.canonical_path();
        reject_reserved_rpc_path(&route.source, &canonical)?;
        let source_path = absolute_source(repo_root, &route.source)?;
        let source_text = fs::read_to_string(&source_path)
            .map_err(|error| format!("read {}: {error}", source_path.display()))?;
        let http_analysis = analyze_http_route_source(&route.source, &source_text)
            .map_err(|error| error.to_string())?;
        let operations = expected_http_operations_by_method(route_map, &canonical)?;
        let source_methods = http_analysis.methods();
        let contract_methods = operations.keys().map(String::as_str).collect::<BTreeSet<_>>();
        if source_methods != contract_methods {
            return Err(format!(
                "{} derives {canonical}: public route.rs verbs {:?} != api-docs HTTP methods {:?}",
                route.source, source_methods, contract_methods
            ));
        }

        let module = module_ident("route", &route.source);
        let literal = format!("{:?}", source_path.to_string_lossy());
        out.push_str(&format!("#[path = {literal}]\nmod {module};\n"));
        let method_router = method_router_expression(&module, &http_analysis.handlers)?;
        for axum_path in route.axum_paths() {
            mounts.push(format!("        .route({axum_path:?}, {method_router})\n"));
        }

        for (method, route_key) in operations {
            let contract = verified_rpc_operation_contract(
                route_map,
                route_key,
                scope,
                None,
                None,
                &route.source,
                &source_text,
            )?;
            let operation_fn = contract.source.operation.as_deref().ok_or_else(|| {
                format!("{route_key}: verified shared operation did not expose operation function")
            })?;
            let invoker_fn = contract.source.invoker.as_deref().ok_or_else(|| {
                format!("{route_key}: verified shared operation did not expose generated invoker")
            })?;
            if contract.source.execution_model != "shared_operation" {
                return Err(format!(
                    "{route_key}: shared-operation generator refuses execution model {:?}",
                    contract.source.execution_model
                ));
            }

            http_rows.push(format!(
                "    ({:?}, {:?}, {:?}, {:?}, {:?}, {:?}),\n",
                contract.operation_key,
                method,
                canonical,
                route.source,
                operation_fn,
                invoker_fn,
            ));
            binding_rows.push(format!(
                "    ::ores_api_docs::RpcV1SharedOperationBinding::new({:?}, {:?}, {:?}, {:?}),\n",
                contract.operation_key, route.source, operation_fn, invoker_fn,
            ));

            handler_rows.push(format!(
                "                {{\n\
                     let __ores_operation_state = __ores_state.clone();\n\
                     let __ores_handler: ::ores_api_docs::RpcV1SharedOperationHandler = ::std::sync::Arc::new(\n\
                         move |__ores_rpc_http_context, __ores_call| {{\n\
                             let __ores_operation_state = __ores_operation_state.clone();\n\
                             Box::pin(async move {{\n\
                                 ::ores_api_docs::invoke_shared_rpc_operation(\n\
                                     ::ores_api_docs::OperationContext::rpc(\n\
                                         __ores_operation_state,\n\
                                         __ores_rpc_http_context,\n\
                                     ),\n\
                                     __ores_call,\n\
                                     {module}::{invoker_fn},\n\
                                 ).await\n\
                             }})\n\
                         }}\n\
                     );\n\
                     __ores_rpc_handlers.insert({wire_key:?}.to_owned(), __ores_handler);\n\
                 }}\n",
                wire_key = contract.operation_key,
            ));
        }
    }

    out.push_str(
        "\n/// Ordinary filesystem REST surface. RPC is generated separately and calls\n\
         /// the same typed operation invokers without re-entering this router.\n\
         #[allow(unused_macros)]\n\
         macro_rules! __ores_filesystem_api_router {\n\
             () => {{\n\
                 ::axum::Router::new()\n",
    );
    for mount in mounts {
        out.push_str(&mount);
    }
    out.push_str("            }};\n        }\n\n");
    out.push_str("pub(crate) use __ores_filesystem_api_router;\n\n");

    out.push_str(
        "/// (stable RPC key, HTTP method, REST path, route.rs, operation fn, invoker fn).\n\
         pub static __ORES_SHARED_OPERATION_INVENTORY: &[(&str, &str, &str, &str, &str, &str)] = &[\n",
    );
    for row in http_rows {
        out.push_str(&row);
    }
    out.push_str("];\n\n");

    out.push_str(
        "pub static __ORES_SHARED_RPC_BINDINGS: &[::ores_api_docs::RpcV1SharedOperationBinding] = &[\n",
    );
    for row in binding_rows {
        out.push_str(&row);
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// Build REST plus `/v1/rpc` from the same typed operation functions.\n\
         /// The RPC side never constructs a synthetic REST request.\n\
         #[allow(unused_macros)]\n\
         macro_rules! __ores_filesystem_api_shared_rpc_router {\n\
             ($state:expr, $route_map:expr) => {{\n\
                 let __ores_state = $state;\n\
                 let __ores_http = __ores_filesystem_api_router!()\n\
                     .with_state(__ores_state.clone());\n\
                 let mut __ores_rpc_handlers = ::std::collections::BTreeMap::new();\n",
    );
    for row in handler_rows {
        out.push_str(&row);
    }
    out.push_str(
        "                ::ores_api_docs::shared_operation_rpc_v1_router(\n\
                     $route_map, __ORES_SHARED_RPC_BINDINGS, __ores_rpc_handlers\n\
                 ).map(|__ores_rpc| __ores_http.merge(__ores_rpc))\n\
             }};\n\
         }\n\n\
         pub(crate) use __ores_filesystem_api_shared_rpc_router;\n",
    );

    Ok(out)
}

fn expected_http_operations_by_method<'a>(
    route_map: &'a RouteMap,
    canonical: &str,
) -> Result<BTreeMap<String, &'a str>, String> {
    let mut operations = BTreeMap::new();
    for (key, entry) in &route_map.map {
        if entry.path != canonical || !entry.transports.iter().any(|value| value == "http") {
            continue;
        }
        if entry.methods.len() != 1 {
            return Err(format!(
                "api-docs operation {key:?} at {canonical} declares methods {:?}; shared-operation RPC requires one operation per HTTP verb",
                entry.methods
            ));
        }
        let method = entry.methods[0].to_ascii_uppercase();
        if let Some(other) = operations.insert(method.clone(), key.as_str()) {
            return Err(format!(
                "api-docs operations {other:?} and {key:?} both own {method} {canonical}"
            ));
        }
    }
    if operations.is_empty() {
        return Err(format!("{canonical} has no HTTP operation in the api-docs route map"));
    }
    Ok(operations)
}

fn method_router_expression(
    module: &str,
    handlers: &[crate::HttpRouteHandlerSource],
) -> Result<String, String> {
    let mut handlers = handlers.to_vec();
    handlers.sort_by_key(|handler| method_order(&handler.method));
    let Some(first) = handlers.first() else {
        return Err("route module has no handlers".to_owned());
    };
    let mut expression = format!(
        "::axum::routing::{}({module}::{})",
        first.rust_name, first.rust_name
    );
    for handler in handlers.iter().skip(1) {
        expression.push_str(&format!(
            ".{}({module}::{})",
            handler.rust_name, handler.rust_name
        ));
    }
    Ok(expression)
}

fn method_order(method: &str) -> usize {
    match method {
        "GET" => 0,
        "POST" => 1,
        "PUT" => 2,
        "PATCH" => 3,
        "DELETE" => 4,
        "HEAD" => 5,
        "OPTIONS" => 6,
        _ => usize::MAX,
    }
}

fn reject_reserved_rpc_path(source: &str, canonical: &str) -> Result<(), String> {
    if matches!(canonical, RPC_V1_CANONICAL_PATH | RPC_V1_LEGACY_PATH) {
        return Err(format!(
            "{source} derives reserved RPC transport path {canonical}; /v1/rpc is runtime-owned and cannot be authored as route.rs"
        ));
    }
    Ok(())
}

fn absolute_source(repo_root: &Path, source: &str) -> Result<PathBuf, String> {
    let root = repo_root
        .canonicalize()
        .map_err(|error| format!("canonicalize {}: {error}", repo_root.display()))?;
    let path = root.join(source);
    if !path.is_file() {
        return Err(format!("route source does not exist: {}", path.display()));
    }
    Ok(path)
}

fn module_ident(prefix: &str, source: &str) -> String {
    let mut out = format!("__ores_{prefix}_");
    for ch in source.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn shared_glue_calls_invoker_not_http_handler_for_rpc() {
        let root = tempdir().expect("temp repo");
        let route_dir = root.path().join("src/routes/v1/users/[user_id]");
        fs::create_dir_all(&route_dir).expect("route dir");
        fs::write(
            route_dir.join("route.rs"),
            r#"
                #[ores_operation(
                    key = "demo.users.find_user",
                    scope = "regular"
                )]
                async fn find_user(
                    ctx: OperationContext<AppState>,
                    input: FindUserInput,
                ) -> Result<FindUserOutput, FindUserError> { todo!() }

                #[ores_route(operation = find_user)]
                pub async fn get() -> HttpResult {
                    __ores_invoke_find_user(ctx, input).await.into()
                }
            "#,
        )
        .expect("route source");

        let routes = vec![FsRoute::new_for_test(
            FsRouteKind::ApiHandler,
            "src/routes/v1/users/[user_id]/route.rs",
            vec![
                FsRouteSegment::Static("v1".into()),
                FsRouteSegment::Static("users".into()),
                FsRouteSegment::Dynamic("user_id".into()),
            ],
        )];
        let map = RouteMap::from_json_str(
            r#"{
              "schema_version":"1.0.0",
              "service":"demo",
              "map":{
                "find_user_by_id":{
                  "path":"/v1/users/{user_id}",
                  "methods":["GET"],
                  "rpc_key":"demo.users.find_user",
                  "binding":{"annotation":"ores_operation","file":"src/routes/v1/users/[user_id]/route.rs"}
                }
              }
            }"#,
        )
        .expect("route map");

        let generated = api_server_shared_operation_glue(
            root.path(),
            &routes,
            &map,
            RpcOperationScope::Regular,
        )
        .expect("shared glue");
        assert!(generated.contains("__ores_invoke_find_user"));
        assert!(generated.contains("invoke_shared_rpc_operation"));
        assert!(!generated.contains("axum_rpc_operation_handler"));
    }
}
