// Generated by `cargo run --bin ores-rpc-docs -- generate`. Do not edit by hand.

import type {
  RpcJsonObject,
  RpcOutcome,
  RpcRequestPlan,
  RpcStreamHandle,
} from "./fluent-types.js";

export declare const CATALOG_VERSION: string;
export declare const DEFAULT_RPC_PATH: string;
export declare const PLAN_VERSION: "1.0.0";

export type StratValue = "json" | "message_pack" | "protobuf";
export type CompressionValue = "identity" | "gzip" | "brotli" | "zstd";
export type QPriorityValue = 0 | 1 | 2 | 3 | 4;
export type BackpressureValue = "buffer" | "drop_oldest" | "drop_newest" | "error";

/** Exclusive groups are phantom markers on the builder type. */
export type RpcExclusiveGroup = "auth_mode" | "ip_version" | "rate_limit" | "serialization" | "stream_rate_limit";

export interface RpcOptionDescriptor {
  readonly id: string;
  readonly method: string;
  readonly group: string;
  readonly appliesTo: "unary" | "stream" | "both";
  readonly arity: "once" | "many";
  readonly exclusiveGroup: RpcExclusiveGroup | null;
  readonly planField: string | null;
  readonly planValue?: unknown;
  readonly secret: boolean;
  readonly localOnly: boolean;
  readonly requiresCapability: string | null;
  readonly params: ReadonlyArray<{ readonly name: string; readonly type: string; readonly enumId?: string; readonly minimum?: number; readonly maximum?: number; readonly maxLength?: number }>;
  readonly wire: unknown;
}

export declare const REDACTED: string;
export declare const REDACTED_HEADER_NAMES: ReadonlyArray<string>;
export declare const REDACTED_HEADER_PATTERNS: ReadonlyArray<string>;
export declare const REDACTED_URL_FIELDS: ReadonlyArray<string>;
export declare const REDACTED_URL_USERINFO: string;
export declare const LIST_VALUED_HEADERS: ReadonlyArray<string>;
export declare const REDACTED_QUERY_NAMES: ReadonlyArray<string>;
export declare const OPTIONS: ReadonlyArray<RpcOptionDescriptor>;
export declare const OPTIONS_BY_SURFACE: { readonly unary: ReadonlyArray<RpcOptionDescriptor>; readonly stream: ReadonlyArray<RpcOptionDescriptor> };
export declare const EXCLUSIVE_GROUPS: ReadonlyArray<RpcExclusiveGroup>;
export declare const ENUM_HEADER_EFFECTS: Readonly<Record<string, Readonly<Record<string, Readonly<Record<string, string>>>>>>;

export declare const Rpc: {
  readonly Strat: {
    readonly json: "json";
    readonly messagePack: "message_pack";
    readonly protobuf: "protobuf";
  };
  readonly Compression: {
    readonly identity: "identity";
    readonly gzip: "gzip";
    readonly brotli: "brotli";
    readonly zstd: "zstd";
  };
  readonly QPriority: {
    readonly zero: 0;
    readonly one: 1;
    readonly two: 2;
    readonly three: 3;
    readonly four: 4;
  };
  readonly Backpressure: {
    readonly buffer: "buffer";
    readonly dropOldest: "drop_oldest";
    readonly dropNewest: "drop_newest";
    readonly error: "error";
  };
};

export interface RpcUnaryCallBuilderCore<T = unknown, E = RpcJsonObject, Used extends RpcExclusiveGroup = never> {
  /** Set one field on an object request body. */
  addBodyField(name: string, value: unknown): RpcUnaryCallBuilder<T, E, Used>;
  /** Set one normalized request header on the call envelope. */
  addHeader(name: string, value: unknown): RpcUnaryCallBuilder<T, E, Used>;
  /** Merge several request headers at once. */
  addHeaders(values: RpcJsonObject): RpcUnaryCallBuilder<T, E, Used>;
  /** Add a uniform random delay up to this bound, to break up thundering herds. */
  addJitter(millis: number): RpcUnaryCallBuilder<T, E, Used>;
  /** Bind one path-template variable. */
  addPathField(name: string, value: unknown): RpcUnaryCallBuilder<T, E, Used>;
  /** Bind one query-string field. */
  addQueryField(name: string, value: unknown): RpcUnaryCallBuilder<T, E, Used>;
  /** Force or disable request-payload compression for this call. */
  compress(compression: CompressionValue): RpcUnaryCallBuilder<T, E, Used>;
  /** Serialize this call against every other call sharing the same named queue. */
  concurrencyKey(key: string): RpcUnaryCallBuilder<T, E, Used>;
  /** Log the exact outbound and inbound payload for this call only, with secret options redacted. */
  debug(): RpcUnaryCallBuilder<T, E, Used>;
  /** Join an identical in-flight call instead of opening a second socket. Both callers receive the same receipt. */
  dedupe(): RpcUnaryCallBuilder<T, E, Used>;
  /** Hold the outbound call for a fixed interval before sending. */
  delay(millis: number): RpcUnaryCallBuilder<T, E, Used>;
  /** Fail immediately rather than queue when the outbound queue is saturated. For telemetry where dropping beats memory pressure. */
  dropIfBusy(): RpcUnaryCallBuilder<T, E, Used>;
  /** Validate payload, headers and authorization server-side without executing the mutation. */
  dryRun(): RpcUnaryCallBuilder<T, E, Used>;
  /** Override connection pooling. Disabling closes the socket immediately after the receipt. */
  keepAlive(enabled: boolean): RpcUnaryCallBuilder<T, E, Used>;
  /** Observe inbound byte progress for this call. */
  onDownloadProgress(callback: (receivedBytes: number, totalBytes: number | null) => void): RpcUnaryCallBuilder<T, E, Used>;
  /** Observe each retry attempt without changing the outcome. */
  onRetry(callback: (attempt: number, cause: unknown) => void): RpcUnaryCallBuilder<T, E, Used>;
  /** Observe outbound byte progress for this call. */
  onUploadProgress(callback: (sentBytes: number, totalBytes: number | null) => void): RpcUnaryCallBuilder<T, E, Used>;
  /** Order this call inside the client's outbound queue. Higher drains first. */
  queuePriority(priority: QPriorityValue): RpcUnaryCallBuilder<T, E, Used>;
  /** Bust intermediate proxy and CDN caches for this call. */
  requireFresh(): RpcUnaryCallBuilder<T, E, Used>;
  /** Bypass the client-side response cache and always open the network. */
  skipCache(): RpcUnaryCallBuilder<T, E, Used>;
  /** Ask the CDN edge to bypass its cache for this call. */
  skipCloudflareCache(): RpcUnaryCallBuilder<T, E, Used>;
  /** Disable strict TLS validation for this call. Refused unless the client was constructed with the insecure_local_dev capability. */
  skipTlsVerify(): RpcUnaryCallBuilder<T, E, Used>;
  /** Serve a cached receipt for this many seconds past its TTL while one background call refreshes it. */
  staleWhileRevalidate(seconds: number): RpcUnaryCallBuilder<T, E, Used>;
  /** Open this call on a fresh connection pool instead of the shared agent. */
  useNewAgent(): RpcUnaryCallBuilder<T, E, Used>;
  /** Route only this call through the given proxy. */
  viaProxy(url: string): RpcUnaryCallBuilder<T, E, Used>;
  /** Replace the whole request body. */
  withBody(body: unknown): RpcUnaryCallBuilder<T, E, Used>;
  /** Cache a successful receipt locally for this many seconds to collapse duplicate outbound calls. Errors and fallbacks are never cached. */
  withCacheTtl(seconds: number): RpcUnaryCallBuilder<T, E, Used>;
  /** Abort at an absolute wall-clock instant and advertise it to the server. */
  withDeadline(unixMillis: number): RpcUnaryCallBuilder<T, E, Used>;
  /** Resolve with this value instead of failing when the call exhausts its retries. */
  withFallback(value: unknown): RpcUnaryCallBuilder<T, E, Used>;
  /** Retry budget for this call. Only admitted on operations declared idempotent. */
  withRetries(count: number): RpcUnaryCallBuilder<T, E, Used>;
  /** Exponential backoff schedule applied between retries. */
  withRetryBackoff(baseMillis: number, factor: number): RpcUnaryCallBuilder<T, E, Used>;
  /** Attach the parent span id for this call. */
  withSpanId(spanId: string): RpcUnaryCallBuilder<T, E, Used>;
  /** Abort this call locally after the given elapsed time. */
  withTimeout(millis: number): RpcUnaryCallBuilder<T, E, Used>;
  /** Attach a distributed trace id, propagated on the envelope and copied to the receipt. */
  withTraceId(traceId: string): RpcUnaryCallBuilder<T, E, Used>;
  /** Serialize the chain to a canonical request plan without opening the network. */
  toPlan(): RpcRequestPlan;
  /** Execute the call. The sole network boundary of the unary client. */
  makeCall(): Promise<RpcOutcome<T, E>>;
  /** Execute the call and raise on a failed receipt. */
  makeCallOrThrow(): Promise<T>;
}

export interface RpcUnaryCallBuilderAuthMode<T = unknown, E = RpcJsonObject, Used extends RpcExclusiveGroup = never> {
  /** Drop the client's default Authorization header for this call only. */
  omitAuth(): RpcUnaryCallBuilder<T, E, Used | "auth_mode">;
  /** Override the client's default credential for this call only. The token is redacted in plans, logs and debug output. */
  withBearerToken(token: string): RpcUnaryCallBuilder<T, E, Used | "auth_mode">;
}

export interface RpcUnaryCallBuilderIpVersion<T = unknown, E = RpcJsonObject, Used extends RpcExclusiveGroup = never> {
  /** Pin address-family resolution to IPv4 for this call. */
  forceIpv4(): RpcUnaryCallBuilder<T, E, Used | "ip_version">;
  /** Pin address-family resolution to IPv6 for this call. */
  forceIpv6(): RpcUnaryCallBuilder<T, E, Used | "ip_version">;
}

export interface RpcUnaryCallBuilderRateLimit<T = unknown, E = RpcJsonObject, Used extends RpcExclusiveGroup = never> {
  /** Send only after the caller has been quiet for this interval. Keyed by operation plus concurrency_key. */
  debounce(millis: number): RpcUnaryCallBuilder<T, E, Used | "rate_limit">;
  /** Emit the leading call in each window and discard the rest. Keyed by operation plus concurrency_key. */
  throttle(millis: number): RpcUnaryCallBuilder<T, E, Used | "rate_limit">;
}

export interface RpcUnaryCallBuilderSerialization<T = unknown, E = RpcJsonObject, Used extends RpcExclusiveGroup = never> {
  /** Serialize the envelope as JSON. Default when no strategy is chosen. */
  useJson(): RpcUnaryCallBuilder<T, E, Used | "serialization">;
  /** Serialize the envelope as MessagePack. */
  useMessagePack(): RpcUnaryCallBuilder<T, E, Used | "serialization">;
  /** Serialize the envelope as protobuf using the operation's frozen descriptor. */
  useProtobuf(): RpcUnaryCallBuilder<T, E, Used | "serialization">;
  /** Select the serialization strategy from a value instead of a dedicated method. */
  useSerialStrategy(strategy: StratValue): RpcUnaryCallBuilder<T, E, Used | "serialization">;
}

/**
 * A unary RPC chain. Spending an exclusive group removes it from the type, so
 * a contradictory second selection is a compile error.
 */
export type RpcUnaryCallBuilder<T = unknown, E = RpcJsonObject, Used extends RpcExclusiveGroup = never> =
  RpcUnaryCallBuilderCore<T, E, Used>
  & ("auth_mode" extends Used ? {} : RpcUnaryCallBuilderAuthMode<T, E, Used>)
  & ("ip_version" extends Used ? {} : RpcUnaryCallBuilderIpVersion<T, E, Used>)
  & ("rate_limit" extends Used ? {} : RpcUnaryCallBuilderRateLimit<T, E, Used>)
  & ("serialization" extends Used ? {} : RpcUnaryCallBuilderSerialization<T, E, Used>);

export interface RpcStreamCallBuilderCore<T = unknown, Used extends RpcExclusiveGroup = never> {
  /** Set one field on an object request body. */
  addBodyField(name: string, value: unknown): RpcStreamCallBuilder<T, Used>;
  /** Set one normalized request header on the call envelope. */
  addHeader(name: string, value: unknown): RpcStreamCallBuilder<T, Used>;
  /** Merge several request headers at once. */
  addHeaders(values: RpcJsonObject): RpcStreamCallBuilder<T, Used>;
  /** Add a uniform random delay up to this bound, to break up thundering herds. */
  addJitter(millis: number): RpcStreamCallBuilder<T, Used>;
  /** Bind one path-template variable. */
  addPathField(name: string, value: unknown): RpcStreamCallBuilder<T, Used>;
  /** Bind one query-string field. */
  addQueryField(name: string, value: unknown): RpcStreamCallBuilder<T, Used>;
  /** Force or disable request-payload compression for this call. */
  compress(compression: CompressionValue): RpcStreamCallBuilder<T, Used>;
  /** Serialize this call against every other call sharing the same named queue. */
  concurrencyKey(key: string): RpcStreamCallBuilder<T, Used>;
  /** Log the exact outbound and inbound payload for this call only, with secret options redacted. */
  debug(): RpcStreamCallBuilder<T, Used>;
  /** Hold the outbound call for a fixed interval before sending. */
  delay(millis: number): RpcStreamCallBuilder<T, Used>;
  /** Fail immediately rather than queue when the outbound queue is saturated. For telemetry where dropping beats memory pressure. */
  dropIfBusy(): RpcStreamCallBuilder<T, Used>;
  /** Override connection pooling. Disabling closes the socket immediately after the receipt. */
  keepAlive(enabled: boolean): RpcStreamCallBuilder<T, Used>;
  /** Observe inbound byte progress for this call. */
  onDownloadProgress(callback: (receivedBytes: number, totalBytes: number | null) => void): RpcStreamCallBuilder<T, Used>;
  /** Observe each retry attempt without changing the outcome. */
  onRetry(callback: (attempt: number, cause: unknown) => void): RpcStreamCallBuilder<T, Used>;
  /** Observe outbound byte progress for this call. */
  onUploadProgress(callback: (sentBytes: number, totalBytes: number | null) => void): RpcStreamCallBuilder<T, Used>;
  /** Order this call inside the client's outbound queue. Higher drains first. */
  queuePriority(priority: QPriorityValue): RpcStreamCallBuilder<T, Used>;
  /** Bust intermediate proxy and CDN caches for this call. */
  requireFresh(): RpcStreamCallBuilder<T, Used>;
  /** Bypass the client-side response cache and always open the network. */
  skipCache(): RpcStreamCallBuilder<T, Used>;
  /** Ask the CDN edge to bypass its cache for this call. */
  skipCloudflareCache(): RpcStreamCallBuilder<T, Used>;
  /** Disable strict TLS validation for this call. Refused unless the client was constructed with the insecure_local_dev capability. */
  skipTlsVerify(): RpcStreamCallBuilder<T, Used>;
  /** Open this call on a fresh connection pool instead of the shared agent. */
  useNewAgent(): RpcStreamCallBuilder<T, Used>;
  /** Route only this call through the given proxy. */
  viaProxy(url: string): RpcStreamCallBuilder<T, Used>;
  /** Decide what happens when the consumer falls behind the producer. */
  withBackpressure(strategy: BackpressureValue): RpcStreamCallBuilder<T, Used>;
  /** Replace the whole request body. */
  withBody(body: unknown): RpcStreamCallBuilder<T, Used>;
  /** Abort at an absolute wall-clock instant and advertise it to the server. */
  withDeadline(unixMillis: number): RpcStreamCallBuilder<T, Used>;
  /** Retry budget for this call. Only admitted on operations declared idempotent. */
  withRetries(count: number): RpcStreamCallBuilder<T, Used>;
  /** Exponential backoff schedule applied between retries. */
  withRetryBackoff(baseMillis: number, factor: number): RpcStreamCallBuilder<T, Used>;
  /** Attach the parent span id for this call. */
  withSpanId(spanId: string): RpcStreamCallBuilder<T, Used>;
  /** Bound the number of buffered inbound items before the backpressure strategy applies. */
  withStreamBuffer(capacity: number): RpcStreamCallBuilder<T, Used>;
  /** Fail the stream when no frame arrives for this long. Distinct from the total-call timeout. */
  withStreamIdleTimeout(millis: number): RpcStreamCallBuilder<T, Used>;
  /** Abort this call locally after the given elapsed time. */
  withTimeout(millis: number): RpcStreamCallBuilder<T, Used>;
  /** Attach a distributed trace id, propagated on the envelope and copied to the receipt. */
  withTraceId(traceId: string): RpcStreamCallBuilder<T, Used>;
  /** Serialize the chain to a canonical request plan without opening the network. */
  toPlan(): RpcRequestPlan;
  /** Open the stream. The sole network boundary of the streaming client. */
  stream(): Promise<RpcStreamHandle<T>>;
}

export interface RpcStreamCallBuilderAuthMode<T = unknown, Used extends RpcExclusiveGroup = never> {
  /** Drop the client's default Authorization header for this call only. */
  omitAuth(): RpcStreamCallBuilder<T, Used | "auth_mode">;
  /** Override the client's default credential for this call only. The token is redacted in plans, logs and debug output. */
  withBearerToken(token: string): RpcStreamCallBuilder<T, Used | "auth_mode">;
}

export interface RpcStreamCallBuilderIpVersion<T = unknown, Used extends RpcExclusiveGroup = never> {
  /** Pin address-family resolution to IPv4 for this call. */
  forceIpv4(): RpcStreamCallBuilder<T, Used | "ip_version">;
  /** Pin address-family resolution to IPv6 for this call. */
  forceIpv6(): RpcStreamCallBuilder<T, Used | "ip_version">;
}

export interface RpcStreamCallBuilderSerialization<T = unknown, Used extends RpcExclusiveGroup = never> {
  /** Serialize the envelope as JSON. Default when no strategy is chosen. */
  useJson(): RpcStreamCallBuilder<T, Used | "serialization">;
  /** Serialize the envelope as MessagePack. */
  useMessagePack(): RpcStreamCallBuilder<T, Used | "serialization">;
  /** Serialize the envelope as protobuf using the operation's frozen descriptor. */
  useProtobuf(): RpcStreamCallBuilder<T, Used | "serialization">;
  /** Select the serialization strategy from a value instead of a dedicated method. */
  useSerialStrategy(strategy: StratValue): RpcStreamCallBuilder<T, Used | "serialization">;
}

export interface RpcStreamCallBuilderStreamRateLimit<T = unknown, Used extends RpcExclusiveGroup = never> {
  /** Emit an item only after the producer has been quiet for this interval. */
  debounceEach(millis: number): RpcStreamCallBuilder<T, Used | "stream_rate_limit">;
  /** Emit the most recent item once per interval. */
  sampleEach(millis: number): RpcStreamCallBuilder<T, Used | "stream_rate_limit">;
  /** Emit the leading item in each interval and drop the rest. */
  throttleEach(millis: number): RpcStreamCallBuilder<T, Used | "stream_rate_limit">;
}

/**
 * A streaming RPC chain. Spending an exclusive group removes it from the type, so
 * a contradictory second selection is a compile error.
 */
export type RpcStreamCallBuilder<T = unknown, Used extends RpcExclusiveGroup = never> =
  RpcStreamCallBuilderCore<T, Used>
  & ("auth_mode" extends Used ? {} : RpcStreamCallBuilderAuthMode<T, Used>)
  & ("ip_version" extends Used ? {} : RpcStreamCallBuilderIpVersion<T, Used>)
  & ("serialization" extends Used ? {} : RpcStreamCallBuilderSerialization<T, Used>)
  & ("stream_rate_limit" extends Used ? {} : RpcStreamCallBuilderStreamRateLimit<T, Used>);

