#![allow(clippy::needless_return)]

use ores_api_docs::{
    render_module_interface_matrix, ModuleInterfaceLanguage, ModuleInterfaceRuntimeProfile,
    ModuleInterfaceSpec,
};
use serde::Deserialize;
use serde_json::Value;

const CONTRACT_VERSION: &str = "ores.module-interface-codegen/v1";
const TYPESPEC: &str = include_str!(
    "../../contracts/module-interface-codegen/module-interface-codegen.tsp"
);
const JSON_SCHEMA: &str = include_str!(
    "../../contracts/module-interface-codegen/module-interface-codegen.schema.json"
);
const SCINTILLA_FIXTURE: &str = include_str!(
    "../../contracts/module-interface-codegen/fixtures/scintilla-worker.json"
);

#[derive(Debug, Deserialize)]
struct CodegenRequest {
    contract_version: String,
    runtime_profile: ModuleInterfaceRuntimeProfile,
    languages: Vec<ModuleInterfaceLanguage>,
    module: ModuleInterfaceSpec,
}

fn language_ids() -> Vec<&'static str> {
    return ModuleInterfaceLanguage::ALL
        .iter()
        .copied()
        .map(ModuleInterfaceLanguage::as_str)
        .collect();
}

fn enum_body<'a>(source: &'a str, enum_name: &str) -> &'a str {
    let marker = format!("enum {enum_name}");
    let enum_start = source.find(&marker).expect("TypeSpec enum must exist");
    let after_name = &source[enum_start + marker.len()..];
    let open = after_name.find('{').expect("TypeSpec enum must open");
    let body = &after_name[open + 1..];
    let close = body.find('}').expect("TypeSpec enum must close");
    return &body[..close];
}

#[test]
fn authored_authorities_cover_the_exact_rust_language_registry() {
    assert!(TYPESPEC.contains(CONTRACT_VERSION));

    let schema: Value = serde_json::from_str(JSON_SCHEMA).expect("JSON Schema authority is JSON");
    assert_eq!(
        schema["properties"]["contract_version"]["const"],
        CONTRACT_VERSION
    );

    let schema_languages = schema["$defs"]["language"]["enum"]
        .as_array()
        .expect("language enum is an array")
        .iter()
        .map(|value| value.as_str().expect("language is a string"))
        .collect::<Vec<_>>();
    let rust_languages = language_ids();
    assert_eq!(schema_languages, rust_languages);

    let tsp_languages = enum_body(TYPESPEC, "ModuleInterfaceLanguage");
    for language in rust_languages {
        assert!(
            tsp_languages
                .split(',')
                .map(str::trim)
                .any(|value| value == language),
            "TypeSpec language enum is missing {language}"
        );
    }

    let runtime_profiles = schema["$defs"]["runtime_profile"]["enum"]
        .as_array()
        .expect("runtime profile enum is an array")
        .iter()
        .map(|value| value.as_str().expect("runtime profile is a string"))
        .collect::<Vec<_>>();
    assert_eq!(runtime_profiles, vec!["ores_stack", "scintilla", "beam_scale"]);

    let tsp_profiles = enum_body(TYPESPEC, "ModuleInterfaceRuntimeProfile");
    for runtime_profile in runtime_profiles {
        assert!(
            tsp_profiles
                .split(',')
                .map(str::trim)
                .any(|value| value == runtime_profile),
            "TypeSpec runtime profile enum is missing {runtime_profile}"
        );
    }
}

#[test]
fn retained_scintilla_fixture_validates_deserializes_and_renders() {
    let schema: Value = serde_json::from_str(JSON_SCHEMA).expect("JSON Schema authority is JSON");
    let fixture: Value = serde_json::from_str(SCINTILLA_FIXTURE).expect("fixture is JSON");
    let validator = jsonschema::validator_for(&schema).expect("JSON Schema authority compiles");
    validator
        .validate(&fixture)
        .expect("retained fixture conforms to authored JSON Schema");

    let request: CodegenRequest =
        serde_json::from_value(fixture).expect("fixture deserializes into Rust projection types");
    assert_eq!(request.contract_version, CONTRACT_VERSION);
    assert_eq!(request.runtime_profile, ModuleInterfaceRuntimeProfile::Scintilla);
    assert_eq!(request.languages, ModuleInterfaceLanguage::ALL);

    let artifacts = render_module_interface_matrix(
        request.runtime_profile,
        &request.languages,
        &request.module,
    )
    .expect("validated fixture renders through shared codegen");

    assert_eq!(artifacts.len(), 13);
    assert!(artifacts.iter().all(|artifact| {
        artifact
            .source
            .contains("@generated by ORESoftware/api-docs module-interface-codegen")
    }));
    assert!(artifacts.iter().all(|artifact| {
        artifact.source.contains("ores-stack.worker.v1")
    }));
}
