// @generated by ores-stack rpc; do not edit

export interface User {
  id: string;
  display_name: string;
}

export interface OperationEnvelope<T> {
  result: T;
  traceIds: string[];
}

export interface CreateUserRequest {
  id: string;
  display_name: string;
}

export interface UpdateUserRequest {
  display_name: string;
}

interface RpcReceipt<T> {
  ok: boolean;
  body?: T;
  error?: unknown;
  traceId?: string;
  spanId?: string;
}

const TRACE_ID = "4bf92f3577b34da6a3ce929d0e0e4736";
const SPAN_ID = "00f067aa0ba902b7";

export class ProofRpcClient {
  constructor(private readonly baseUrl: string) {}

  createUser(tenant: string, request: CreateUserRequest): Promise<OperationEnvelope<User>> {
    return this.call("demo.users.create_user", {
      headers: { "x-ores-tenant": tenant },
      body: request,
    });
  }

  findUserById(
    userId: string,
    includeDisabled: boolean | null,
    ifNoneMatch: string | null,
  ): Promise<OperationEnvelope<User>> {
    return this.call("demo.users.find_user_by_id", {
      path: { user_id: userId },
      query: { include_disabled: includeDisabled },
      headers: { "if-none-match": ifNoneMatch },
    });
  }

  updateUser(
    userId: string,
    idempotencyKey: string,
    request: UpdateUserRequest,
  ): Promise<OperationEnvelope<User>> {
    return this.call("demo.users.update_user", {
      path: { user_id: userId },
      headers: { "idempotency-key": idempotencyKey },
      body: request,
    });
  }

  private async call<T>(
    key: string,
    input: {
      path?: Readonly<Record<string, unknown>>;
      query?: Readonly<Record<string, unknown>>;
      headers?: Readonly<Record<string, unknown>>;
      body?: unknown;
    },
  ): Promise<T> {
    const response = await fetch(`${this.baseUrl}/v1/rpc`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        v: 1,
        op: "call",
        id: `ts-${key}`,
        key,
        transport: "http",
        ...input,
        traceId: TRACE_ID,
        spanId: SPAN_ID,
      }),
    });
    const receipt = (await response.json()) as RpcReceipt<T>;
    if (!receipt.ok || receipt.body === undefined) {
      throw new Error(`RPC ${key} failed: ${JSON.stringify(receipt.error)}`);
    }
    if (receipt.traceId !== TRACE_ID || receipt.spanId !== SPAN_ID) {
      throw new Error(`RPC ${key} lost dynamic trace/span correlation`);
    }
    return receipt.body;
  }
}
