// @generated by ores-stack sync; do not edit

import 'dart:convert';
import 'dart:io';

class User {
  const User({required this.id, required this.displayName});

  final String id;
  final String displayName;

  factory User.fromJson(Map<String, Object?> json) => User(
        id: json['id']! as String,
        displayName: json['display_name']! as String,
      );
}

class OperationEnvelope<T> {
  const OperationEnvelope({required this.result, required this.traceIds});

  final T result;
  final List<String> traceIds;
}

class CreateUserRequest {
  const CreateUserRequest({required this.id, required this.displayName});

  final String id;
  final String displayName;

  Map<String, Object?> toJson() => {
        'id': id,
        'display_name': displayName,
      };
}

class UpdateUserRequest {
  const UpdateUserRequest({required this.displayName});

  final String displayName;

  Map<String, Object?> toJson() => {'display_name': displayName};
}

class ProofRpcClient {
  ProofRpcClient(this.baseUrl);

  final String baseUrl;
  static const _traceId = '4bf92f3577b34da6a3ce929d0e0e4736';
  static const _spanId = '00f067aa0ba902b7';

  Future<OperationEnvelope<User>> createUser(
    String tenant,
    CreateUserRequest request,
  ) async {
    final body = await _call(
      key: 'demo.users.create_user',
      headers: {'x-ores-tenant': tenant},
      body: request.toJson(),
    );
    return _userEnvelope(body);
  }

  Future<OperationEnvelope<User>> findUserById(
    String userId,
    bool? includeDisabled,
    String? ifNoneMatch,
  ) async {
    final body = await _call(
      key: 'demo.users.find_user_by_id',
      path: {'user_id': userId},
      query: {'include_disabled': includeDisabled},
      headers: {'if-none-match': ifNoneMatch},
    );
    return _userEnvelope(body);
  }

  Future<OperationEnvelope<User>> updateUser(
    String userId,
    String idempotencyKey,
    UpdateUserRequest request,
  ) async {
    final body = await _call(
      key: 'demo.users.update_user',
      path: {'user_id': userId},
      headers: {'idempotency-key': idempotencyKey},
      body: request.toJson(),
    );
    return _userEnvelope(body);
  }

  Future<Map<String, Object?>> _call({
    required String key,
    Map<String, Object?>? path,
    Map<String, Object?>? query,
    Map<String, Object?>? headers,
    Map<String, Object?>? body,
  }) async {
    final client = HttpClient();
    try {
      final request = await client.postUrl(Uri.parse('$baseUrl/v1/rpc'));
      request.headers.contentType = ContentType.json;
      request.write(jsonEncode({
        'v': 1,
        'op': 'call',
        'id': 'dart-$key',
        'key': key,
        'transport': 'http',
        if (path != null) 'path': path,
        if (query != null) 'query': query,
        if (headers != null) 'headers': headers,
        if (body != null) 'body': body,
        'traceId': _traceId,
        'spanId': _spanId,
      }));
      final response = await request.close();
      final text = await utf8.decoder.bind(response).join();
      final decoded = jsonDecode(text);
      if (decoded is! Map) {
        throw StateError('RPC receipt is not an object: $text');
      }
      final receipt = Map<String, Object?>.from(decoded);
      if (receipt['ok'] != true) {
        throw StateError('RPC $key failed: ${receipt['error']}');
      }
      if (receipt['traceId'] != _traceId || receipt['spanId'] != _spanId) {
        throw StateError('RPC $key lost dynamic trace/span correlation');
      }
      final result = receipt['body'];
      if (result is! Map) throw StateError('RPC $key body missing');
      return Map<String, Object?>.from(result);
    } finally {
      client.close(force: true);
    }
  }

  static OperationEnvelope<User> _userEnvelope(Map<String, Object?> json) {
    final result = json['result'];
    final traces = json['traceIds'];
    if (result is! Map || traces is! List) {
      throw StateError('typed response envelope is malformed');
    }
    return OperationEnvelope<User>(
      result: User.fromJson(Map<String, Object?>.from(result)),
      traceIds: traces.cast<String>(),
    );
  }
}
