from __future__ import annotations

import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).with_name("generate-rpc-docs.py")
SPEC = importlib.util.spec_from_file_location("generate_rpc_docs", SCRIPT)
assert SPEC and SPEC.loader
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


class RpcDocCouplingTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        (self.root / "generated").mkdir()
        self.route = {
            "schema_version": "2.0.0",
            "service": "demo",
            "version": "1.2.3",
            "types": {},
            "map": {
                "watch": {
                    "path": "/v1/watch/{id}",
                    "methods": ["GET"],
                    "transports": ["websocket", "tcp"],
                    "stream": "server_stream",
                    "response": "String",
                }
            },
        }
        self._write_json("route.json", self.route)
        mechanisms = {
            "rust": ("trait", "RpcTransport"),
            "typescript": ("interface", "RpcTransport"),
            "dart": ("abstract_interface_class", "RpcTransport"),
            "gleam": ("function_type", "Transport"),
            "go": ("interface", "RPCTransport"),
            "python": ("protocol", "RpcTransport"),
            "kotlin": ("interface", "RpcTransport"),
            "swift": ("protocol", "RidlTransport"),
        }
        surfaces = []
        for language, (kind, symbol) in mechanisms.items():
            file = f"generated/{language}.txt"
            (self.root / file).write_text(
                f"Generated by ridl\n{symbol}\n"
                'OperationInfo("watch", "/v1/watch/{id}", ["GET"], '
                '["websocket", "tcp"], "server_stream")\n',
                encoding="utf-8",
            )
            surfaces.append(
                {
                    "language": language,
                    "role": "client",
                    "mechanism": kind,
                    "file": file,
                    "symbol": symbol,
                }
            )
        self.manifest = {
            "schema_version": "1.0.0",
            "service": "demo",
            "route_map": "route.json",
            "docs_output": "generated/docs.json",
            "required_languages": list(mechanisms),
            "surfaces": surfaces,
        }
        self._write_json("surface.json", self.manifest)
        self._write_json(
            "rpc-coupling.json",
            {"schema_version": "1.0.0", "manifests": ["surface.json"]},
        )

    def tearDown(self) -> None:
        self.temp.cleanup()

    def _write_json(self, path: str, value: object) -> None:
        target = self.root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")

    def _run(self, flag: str) -> int:
        return MODULE.run([flag, "--root", str(self.root)])

    def test_write_then_check_is_deterministic_and_fingerprinted(self) -> None:
        self.assertEqual(self._run("--write"), 0)
        first = (self.root / "generated/docs.json").read_bytes()
        self.assertEqual(self._run("--check"), 0)
        self.assertEqual(self._run("--write"), 0)
        self.assertEqual(first, (self.root / "generated/docs.json").read_bytes())
        document = json.loads(first)
        self.assertEqual(
            document["operations"][0]["rpc_method_id"], "demo.watch"
        )
        self.assertRegex(
            document["operations"][0]["contract_sha256"],
            r"^[0-9a-f]{64}$",
        )
        self.assertRegex(document["document_sha256"], r"^[0-9a-f]{64}$")
        self.assertEqual(len(document["language_surfaces"]), 8)

    def test_document_drift_fails_closed(self) -> None:
        self.assertEqual(self._run("--write"), 0)
        (self.root / "generated/docs.json").write_text("{}\n", encoding="utf-8")
        self.assertEqual(self._run("--check"), 1)

    def test_missing_required_language_is_rejected(self) -> None:
        self.manifest["surfaces"].pop()
        self._write_json("surface.json", self.manifest)
        self.assertEqual(self._run("--write"), 1)

    def test_transport_or_stream_drift_in_one_language_is_rejected(self) -> None:
        swift = self.root / "generated/swift.txt"
        swift.write_text(
            swift.read_text(encoding="utf-8").replace(
                '"server_stream"', '"unary"'
            ),
            encoding="utf-8",
        )
        self.assertEqual(self._run("--write"), 1)

    def test_source_path_traversal_is_rejected(self) -> None:
        self.manifest["surfaces"][0]["file"] = "../outside.rs"
        self._write_json("surface.json", self.manifest)
        self.assertEqual(self._run("--write"), 1)

    def test_route_change_changes_contract_and_document_fingerprints(self) -> None:
        self.assertEqual(self._run("--write"), 0)
        before = json.loads((self.root / "generated/docs.json").read_text())
        self.route["map"]["watch"]["methods"] = ["POST"]
        self._write_json("route.json", self.route)
        for language in self.manifest["required_languages"]:
            path = self.root / f"generated/{language}.txt"
            path.write_text(
                path.read_text().replace('["GET"]', '["POST"]'),
                encoding="utf-8",
            )
        self.assertEqual(self._run("--write"), 0)
        after = json.loads((self.root / "generated/docs.json").read_text())
        self.assertNotEqual(
            before["operations"][0]["contract_sha256"],
            after["operations"][0]["contract_sha256"],
        )
        self.assertNotEqual(before["document_sha256"], after["document_sha256"])

    def test_binding_metadata_is_closed(self) -> None:
        self.manifest["surfaces"][0]["unreviewed"] = True
        self._write_json("surface.json", self.manifest)
        self.assertEqual(self._run("--write"), 1)


if __name__ == "__main__":
    unittest.main()
