//! Deterministic Markdown projection of the RPC client option catalog.
//!
//! Output is a pure function of the catalog bytes: no clock, no environment,
//! no network, no model. Running the generator twice on the same input yields
//! byte-identical output, which `ores-rpc-docs check` enforces in CI.

use super::model::{AppliesTo, Catalog, Option_};
use super::names::Language;
use std::fmt::Write as _;

const GENERATED_NOTICE: &str =
    "<!-- Generated by `cargo run --bin ores-rpc-docs -- generate`. Do not edit by hand. -->";

pub fn render(catalog: &Catalog) -> String {
    let mut out = String::with_capacity(32 * 1024);

    let _ = writeln!(out, "{GENERATED_NOTICE}");
    let _ = writeln!(out);
    let _ = writeln!(out, "# RPC client options");
    let _ = writeln!(out);
    let _ = writeln!(out, "{}", catalog.description);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Catalog version `{}`. All calls are carried over `POST {}`.",
        catalog.catalog_version, catalog.rpc_path
    );
    let _ = writeln!(out);

    render_surfaces(&mut out, catalog);
    render_exclusive_groups(&mut out, catalog);
    render_enums(&mut out, catalog);
    render_groups(&mut out, catalog);
    render_language_index(&mut out, catalog);

    out
}

fn render_surfaces(out: &mut String, catalog: &Catalog) {
    let unary = catalog.unary_options().count();
    let stream = catalog.stream_options().count();
    let both = catalog
        .options
        .iter()
        .filter(|o| o.applies_to == AppliesTo::Both)
        .count();

    let _ = writeln!(out, "## Two client surfaces");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "The unary client and the streaming client are separate types. A chain terminates in \
         `make_call` or in `stream`, never in both: the terminal method is the only network \
         boundary on its surface, and neither builder exposes the other's terminal."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "| Surface | Terminal | Options reachable |");
    let _ = writeln!(out, "| --- | --- | --- |");
    let _ = writeln!(out, "| Unary | `make_call`, `make_call_or_throw` | {unary} |");
    let _ = writeln!(out, "| Streaming | `stream` | {stream} |");
    let _ = writeln!(out, "| Shared by both | — | {both} |");
    let _ = writeln!(out);
}

fn render_exclusive_groups(out: &mut String, catalog: &Catalog) {
    let _ = writeln!(out, "## Contradiction-free by construction");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Options in an exclusive group are one-way doors. Selecting one returns a narrowed \
         builder type that no longer carries any member of that group, so a contradictory \
         second selection is a compile error rather than a runtime check."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "| Group | Members | Default | Purpose |");
    let _ = writeln!(out, "| --- | --- | --- | --- |");
    for group in &catalog.exclusive_groups {
        let members: Vec<&str> = catalog
            .options
            .iter()
            .filter(|o| o.exclusive_group.as_deref() == Some(group.exclusive_group_id.as_str()))
            .map(|o| o.option_id.as_str())
            .collect();
        let rendered: Vec<String> = members.iter().map(|m| format!("`{m}`")).collect();
        let default = group
            .default_option_id
            .as_deref()
            .map_or_else(|| "none".to_owned(), |d| format!("`{d}`"));
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} |",
            group.exclusive_group_id,
            rendered.join(", "),
            default,
            group.summary
        );
    }
    let _ = writeln!(out);
}

fn render_enums(out: &mut String, catalog: &Catalog) {
    let _ = writeln!(out, "## Option value enums");
    let _ = writeln!(out);
    for catalog_enum in &catalog.enums {
        let _ = writeln!(
            out,
            "### `{}` ({})",
            catalog_enum.enum_id, catalog_enum.namespace
        );
        let _ = writeln!(out);
        let _ = writeln!(out, "| Variant | Wire value | Header effect |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for variant in &catalog_enum.variants {
            let effect = match (&variant.content_type, &variant.content_encoding) {
                (Some(ct), _) => format!("`content-type: {ct}`"),
                (None, Some(ce)) => format!("`content-encoding: {ce}`"),
                (None, None) => "—".to_owned(),
            };
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} |",
                variant.variant_id, scalar(&variant.wire_value), effect
            );
        }
        let _ = writeln!(out);
    }
}

fn render_groups(out: &mut String, catalog: &Catalog) {
    let _ = writeln!(out, "## Options by group");
    let _ = writeln!(out);
    for group in catalog.groups() {
        let _ = writeln!(out, "### {group}");
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "| Option | Surface | Repeatable | Signature | Plan field | Wire effect |"
        );
        let _ = writeln!(out, "| --- | --- | --- | --- | --- | --- |");
        for option in catalog.options.iter().filter(|o| o.group == group) {
            let _ = writeln!(
                out,
                "| `{}` | {} | {} | `{}` | {} | {} |",
                option.option_id,
                option.applies_to.as_str(),
                if option.arity == super::model::Arity::Many {
                    "yes"
                } else {
                    "no"
                },
                signature(option),
                plan_field_cell(option),
                wire_cell(option, catalog)
            );
        }
        let _ = writeln!(out);
        for option in catalog.options.iter().filter(|o| o.group == group) {
            let _ = writeln!(out, "- `{}` — {}", option.option_id, option.summary);
            if let Some(capability) = &option.requires_capability {
                let _ = writeln!(
                    out,
                    "  - Refused unless the client declares the `{capability}` capability."
                );
            }
            if option.secret {
                let _ = writeln!(
                    out,
                    "  - Carries a credential. It is redacted from request plans, debug output and logs."
                );
            }
        }
        let _ = writeln!(out);
    }
}

fn render_language_index(out: &mut String, catalog: &Catalog) {
    let _ = writeln!(out, "## Derived method names");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "These spellings are derived from `option_id`, not authored. A client that spells a \
         method differently is out of contract."
    );
    let _ = writeln!(out);

    let mut header = String::from("| Option |");
    let mut divider = String::from("| --- |");
    for language in Language::ALL {
        let _ = write!(header, " {} |", language.as_str());
        divider.push_str(" --- |");
    }
    let _ = writeln!(out, "{header}");
    let _ = writeln!(out, "{divider}");

    for option in &catalog.options {
        let _ = write!(out, "| `{}` |", option.option_id);
        for language in Language::ALL {
            let _ = write!(out, " `{}` |", language.method_name(&option.option_id));
        }
        let _ = writeln!(out);
    }
    let _ = writeln!(out);
}

fn signature(option: &Option_) -> String {
    let params: Vec<String> = option
        .params
        .iter()
        .map(|p| match p.ty.as_str() {
            "enum" => format!(
                "{}: {}",
                p.name,
                p.enum_id.as_deref().unwrap_or("enum")
            ),
            "callback" => format!(
                "{}: {}",
                p.name,
                p.signature.as_deref().unwrap_or("callback")
            ),
            other => format!("{}: {other}", p.name),
        })
        .collect();
    let returns = option.returns.as_deref().unwrap_or("self");
    format!("{}({}) -> {returns}", option.option_id, params.join(", "))
}

fn plan_field_cell(option: &Option_) -> String {
    match &option.plan_field {
        None => "—".to_owned(),
        Some(field) => match &option.plan_value {
            None => format!("`{field}`"),
            Some(value) => format!("`{field}` = `{}`", scalar(value)),
        },
    }
}

fn wire_cell(option: &Option_, catalog: &Catalog) -> String {
    let Some(wire) = &option.wire else {
        return if option.local_only {
            "client-local".to_owned()
        } else {
            "—".to_owned()
        };
    };
    let mut parts: Vec<String> = Vec::new();
    for (name, value) in &wire.headers {
        parts.push(format!("`{name}: {value}`"));
    }
    for name in &wire.drop_headers {
        parts.push(format!("drops `{name}`"));
    }
    if let Some(source) = &wire.headers_from_enum {
        let enum_id = option
            .params
            .iter()
            .find_map(|p| p.enum_id.as_deref())
            .unwrap_or("");
        let variants = catalog
            .enum_by_id(enum_id)
            .map(|e| e.variants.len())
            .unwrap_or(0);
        parts.push(format!(
            "header from the selected `{enum_id}` variant's `{source}` ({variants} variants)"
        ));
    }
    if parts.is_empty() {
        "—".to_owned()
    } else {
        parts.join("; ")
    }
}

/// Render a JSON scalar the way a reader would type it, not the way JSON
/// quotes it: `json` rather than `"json"`, `3` rather than `3`.
fn scalar(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::String(text) => text.clone(),
        other => other.to_string(),
    }
}
