//! Generated TypeScript surface for the RPC client option catalog.
//!
//! Two artifacts are emitted into the TypeScript client package:
//!
//! * `options.generated.js` — the runtime option table. The fluent builders
//!   install their method surface from this table, so a method can only exist
//!   in the client if the catalog declares it.
//! * `options.generated.d.ts` — the type-state types. Each exclusive group is a
//!   phantom marker: selecting a member returns a builder whose type no longer
//!   carries that group, so a contradictory second selection does not compile.

use super::model::{AppliesTo, Catalog, Option_};
use super::names::Language;
use std::fmt::Write as _;

const NOTICE: &str =
    "// Generated by `cargo run --bin ores-rpc-docs -- generate`. Do not edit by hand.";

pub fn render_runtime(catalog: &Catalog) -> String {
    let mut out = String::with_capacity(32 * 1024);
    let _ = writeln!(out, "{NOTICE}");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "export const CATALOG_VERSION = {};",
        json_string(&catalog.catalog_version)
    );
    let _ = writeln!(
        out,
        "export const DEFAULT_RPC_PATH = {};",
        json_string(&catalog.rpc_path)
    );
    let _ = writeln!(out, "export const PLAN_VERSION = \"1.0.0\";");
    let _ = writeln!(out);

    // Final-boundary plan redaction. The catalog owns these lists so the
    // TypeScript and Rust clients cannot disagree about what a plan hides.
    let redaction = &catalog.plan_redaction;
    let list = |values: &[String]| {
        values
            .iter()
            .map(|value| json_string(value))
            .collect::<Vec<_>>()
            .join(", ")
    };
    let _ = writeln!(
        out,
        "export const REDACTED = {};",
        json_string(&redaction.redacted_placeholder)
    );
    let _ = writeln!(
        out,
        "export const REDACTED_HEADER_NAMES = Object.freeze([{}]);",
        list(&redaction.header_names)
    );
    let _ = writeln!(
        out,
        "export const REDACTED_HEADER_PATTERNS = Object.freeze([{}]);",
        list(&redaction.header_name_patterns)
    );
    let _ = writeln!(
        out,
        "export const REDACTED_URL_FIELDS = Object.freeze([{}]);",
        list(&redaction.url_fields)
    );
    let _ = writeln!(out);

    // Enums, as frozen namespaces. `Rpc.Strat.JSON` and friends.
    let _ = writeln!(out, "export const Rpc = Object.freeze({{");
    for catalog_enum in &catalog.enums {
        let namespace = catalog_enum
            .namespace
            .rsplit('.')
            .next()
            .unwrap_or(&catalog_enum.namespace);
        let _ = writeln!(out, "  {namespace}: Object.freeze({{");
        for variant in &catalog_enum.variants {
            let _ = writeln!(
                out,
                "    {}: {},",
                Language::TypeScript.variant_name(&variant.variant_id),
                serde_json::to_string(&variant.wire_value).unwrap_or_else(|_| "null".to_owned())
            );
        }
        let _ = writeln!(out, "  }}),");
    }
    let _ = writeln!(out, "}});");
    let _ = writeln!(out);

    // Enum header effects, used to translate a selected variant into headers.
    let _ = writeln!(out, "export const ENUM_HEADER_EFFECTS = Object.freeze({{");
    for catalog_enum in &catalog.enums {
        let _ = writeln!(out, "  {}: Object.freeze({{", catalog_enum.enum_id);
        for variant in &catalog_enum.variants {
            let mut effects: Vec<String> = Vec::new();
            if let Some(content_type) = &variant.content_type {
                effects.push(format!(
                    "\"content-type\": {}, accept: {}",
                    json_string(content_type),
                    json_string(content_type)
                ));
            }
            if let Some(content_encoding) = &variant.content_encoding {
                effects.push(format!(
                    "\"content-encoding\": {}",
                    json_string(content_encoding)
                ));
            }
            let key =
                serde_json::to_string(&variant.wire_value).unwrap_or_else(|_| "null".to_owned());
            let _ = writeln!(
                out,
                "    [{key}]: Object.freeze({{ {} }}),",
                effects.join(", ")
            );
        }
        let _ = writeln!(out, "  }}),");
    }
    let _ = writeln!(out, "}});");
    let _ = writeln!(out);

    let _ = writeln!(out, "export const EXCLUSIVE_GROUPS = Object.freeze([");
    for group in &catalog.exclusive_groups {
        let _ = writeln!(out, "  {},", json_string(&group.exclusive_group_id));
    }
    let _ = writeln!(out, "]);");
    let _ = writeln!(out);

    let _ = writeln!(out, "export const OPTIONS = Object.freeze([");
    for option in &catalog.options {
        if option.terminal {
            // Terminals are hand-written: they are the network boundary.
            continue;
        }
        let _ = writeln!(out, "  Object.freeze({{");
        let _ = writeln!(out, "    id: {},", json_string(&option.option_id));
        let _ = writeln!(
            out,
            "    method: {},",
            json_string(&Language::TypeScript.method_name(&option.option_id))
        );
        let _ = writeln!(out, "    group: {},", json_string(&option.group));
        let _ = writeln!(
            out,
            "    appliesTo: {},",
            json_string(option.applies_to.as_str())
        );
        let _ = writeln!(out, "    arity: {},", json_string(option.arity.as_str()));
        let _ = writeln!(
            out,
            "    exclusiveGroup: {},",
            option
                .exclusive_group
                .as_deref()
                .map_or_else(|| "null".to_owned(), json_string)
        );
        let _ = writeln!(
            out,
            "    planField: {},",
            option
                .plan_field
                .as_deref()
                .map_or_else(|| "null".to_owned(), json_string)
        );
        let _ = writeln!(
            out,
            "    planValue: {},",
            option.plan_value.as_ref().map_or_else(
                || "undefined".to_owned(),
                |v| serde_json::to_string(v).unwrap_or_else(|_| "undefined".to_owned())
            )
        );
        let _ = writeln!(out, "    secret: {},", option.secret);
        let _ = writeln!(out, "    localOnly: {},", option.local_only);
        let _ = writeln!(
            out,
            "    requiresCapability: {},",
            option
                .requires_capability
                .as_deref()
                .map_or_else(|| "null".to_owned(), json_string)
        );
        let _ = writeln!(out, "    params: {},", render_params(option));
        let _ = writeln!(out, "    wire: {},", render_wire(option));
        let _ = writeln!(out, "  }}),");
    }
    let _ = writeln!(out, "]);");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "export const OPTIONS_BY_SURFACE = Object.freeze({{\n  unary: Object.freeze(OPTIONS.filter((o) => o.appliesTo !== \"stream\")),\n  stream: Object.freeze(OPTIONS.filter((o) => o.appliesTo !== \"unary\")),\n}});"
    );
    out
}

fn render_params(option: &Option_) -> String {
    let rendered: Vec<String> = option
        .params
        .iter()
        .map(|param| {
            let mut parts = vec![
                format!("name: {}", json_string(&param.name)),
                format!("type: {}", json_string(&param.ty)),
            ];
            if let Some(enum_id) = &param.enum_id {
                parts.push(format!("enumId: {}", json_string(enum_id)));
            }
            if let Some(minimum) = param.minimum {
                parts.push(format!("minimum: {}", trim_number(minimum)));
            }
            if let Some(maximum) = param.maximum {
                parts.push(format!("maximum: {}", trim_number(maximum)));
            }
            if let Some(max_length) = param.max_length {
                parts.push(format!("maxLength: {max_length}"));
            }
            format!("Object.freeze({{ {} }})", parts.join(", "))
        })
        .collect();
    format!("Object.freeze([{}])", rendered.join(", "))
}

fn render_wire(option: &Option_) -> String {
    let Some(wire) = &option.wire else {
        return "null".to_owned();
    };
    let mut parts: Vec<String> = Vec::new();
    if !wire.headers.is_empty() {
        let headers: Vec<String> = wire
            .headers
            .iter()
            .map(|(name, value)| format!("[{}]: {}", json_string(name), json_string(value)))
            .collect();
        parts.push(format!(
            "headers: Object.freeze({{ {} }})",
            headers.join(", ")
        ));
    }
    if !wire.drop_headers.is_empty() {
        let dropped: Vec<String> = wire.drop_headers.iter().map(|h| json_string(h)).collect();
        parts.push(format!(
            "dropHeaders: Object.freeze([{}])",
            dropped.join(", ")
        ));
    }
    if let Some(source) = &wire.headers_from_enum {
        parts.push(format!("headersFromEnum: {}", json_string(source)));
    }
    format!("Object.freeze({{ {} }})", parts.join(", "))
}

pub fn render_types(catalog: &Catalog) -> String {
    let mut out = String::with_capacity(32 * 1024);
    let _ = writeln!(out, "{NOTICE}");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "import type {{\n  RpcJsonObject,\n  RpcOutcome,\n  RpcRequestPlan,\n  RpcStreamHandle,\n}} from \"./fluent-types.js\";"
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "export declare const CATALOG_VERSION: string;");
    let _ = writeln!(out, "export declare const DEFAULT_RPC_PATH: string;");
    let _ = writeln!(out, "export declare const PLAN_VERSION: \"1.0.0\";");
    let _ = writeln!(out);

    for catalog_enum in &catalog.enums {
        let namespace = catalog_enum
            .namespace
            .rsplit('.')
            .next()
            .unwrap_or(&catalog_enum.namespace);
        let values: Vec<String> = catalog_enum
            .variants
            .iter()
            .map(|v| serde_json::to_string(&v.wire_value).unwrap_or_else(|_| "never".to_owned()))
            .collect();
        let _ = writeln!(
            out,
            "export type {namespace}Value = {};",
            values.join(" | ")
        );
    }
    let _ = writeln!(out);

    let groups: Vec<String> = catalog
        .exclusive_groups
        .iter()
        .map(|g| json_string(&g.exclusive_group_id))
        .collect();
    let _ = writeln!(
        out,
        "/** Exclusive groups are phantom markers on the builder type. */\nexport type RpcExclusiveGroup = {};",
        groups.join(" | ")
    );
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "export interface RpcOptionDescriptor {{\n  readonly id: string;\n  readonly method: string;\n  readonly group: string;\n  readonly appliesTo: \"unary\" | \"stream\" | \"both\";\n  readonly arity: \"once\" | \"many\";\n  readonly exclusiveGroup: RpcExclusiveGroup | null;\n  readonly planField: string | null;\n  readonly planValue?: unknown;\n  readonly secret: boolean;\n  readonly localOnly: boolean;\n  readonly requiresCapability: string | null;\n  readonly params: ReadonlyArray<{{ readonly name: string; readonly type: string; readonly enumId?: string; readonly minimum?: number; readonly maximum?: number; readonly maxLength?: number }}>;\n  readonly wire: unknown;\n}}"
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "export declare const REDACTED: string;");
    let _ = writeln!(
        out,
        "export declare const REDACTED_HEADER_NAMES: ReadonlyArray<string>;"
    );
    let _ = writeln!(
        out,
        "export declare const REDACTED_HEADER_PATTERNS: ReadonlyArray<string>;"
    );
    let _ = writeln!(
        out,
        "export declare const REDACTED_URL_FIELDS: ReadonlyArray<string>;"
    );
    let _ = writeln!(
        out,
        "export declare const OPTIONS: ReadonlyArray<RpcOptionDescriptor>;"
    );
    let _ = writeln!(
        out,
        "export declare const OPTIONS_BY_SURFACE: {{ readonly unary: ReadonlyArray<RpcOptionDescriptor>; readonly stream: ReadonlyArray<RpcOptionDescriptor> }};"
    );
    let _ = writeln!(
        out,
        "export declare const EXCLUSIVE_GROUPS: ReadonlyArray<RpcExclusiveGroup>;"
    );
    let _ = writeln!(out, "export declare const ENUM_HEADER_EFFECTS: Readonly<Record<string, Readonly<Record<string, Readonly<Record<string, string>>>>>>;");
    let _ = writeln!(out);

    let _ = writeln!(out, "export declare const Rpc: {{");
    for catalog_enum in &catalog.enums {
        let namespace = catalog_enum
            .namespace
            .rsplit('.')
            .next()
            .unwrap_or(&catalog_enum.namespace);
        let _ = writeln!(out, "  readonly {namespace}: {{");
        for variant in &catalog_enum.variants {
            let _ = writeln!(
                out,
                "    readonly {}: {};",
                Language::TypeScript.variant_name(&variant.variant_id),
                serde_json::to_string(&variant.wire_value).unwrap_or_else(|_| "never".to_owned())
            );
        }
        let _ = writeln!(out, "  }};");
    }
    let _ = writeln!(out, "}};");
    let _ = writeln!(out);

    render_builder_interface(&mut out, catalog, AppliesTo::Unary);
    render_builder_interface(&mut out, catalog, AppliesTo::Stream);

    out
}

/// Emit the type-state builder for one surface.
///
/// The builder is a generic over `Used`, the set of exclusive groups already
/// spent. Methods belonging to a spent group are conditionally removed from the
/// type, so calling one twice is a type error rather than a runtime assertion.
fn render_builder_interface(out: &mut String, catalog: &Catalog, surface: AppliesTo) {
    let (name, core, terminal_ids) = match surface {
        AppliesTo::Stream => (
            "RpcStreamCallBuilder",
            "RpcStreamCallBuilderCore",
            vec!["stream", "to_plan"],
        ),
        _ => (
            "RpcUnaryCallBuilder",
            "RpcUnaryCallBuilderCore",
            vec!["make_call", "make_call_or_throw", "to_plan"],
        ),
    };
    let generics = match surface {
        AppliesTo::Stream => "<T = unknown, Used extends RpcExclusiveGroup = never>",
        _ => "<T = unknown, E = RpcJsonObject, Used extends RpcExclusiveGroup = never>",
    };
    let self_args = match surface {
        AppliesTo::Stream => "T, Used",
        _ => "T, E, Used",
    };

    let on_surface = |option: &Option_| match surface {
        AppliesTo::Stream => option.applies_to.on_stream(),
        _ => option.applies_to.on_unary(),
    };

    // Non-exclusive options: always present, always return the same type.
    let _ = writeln!(out, "export interface {core}{generics} {{");
    for option in catalog.options.iter().filter(|o| on_surface(o)) {
        if option.exclusive_group.is_some() {
            continue;
        }
        if option.terminal || terminal_ids.contains(&option.option_id.as_str()) {
            continue;
        }
        let _ = writeln!(
            out,
            "  /** {} */\n  {}({}): {name}<{self_args}>;",
            option.summary.replace("*/", ""),
            Language::TypeScript.method_name(&option.option_id),
            ts_params(option, catalog),
        );
    }
    render_terminals(out, surface);
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);

    // One interface per exclusive group, added only while the group is unspent.
    for group in &catalog.exclusive_groups {
        let members: Vec<&Option_> = catalog
            .options
            .iter()
            .filter(|o| {
                o.exclusive_group.as_deref() == Some(group.exclusive_group_id.as_str())
                    && on_surface(o)
            })
            .collect();
        if members.is_empty() {
            continue;
        }
        let interface = group_interface_name(name, &group.exclusive_group_id);
        let _ = writeln!(out, "export interface {interface}{generics} {{");
        for option in members {
            let used = match surface {
                AppliesTo::Stream => {
                    format!("T, Used | {}", json_string(&group.exclusive_group_id))
                }
                _ => format!("T, E, Used | {}", json_string(&group.exclusive_group_id)),
            };
            let _ = writeln!(
                out,
                "  /** {} */\n  {}({}): {name}<{used}>;",
                option.summary.replace("*/", ""),
                Language::TypeScript.method_name(&option.option_id),
                ts_params(option, catalog),
            );
        }
        let _ = writeln!(out, "}}");
        let _ = writeln!(out);
    }

    // The builder is the core plus every group not yet spent.
    let mut conjuncts: Vec<String> = vec![format!("{core}<{self_args}>")];
    for group in &catalog.exclusive_groups {
        let has_members = catalog.options.iter().any(|o| {
            o.exclusive_group.as_deref() == Some(group.exclusive_group_id.as_str()) && on_surface(o)
        });
        if !has_members {
            continue;
        }
        let interface = group_interface_name(name, &group.exclusive_group_id);
        conjuncts.push(format!(
            "({} extends Used ? {{}} : {interface}<{self_args}>)",
            json_string(&group.exclusive_group_id)
        ));
    }
    let _ = writeln!(
        out,
        "/**\n * A {} RPC chain. Spending an exclusive group removes it from the type, so\n * a contradictory second selection is a compile error.\n */\nexport type {name}{generics} =\n  {};",
        match surface {
            AppliesTo::Stream => "streaming",
            _ => "unary",
        },
        conjuncts.join("\n  & ")
    );
    let _ = writeln!(out);
}

fn render_terminals(out: &mut String, surface: AppliesTo) {
    match surface {
        AppliesTo::Stream => {
            let _ = writeln!(
                out,
                "  /** Serialize the chain to a canonical request plan without opening the network. */\n  toPlan(): RpcRequestPlan;"
            );
            let _ = writeln!(
                out,
                "  /** Open the stream. The sole network boundary of the streaming client. */\n  stream(): Promise<RpcStreamHandle<T>>;"
            );
        }
        _ => {
            let _ = writeln!(
                out,
                "  /** Serialize the chain to a canonical request plan without opening the network. */\n  toPlan(): RpcRequestPlan;"
            );
            let _ = writeln!(
                out,
                "  /** Execute the call. The sole network boundary of the unary client. */\n  makeCall(): Promise<RpcOutcome<T, E>>;"
            );
            let _ = writeln!(
                out,
                "  /** Execute the call and raise on a failed receipt. */\n  makeCallOrThrow(): Promise<T>;"
            );
        }
    }
}

fn group_interface_name(builder: &str, group_id: &str) -> String {
    format!(
        "{builder}{}",
        super::names::Language::Go.method_name(group_id)
    )
}

fn ts_params(option: &Option_, catalog: &Catalog) -> String {
    option
        .params
        .iter()
        .map(|param| {
            let ty = match param.ty.as_str() {
                "enum" => param
                    .enum_id
                    .as_deref()
                    .and_then(|id| catalog.enum_by_id(id))
                    .map(|e| {
                        format!(
                            "{}Value",
                            e.namespace.rsplit('.').next().unwrap_or(&e.namespace)
                        )
                    })
                    .unwrap_or_else(|| "never".to_owned()),
                "bool" => "boolean".to_owned(),
                "u8" | "u32" | "i64" | "f64" => "number".to_owned(),
                "string" | "secret_string" | "url" => "string".to_owned(),
                "json_object" => "RpcJsonObject".to_owned(),
                "json" => "unknown".to_owned(),
                "callback" => callback_type(param),
                _ => "unknown".to_owned(),
            };
            format!(
                "{}: {ty}",
                super::names::Language::TypeScript.method_name(&param.name)
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn callback_type(param: &super::model::Param) -> String {
    // Signatures are authored in the catalog as a language-neutral shape.
    match param.signature.as_deref() {
        Some(signature) if signature.contains("attempt") => {
            "(attempt: number, cause: unknown) => void".to_owned()
        }
        Some(signature) if signature.contains("sent_bytes") => {
            "(sentBytes: number, totalBytes: number | null) => void".to_owned()
        }
        Some(signature) if signature.contains("received_bytes") => {
            "(receivedBytes: number, totalBytes: number | null) => void".to_owned()
        }
        _ => "(...args: never[]) => void".to_owned(),
    }
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "\"\"".to_owned())
}

fn trim_number(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{}", value as i64)
    } else {
        format!("{value}")
    }
}
