// @generated by ores-stack rpc; do not edit

use ores_api_docs::{RpcV1Call, RpcV1HttpContext, RpcV1Receipt};

use crate::{model::CreateUserOperation, rpc_support::invoke_json_rpc, state::AppState};

use super::handlers;

pub async fn dispatch(
    state: AppState,
    http_context: RpcV1HttpContext,
    call: RpcV1Call,
) -> RpcV1Receipt {
    invoke_json_rpc::<CreateUserOperation, _, _>(
        state,
        http_context,
        call,
        "ores-trace-proof-rpc-create-M7qT2vB9nLs",
        handlers::__ores_invoke_create_user,
    )
    .await
}
